import { describe, it, expect } from 'vitest';
import { parseLead, parseLeadPage, parseLeadRoom, sourceLeadCutoff } from '../sourceLeadData';
const id = '11111111-1111-4111-8111-111111111111';
const lead = () => ({ id, kind: 'SOURCE_LEAD', title: '來源線索：書籍', summary: '自撰事實摘要', canonicalUrl: 'https://www.facebook.com/groups/123/posts/456', county: '臺南市', district: '永康區', publicPlaceName: '公共地標', publicAddress: '臺南市永康區合成路123號', latitude: 23, longitude: 120.23, postedEarliestAt: new Date(Date.now() - 86400000).toISOString(), postedLatestAt: new Date(Date.now() - 86400000).toISOString(), checkedAt: new Date().toISOString(), stockStatus: 'UNKNOWN', qualifiedSupply: false, checkoutEnabled: false, notice: '待確認', publicFacts: null, coordinateSourceUrl: 'https://www.openstreetmap.org/node/2884639590', coordinateAttribution: { text: '© OpenStreetMap contributors', url: 'https://www.openstreetmap.org/copyright', license: 'ODbL-1.0', licenseUrl: 'https://opendatacommons.org/licenses/odbl/1-0/' } });
describe('source leads stay separate from stock and checkout', () => {
    it('accepts unknown stock without image, preserves OSM notice', () => { const r = parseLead(lead()); expect(r.stockStatus).toBe('UNKNOWN'); expect(r.checkoutEnabled).toBe(false); expect(r.coordinateAttribution?.license).toBe('ODbL-1.0'); });
    it('rejects original date beyond TPE calendar-month cutoff and stale/future checks', () => { expect(sourceLeadCutoff(Date.parse('2026-10-02T00:00:00Z'))).toBe(Date.parse('2026-08-01T16:00:00Z')); for (const patch of [{ postedEarliestAt: new Date(Date.now() - 100 * 86400000).toISOString() }, { checkedAt: new Date(Date.now() - 49 * 3600000).toISOString() }, { checkedAt: new Date(Date.now() + 3600000).toISOString() }])
        expect(() => parseLead({ ...lead(), ...patch })).toThrow(); });
    it('rejects private/unsupported fields, unsafe URLs and bad coordinate licence', () => { for (const patch of [{ imageUrl: 'copied-image' }, { sellerRoute: 'private' }, { qualifiedSupply: true }, { canonicalUrl: 'https://user:secret@example.invalid/post' }, { coordinateAttribution: { ...lead().coordinateAttribution, url: 'https://wrong.invalid/license' } }])
        expect(() => parseLead({ ...lead(), ...patch })).toThrow(); });
    it('pagination preserves identity and rejects duplicates', () => { expect(parseLeadPage({ enabled: true, items: [lead()], nextCursor: null }).items).toHaveLength(1); expect(() => parseLeadPage({ enabled: true, items: [lead(), lead()], nextCursor: null })).toThrow(); });
    it('inquiry keeps cancel/review states, prohibits private audit payloads and checkout', () => { const room = { id, leadId: id, state: 'CANCEL_REQUESTED', available: false, events: [], transferHash: 'a'.repeat(64), routeVerified: false, delivered: false, delivery: null, checkoutEnabled: false, orderCreated: false, notice: '停止代轉' }; expect(parseLeadRoom(room, id).state).toBe('CANCEL_REQUESTED'); expect(() => parseLeadRoom({ ...room, buyerUserId: 3 }, id)).toThrow(); expect(() => parseLeadRoom({ ...room, orderCreated: true }, id)).toThrow(); });
});

it('accepts only stable item-bound media routes, rejects another item or source',()=>{const mediaId='22222222-2222-4222-8222-222222222222';const photo={id:mediaId,sourceUrl:lead().canonicalUrl,imageUrl:'https://wishlist.example.com/api/source-leads/'+id+'/media/'+mediaId+'/image',thumbnailUrl:'https://wishlist.example.com/api/source-leads/'+id+'/media/'+mediaId+'/thumbnail',alt:'原圖'};expect(parseLead({...lead(),media:[photo]}).media).toHaveLength(1);for(const patch of [{sourceUrl:'https://example.invalid/other'},{imageUrl:'https://scontent.example.com/temporary.jpg'},{thumbnailUrl:'https://wishlist.example.com/api/source-leads/other/media/'+mediaId+'/thumbnail'}])expect(()=>parseLead({...lead(),media:[{...photo,...patch}]})).toThrow();});
