import { getDisplayLocale } from '../utils/localization';
const english={
 '完整資料影響盤點':'Complete data impact preview', '重新盤點':'Refresh impact preview',
 '正在重新盤點本人資料…':'Refreshing your data impact preview…',
 '無法取得完整刪除影響盤點；沒有送出刪除。請重新盤點後再確認。':'The complete deletion impact could not be verified. No deletion was sent. Refresh the preview before confirming.',
 '目前保留上次盤點；尚未確認最新資料，暫時不能送出刪除。':'The last preview is kept. Current data is unverified, so deletion is temporarily disabled.',
 '本人商品檢舉與證據':'Your listing reports and evidence', '本人檢舉收件與安全放棄回執':'Your report submission and abandonment receipts',
 '隨本人刊登移除的檢舉案件':'Reports removed with your listings', '隨本人刊登移除的審核紀錄':'Moderation records removed with your listings',
 '保留但解除本人案件關聯的審核紀錄':'Moderation records retained with your report link removed',
 '願望':'Wishes', '願望建立操作紀錄':'Wish creation operation records', '刊登':'Listings', '商品照片':'Listing photos',
 '需封存聊天室':'Conversations to archive', '本人發送訊息':'Messages you authored', '保留對方自有訊息':'Other participants’ messages to retain',
 '移除面交預約':'Meetup appointments to remove', '其中尚未結束的預約':'Of these, upcoming appointments',
 '解除帳號關聯的購買紀錄':'Purchase records with your account link removed', '解除他人願望代購占用':'Gift claims in others’ wishlists to release',
 '解除他人願望原始關聯':'Original-credit links in others’ wishlists to remove', '商品關注':'Item watches',
 '追蹤關係':'Follow relationships', '封鎖關係':'Block relationships', '意見回報':'Feedback records', '本人分析錯誤紀錄':'Your analysis error records',
 '正在安全讀取原刪除操作…':'Reading the original deletion operation safely…',
 '重試安全讀取刪除恢復資料':'Retry safe deletion recovery reading',
 '刪除 Weesh（Wishlist.ai）帳號與相關資料':'Delete your Weesh (Wishlist.ai) account and related data',
 '不需要重新安裝 App；可在此網頁登入後提出刪除。此操作只處理目前登入的本人帳號。':'You can request deletion here after signing in, without reinstalling the app. This affects only your currently signed-in account.',
 '帳號、本人願望與刊登、本人發送的訊息將依後台刪除流程處理；共享聊天室會封存，對方自有訊息不因你的要求而刪除。':'Your account, wishes, listings and messages you authored follow the server deletion process. Shared conversations are archived; other participants’ own messages remain.',
 '商品照片與舊資產可能由背景工作後續清理；「帳號已刪除」不代表照片或備份已即時清空。若有透過商店購買的訂閱，請另至購買平台確認取消。':'Photos and legacy assets may be cleaned up later. Account deletion does not prove that all photos or backups were immediately erased. Manage any store subscription on the original purchase platform.',
 '更多資訊請閱讀':'Read more in the', '隱私權政策':'Privacy policy','。':'.',
 '原刪除操作的本機紀錄無法安全讀取。為避免重複送出，這個分頁不會建立新操作；請透過網站意見回饋聯絡支援核對。':'The original deletion journal could not be read safely. This page will not create another operation. Contact support to reconcile it.',
 '此瀏覽器保留另一帳號的未確認刪除操作；不會使用目前帳號查詢或建立新刪除，請由原帳號核對。':'This browser retains an unconfirmed deletion for another account. The current account will neither query it nor create a new deletion. Verify with the original account.',
 '原刪除操作的結果仍未確認；不會自動重送刪除。':'The original deletion result is unconfirmed. Deletion will not be resent automatically.',
 '無法取得本人刪除影響盤點；沒有送出刪除。請稍後重新載入。':'Your deletion impact could not be loaded. Nothing was deleted. Reload later.',
 '永久刪除目前本人帳號？願望、刊登與本人訊息將無法復原；照片清理可能需要後續處理。':'Permanently delete your currently signed-in account? Your wishes, listings and authored messages cannot be recovered. Photo cleanup may require further processing.',
 '登入帳號已改變；沒有送出刪除。':'The signed-in account changed or could not be verified. No deletion was sent.',
 '無法安全保存原刪除操作；沒有送出刪除。請保留本頁並重試。':'The original deletion operation could not be saved safely. No deletion was sent. Keep this page and retry.',
 '尚未確認刪除結果；原操作已保存。請查詢結果，或讓伺服器確認放棄後再重試。':'Deletion is unconfirmed; the original operation is saved. Check its result or obtain a server-confirmed abandonment before trying again.',
 '結果仍未確認；不會將登入失效或找不到收據當成成功。':'The result is unconfirmed. An expired sign-in or missing receipt does not prove success.',
 '只放棄尚未成立的原操作？若帳號已刪除，此動作不會復原帳號。':'Abandon only the original operation that has not taken effect? This cannot restore an already deleted account.',
 '伺服器尚未確認放棄，原操作仍保留；不能安全建立新刪除。':'The server has not confirmed abandonment. The original operation remains; a new deletion cannot be created safely.',
 '刪除結果已確認，但瀏覽器恢復資料尚未清理；請先關閉此分頁。':'The deletion result is verified, but the browser journal could not be cleared. Close this tab for now.',
 '已確認的原操作與目前瀏覽器紀錄不同；較新的恢復資料已保留，請重新開啟核對。':'The verified original operation differs from the current browser journal. Newer recovery data was preserved. Reopen to reconcile it.',
 '原刪除操作':'Original deletion operation','操作識別碼：':'Operation ID: ',
 '伺服器已確認帳號刪除。':'The server confirmed account deletion.',
 '商品照片待清理：':'Photos pending cleanup:', '；舊資產待核對／清理：':'; legacy assets pending reconciliation or cleanup:',
 '。這不是實體資產或備份全數清除證明。':'. This does not prove that all physical assets or backups were erased.',
 '正在清理此瀏覽器內本人私密的待確認資料…':'Cleaning your private pending data in this browser…',
 '此瀏覽器的本人待確認資料已清理，已防止較晚完成的舊操作重新寫入。':'Your pending data in this browser was cleared. Late old operations are fenced from writing it again.',
 '帳號刪除已確認，但此瀏覽器的私密資料尚未完成清理；原回執仍保留，請重試。這不是帳號刪除失敗。':'Account deletion is verified, but browser private-data cleanup is incomplete. The original receipt remains. Retry cleanup; account deletion has not failed.',
 '重試本機資料清理':'Retry browser data cleanup', '伺服器已確認放棄原操作；帳號未刪除。':'The server confirmed abandonment of the original operation. The account was not deleted.',
 '尚未取得成功或放棄的伺服器收據。重開瀏覽器只會查詢，不會自動重送刪除。':'No success or abandonment receipt is verified yet. Reopening only checks the result and never automatically resends deletion.',
 '只查詢原操作結果':'Check original result only','安全放棄尚未成立的操作':'Safely abandon an operation that has not taken effect',
 '完成並登出':'Finish and sign out','返回刪除表單':'Return to deletion form',
 '請先以原帳號登入，再在此頁確認刪除影響並提出要求。若忘記密碼，可先使用網頁密碼重設；不需透過 App。':'Sign in to the original account, then review its deletion impact here. If you forgot your password, use web password recovery. The app is not required.',
 '登入後繼續':'Sign in to continue','重設密碼':'Reset password','本人資料影響盤點':'Your deletion impact',
 '唯讀盤點時間：':'Read-only preview captured: ', '；數量可能重疊且會變動，尚未刪除。':'; counts may overlap or change. Nothing has been deleted.',
 '願望清單':'Wishlists','、願望':', wishes','、刊登':', listings','、商品照片':', photos','、本人訊息':', authored messages',
 '尚未取得有效盤點，不可送出刪除。':'A valid impact preview is required before deletion.',
 '目前密碼':'Current password','刪除帳號的目前密碼':'Current password for account deletion',
 '輸入「{phrase}」確認':'Type “{phrase}” to confirm','輸入刪除帳號以確認':'Account deletion confirmation',
 '永久刪除本人帳號':'Permanently delete my account',
}as const;
export function deletionText(key:keyof typeof english,values:Record<string,string|number>={}){return(getDisplayLocale().startsWith('zh')?key:english[key]).replace(/\{(\w+)\}/g,(whole,name:string)=>String(values[name]??whole));}
