import { getDisplayLocale } from '../utils/localization';
import type { ChatRoomRecord } from './chatData';
const english = {
  "自動讀取已暫停；請使用本頁更新按鈕重新核對，成功後才會恢復。登入失效時請先重新登入原帳號。": "Automatic reads are paused. Use this page's update button to verify the latest state; reads resume only after success. If your session expired, first sign in to the same account.",
  "請求暫時受限，已暫停自動讀取；請稍後再試，原內容與待確認操作會保留。": "Requests are temporarily limited. Automatic reads are paused; try again later. Your original content and pending operations remain.",
  "售價未提供": "Price unavailable",
  "免費贈送": "Free",
  "聊天商品照片": "Chat item photo",
  "聊天商品照片未提供或已停止公開": "Chat item photo unavailable or no longer public",
  "照片未提供": "No photo",
  "已停止公開": "No longer public",
  "聊天與面交": "Chat and meetups",
  "登入後與商品買家或賣家聯絡。": "Sign in to contact the item's buyer or seller.",
  "登入": "Sign in",
  "聊天分頁重複，請重新載入收件匣。": "Repeated chat page. Reload the inbox.",
  "登入已失效；請重新登入原帳號，待確認操作會保留。": "Your session expired. Sign in to the same account; pending operations are retained.",
  "暫時無法載入聊天；不代表沒有對話，請重試。": "Chats could not be loaded. This does not mean there are no conversations. Retry.",
  "與買家或賣家聯繫，討論商品細節並約面交。": "Contact buyers or sellers to discuss the item and arrange a meetup.",
  "好友與原有社交功能": "Friends and social features",
  "聊天連結無效，不會使用不明識別碼查詢。": "Invalid chat link. No unknown conversation will be queried.",
  "返回收件匣": "Back to inbox",
  "正在更新聊天…": "Updating chats…",
  "商品聯絡人": "Item contact",
  "與": "With",
  "已移除的帳號": "Removed account",
  "已封存 · 僅供查看": "Archived · Read only",
  "已封鎖 · 歷史仍可查看": "Blocked · History remains readable",
  "商品已停止刊登 · 歷史仍可查看": "Item no longer listed · History remains readable",
  "開始討論這件商品": "Start discussing this item",
  "（台灣時間）": " (Taiwan time)",
  "則未讀": "unread",
  "其他商品尚無聊天。當有買家或賣家聯繫時，對話會顯示在這裡。": "No other item conversations yet. Chats appear here when a buyer or seller contacts you.",
  "載入較早的聊天": "Load older conversations",
  "重新載入收件匣": "Reload inbox",
  "探索商品": "Explore items",
  "原訊息已確認送出。": "The original message is confirmed sent.",
  "原訊息已確認送出，但本機標記尚未清除；請查核原回執，不建立另一則訊息。": "The original message was sent, but its local recovery record remains. Verify its receipt instead of creating another message.",
  "面交狀態暫時無法確認；請開啟預約詳情重試。": "Meetup status could not be verified. Open appointment details and retry.",
  "聊天分頁方向不正確。": "The message page has an invalid direction.",
  "聊天分頁重複。": "Repeated message page.",
  "登入已失效；原訊息保留，請重新登入原帳號後查核。": "Your session expired. The original message is retained. Sign in to the same account to verify it.",
  "無法更新聊天；歷史可能不完整，待確認訊息仍保留，請重試。": "Chats could not be updated. History may be incomplete; pending messages remain. Retry.",
  "尚無原訊息回執；不代表送出失敗或已取消，原內容保留，可明確重試。": "No original message receipt is available. This does not prove failure or cancellation. The original content is retained for explicit retry.",
  "無法查核原訊息回執；沒有重新傳送，原內容仍保留。": "The original message receipt could not be verified. Nothing was resent; the original content remains.",
  "無法安全恢復待確認訊息；請重試恢復，不會丟棄原識別碼重複傳送。": "Pending messages could not be restored safely. Retry recovery; the original identity will not be replaced.",
  "已讀狀態尚未確認；不會假稱已讀，稍後會依實際可見訊息重試。": "Read status is unconfirmed. Only messages actually visible will be marked read on a later attempt.",
  "尚未確認訊息送出；重試會使用相同識別碼與文字，也可只查核原回執。": "Message delivery is unconfirmed. Retrying uses the same identity and text; you can also read the original receipt without resending.",
  "尚未送出訊息。": "The message has not been sent.",
  "封鎖狀態尚未確認；請只更新聊天查核，不會自動反向操作或重送。": "Block status is unconfirmed. Update the chat to check; nothing is automatically reversed or resent.",
  "正在更新…": "Updating…",
  "只更新聊天": "Update chat only",
  "解除封鎖": "Unblock",
  "封鎖對方": "Block contact",
  "聊天商品": "Chat item",
  "正在讀取聊天室…": "Reading conversation…",
  "聊天室已封存，僅可查看保留歷史；對方刪除帳號時其訊息及私密預約會移除。": "This conversation is archived and its retained history is read only. A removed participant's messages and private appointments are deleted.",
  "已封鎖，停止傳送新訊息；歷史仍可查看，原訊息可查核回執。": "Blocked: new messages are paused. History and original message receipts remain readable.",
  "商品已停止刊登；請與對方確認交易狀態。": "This item is no longer listed. Check its status with the contact.",
  "商品聊天訊息紀錄": "Item conversation history",
  "載入較早訊息": "Load older messages",
  "本人訊息": "My message",
  "對方訊息": "Contact's message",
  "還沒有訊息，打聲招呼吧。": "No messages yet. Say hello.",
  "仍有更新的訊息尚未讀完；下一次更新會繼續讀取，不代表最新紀錄已完整。": "Newer messages remain unread by this page. The next update continues loading; the latest history is not yet complete.",
  "聊天面交預約": "Chat meetup appointment",
  "查看或提議面交預約": "View or propose a meetup",
  "面交預約 ·": "Meetup ·",
  "· 第": "· Version ",
  "版": "",
  "時間與地點仍待雙方確認，請在詳情核對後回覆。": "Both parties still need to confirm the time and place. Review the details before replying.",
  "上一則訊息結果尚未確認，原識別碼與文字已保留；不會自動重送或建立重複訊息。": "The previous message is unconfirmed. Its original identity and text are retained; nothing is automatically resent or duplicated.",
  "聊天室已封存，不能重新傳送。": "This conversation is archived; messages cannot be resent.",
  "重試恢復待確認訊息": "Retry pending message recovery",
  "商品聊天訊息（最多2000字元）": "Item message (up to 2000 characters)",
  "輸入訊息，預約前請確認商品狀態": "Enter a message; check the item status before arranging a meetup",
  "明確重試相同訊息": "Retry the same message",
  "傳送訊息": "Send message",
  "只查核原訊息回執": "Read original message receipt only",
  "此瀏覽器無法偵測訊息可見範圍，不會自動標記已讀；可由你明確確認。": "This browser cannot detect visible messages, so it will not mark them read automatically. You can confirm this explicitly.",
  "將目前已載入訊息標記為已讀": "Mark loaded messages as read",
  "無法更新面交預約；不代表尚無預約或已確認，請重試。": "The appointment could not be updated. This does not prove that it is absent or confirmed. Retry.",
  "無法安全恢復待確認預約，請重試恢復；不會重建操作。": "The pending appointment could not be restored safely. Retry recovery; no replacement operation is created.",
  "對方已更新預約，請載入最新版本後重新編輯；沒有送出操作。": "The contact updated the appointment. Load the latest version before editing again; nothing was sent.",
  "後台操作已確認，但本機待確認標記尚未清除；請查核或重試同一操作，暫不建立新操作。": "The server operation is confirmed, but its local recovery record remains. Verify or retry the same operation; new operations are paused.",
  "原待確認操作已安全放棄；這不會取消已成立的預約。": "The original pending operation was safely stopped. This does not cancel an existing appointment.",
  "原操作已先完成，已確認結果；放棄操作沒有取消目前預約。": "The original operation had already completed and is now verified. Stopping it did not cancel the current appointment.",
  "操作已確認；是否雙方同意請查看預約狀態。": "The operation is verified. Check the appointment status to see whether both parties agreed.",
  "對方已更新預約，不能沿用舊版同意；原操作仍保留，請更新並安全放棄後重新核對。": "The contact updated the appointment. Approval of the old version cannot approve new terms. The original operation remains; update, safely stop it, and review again.",
  "時間與任一方其他預約重疊；原操作仍保留，請更新並安全放棄後選擇其他時間。": "The time overlaps another appointment for either party. The original operation remains; update and safely stop it before choosing another time.",
  "尚未確認操作結果；請查核畫面狀態或明確重試原操作，關閉後仍會保留。": "The result is unconfirmed. Check the displayed status or explicitly retry the original operation. Closing retains it.",
  "尚未送出操作。": "No operation has been sent.",
  "面交預約": "Meetup appointment",
  "僅買賣雙方可見。預約不代表付款、交易保障或自動保留商品；請優先選擇安全的公共場所。": "Only the buyer and seller can view this appointment. It does not prove payment, guarantee a trade, or reserve the item automatically. Choose a safe public place.",
  "聊天室已封存，無法新增或調整面交。": "This conversation is archived. Meetups cannot be created or changed.",
  "商品已停止刊登，請先與賣家確認；仍可取消既有預約。": "The item is no longer listed. Check with the seller first; existing appointments can still be cancelled.",
  "已封鎖，不能新增或確認面交；仍可取消既有預約。": "Blocked: new meetups cannot be proposed or confirmed. Existing appointments can still be cancelled.",
  "目前面交預約": "Current meetup appointment",
  "至": "to",
  "雙方私密座標：": "Private coordinates for both parties: ",
  "買家": "Buyer: ",
  "已同意": "agreed",
  "尚未同意": "not yet agreed",
  "· 賣家": "· Seller: ",
  "已回報完成": "reported completion",
  "尚未回報": "not yet reported",
  "上次讀取尚無預約；目前有待確認操作，請更新狀態核對，不能據此認定邀約未成立。": "The last read found no appointment, but an operation is pending. Update the status to check; this does not prove the proposal failed.",
  "尚無面交預約，先與對方討論時間再提出邀約。": "No meetup appointment yet. Discuss a time with the contact before proposing one.",
  "正在讀取面交預約…": "Reading meetup appointment…",
  "重試恢復待確認預約": "Retry pending appointment recovery",
  "待確認面交操作": "Pending meetup operation",
  "有一個尚未確認結果的操作": "An operation has an unconfirmed result",
  "原操作：": "Original operation: ",
  "· 原第": "· Original version ",
  "版。重試沿用相同識別碼、版本與條件，不會自動改為同意新版本。": ". Retrying keeps the same identity, version and terms; it cannot automatically approve a new version.",
  "（台灣時間） ·": " (Taiwan time) ·",
  "明確重試原操作": "Retry original operation",
  "安全放棄待確認操作": "Safely stop pending operation",
  "若原操作已完成，只確認原結果；不會取消已成立預約。只有未完成的操作會被封存。": "If the original operation completed, only its result is verified; the appointment is not cancelled. Only unfinished operations are stopped.",
  "確認安全放棄（不取消現有預約）": "Confirm stopping operation (keep existing appointment)",
  "返回查核": "Back to verification",
  "改期／重新提議": "Reschedule or propose again",
  "提出面交邀約": "Propose meetup",
  "對方已更新預約。原表單不會被自動覆蓋，請重新核對。": "The contact updated the appointment. Your form will not be overwritten automatically. Review again.",
  "載入最新版本後重新編輯": "Load latest version and edit again",
  "面交日期與時間（台灣時間）": "Meetup date and time (Taiwan time)",
  "面交時間長度（分鐘，15至240）": "Duration (minutes, 15–240)",
  "私密面交地點名稱": "Private meetup place",
  "公共場所名稱、出口或集合點": "Public place, exit or meeting point",
  "私密面交緯度（選填）": "Private latitude (optional)",
  "私密面交經度（選填，須與緯度同填）": "Private longitude (optional, requires latitude)",
  "面交備註（選填，最多1000字元）": "Meetup notes (optional, up to 1000 characters)",
  "提出此版本（改期需對方重新同意）": "Propose these terms (changes require new approval)",
  "關閉編輯": "Close editor",
  "提議改期或修改地點": "Propose a new time or place",
  "同意第": "Agree to version ",
  "版時間與地點": "'s time and place",
  "我已完成面交（仍需對方回報）": "I completed the meetup (contact must also report)",
  "取消第": "Cancel version ",
  "版預約": " appointment",
  "只更新預約狀態": "Update appointment status only",
  "聊天資料回應不正確": "The chat response could not be verified.",
  "已封存的商品聊天": "Archived item conversation",
  "請輸入1至2000字訊息，不含無效控制字元": "Enter 1–2000 characters without invalid control characters.",
  "回執與原訊息不符，尚未確認送出。": "The receipt does not match the original message. Delivery remains unconfirmed.",
  "提議中": "Proposed",
  "雙方已確認": "Both parties confirmed",
  "已取消": "Cancelled",
  "雙方已回報完成": "Both parties reported completion",
  "提出邀約": "Propose meetup",
  "改期或修改地點": "Change time or place",
  "同意時間與地點": "Agree to time and place",
  "取消預約": "Cancel appointment",
  "回報面交完成": "Report meetup completion",
  "請選擇有效的台灣面交日期與時間。": "Choose a valid meetup date and time in Taiwan.",
  "面交預約資料不正確": "The appointment response could not be verified.",
  "請填寫有效時間、地點與完整的選填座標": "Enter a valid time, place, and both optional coordinates.",
  "無法安全保存或恢復待確認操作。請重試恢復；不會在未保存時送出。": "The pending operation could not be saved or restored safely. Retry recovery; nothing is sent without saving.",
  "關閉": "Close",
  "操作需要重新查核；請保留內容並重試讀取。": "The operation needs verification. Keep your content and retry reading.",
  "已確認先前第{acknowledged}版操作；目前第{current}版仍需重新核對。": "The original version {acknowledged} operation is verified. Review the current version {current} separately.",
  "{title}，與{name}聊天{unread}": "{title}, chat with {name}{unread}",
  "，{count} 則未讀": ", {count} unread"
} as const;

export function chatText(key: keyof typeof english, values: Record<string, string | number> = {}) {
  return (getDisplayLocale().startsWith('zh') ? key : english[key]).replace(/\{(\w+)\}/g, (whole, name: string) => String(values[name] ?? whole));
}
export function chatMessage(value: string) {
  if (!value) return value;
  if (Object.hasOwn(english, value)) return chatText(value as keyof typeof english);
  const versions = /^已確認先前第(\d+)版操作；目前第(\d+)版仍需重新核對。$/.exec(value);
  if (versions) return chatText('已確認先前第{acknowledged}版操作；目前第{current}版仍需重新核對。', { acknowledged: versions[1], current: versions[2] });
  return chatText('操作需要重新查核；請保留內容並重試讀取。');
}
export const chatTime = (value: string) => new Date(value).toLocaleString(getDisplayLocale().startsWith('zh') ? 'zh-TW' : 'en-US', { timeZone: 'Asia/Taipei', hour12: false });
export const chatRoomTitle = (room: ChatRoomRecord) => room.listingId === null ? chatText('已封存的商品聊天') : room.listing.title;
export const chatRoomPrice = (room: ChatRoomRecord) => room.listing.price === null ? chatText('售價未提供') : room.listing.price === 0 ? chatText('免費贈送') : 'NT$ ' + room.listing.price.toLocaleString(getDisplayLocale().startsWith('zh') ? 'zh-TW' : 'en-US');
