import { describe,it,expect,beforeEach,afterEach,vi } from 'vitest';
import { createHash } from 'node:crypto';
import { IDBFactory,IDBKeyRange } from 'fake-indexeddb';
import { prepareLegacyCreate,legacyCreateReceipt } from './legacyWishCreateWeb';
import { detailOperation } from './legacyDetailWeb';
import { legacyPhotoEnvelope,legacyRemovalEnvelope } from './useLegacyWishPhoto';
import { photoUploadJournal,parsePhotoUploadJournal,photoUploadResult } from './listingPhotoUploadWeb';
import { createWebPendingStore,pendingRequestKey,pendingScope } from './webPendingStore';
const draft={name:'',notes:'合成備註',price:'0',currency:'usd',budget:'25.50',budgetCurrency:'twd',link:''};
const id='11111111-1111-4111-8111-111111111111',media='22222222-2222-4222-8222-222222222222';
beforeEach(()=>vi.stubGlobal('IDBKeyRange',IDBKeyRange));
afterEach(()=>vi.unstubAllGlobals());
describe('legacy create canonical identities and encrypted photo envelopes',()=>{
  it.each([['LINK','合成文字願望',null,'SKIPPED'],['LINK','https://example.com/product',null,'PENDING'],['LINK','http://example.com/product',null,'SKIPPED'],['PHOTO','',media,'PENDING']] as const)('hashes the complete normalized %s request with backend protocol %s',async(kind,input,mediaId,status)=>{const p=await prepareLegacyCreate(kind,1,draft,input,mediaId);expect(p.requestHash).toBe(createHash('sha256').update(JSON.stringify(['legacy-create-v1',kind,1,p.data])).digest('hex'));expect(p.data).toMatchObject({price:'0',currency:'USD',maxPrice:25.5,priceCurrency:'TWD',notes:'合成備註',aiStatus:status,mediaId});expect(p.payload).not.toHaveProperty('link');expect(p.payload.requestHash).toBe(p.requestHash);});
  it('retains a deleted-created receipt and a safe stop without treating an unknown read as no creation',()=>{const op=detailOperation(JSON.stringify({version:1,id:1,kind:'LINK_CREATE',clientRequestId:id,requestHash:'a'.repeat(64),localOperationId:media}));expect(legacyCreateReceipt({kind:'LINK',clientRequestId:id,requestHash:op.requestHash,wishlistId:1,state:'CREATED',resourceId:50,resource:null,deleted:true},op)).toEqual({state:'CREATED',resourceId:50,deleted:true});expect(()=>legacyCreateReceipt({kind:'LINK',clientRequestId:id,requestHash:'b'.repeat(64),wishlistId:1,state:'ABANDONED',resourceId:null,resource:null,deleted:false},op)).toThrow();});
  it('requires an explicit MANUAL_PHOTO caller and keeps batch purpose validation strict',async()=>{const body=await photoUploadJournal(new File(['photo'],'secret-name.jpg',{type:'image/jpeg'}),id,'MANUAL_PHOTO');await expect(parsePhotoUploadJournal(body)).rejects.toThrow();expect((await parsePhotoUploadJournal(body,'MANUAL_PHOTO')).capturePurpose).toBe('MANUAL_PHOTO');const journal=JSON.parse(body),createdAt=new Date().toISOString();expect(await photoUploadResult({receipt:{clientUploadId:id,requestHash:journal.requestHash,state:'ABANDONED',mediaId:null,createdAt},media:null},body,42,'MANUAL_PHOTO')).toMatchObject({state:'ABANDONED'});await expect(photoUploadResult({receipt:{clientUploadId:id,requestHash:journal.requestHash,state:'ABANDONED',mediaId:null,createdAt},media:null},body,42)).rejects.toThrow();});
  it('binds upload/removal to the original list and exact content without persisting names, files or credentials',async()=>{const body=await photoUploadJournal(new File(['private-photo-bytes'],'private-name.jpg',{type:'image/jpeg'}),id,'MANUAL_PHOTO'),outer=JSON.stringify({version:1,listId:1,body}),journal=JSON.parse(body);const removal=JSON.stringify({version:1,mediaId:media,photoBody:JSON.stringify({version:1,clientUploadId:id,digest:journal.sourceHash})}),raw=JSON.stringify({version:1,listId:1,photo:outer,body:removal});expect((await legacyPhotoEnvelope(outer)).listId).toBe(1);expect((await legacyRemovalEnvelope(raw)).photo).toBe(outer);expect(raw).not.toMatch(/private-photo-bytes|private-name|token/);await expect(legacyRemovalEnvelope(JSON.stringify({...JSON.parse(raw),listId:2}))).rejects.toThrow();await expect(legacyPhotoEnvelope(JSON.stringify({...JSON.parse(outer),name:'sensitive'}))).rejects.toThrow();});
  it('actually encrypts both new scopes with account/API isolation, CAS and authoritative account erasure',async()=>{const store=createWebPendingStore('legacy-create-'+crypto.randomUUID(),new IDBFactory()),api='https://example.com/api';for(const feature of ['legacy-wish-photo','legacy-wish-photo-remove']){const key=await pendingRequestKey(api,42,feature),other=await pendingRequestKey(api,43,feature),alternate=await pendingRequestKey('https://another.example/api',42,feature);await store.save(key,'minimal-synthetic-journal');expect(await store.get(other)).toBeNull();expect(await store.get(alternate)).toBeNull();expect(await store.clear(key,'stale-journal')).toBe(false);await expect(store.save(key,'replacement')).rejects.toThrow();expect(await store.get(key)).toBe('minimal-synthetic-journal');}await store.eraseScope(await pendingScope(api,42));for(const feature of ['legacy-wish-photo','legacy-wish-photo-remove']){const key=await pendingRequestKey(api,42,feature);expect(await store.get(key)).toBeNull();await expect(store.save(key,'late')).rejects.toThrow();}});
});
