import { getUserLocale } from '../utils/localization';

const english = {
  "商品服務網址不正確。": "Invalid listing service URL.",
  "我的商品資料不正確，請重新載入。": "Your listing data could not be verified. Reload and try again.",
  "商品分頁未前進，請重新載入。": "Listing pagination did not advance. Reload and try again.",
  "請確認名稱、3000 字內說明及有效售價；在售商品不可清空說明或價格。": "Check the title, description of up to 3,000 characters, and valid TWD price. Published listings require a description and price.",
  "登入已失效，請重新登入。": "Your session expired. Sign in again.",
  "無法取得我的商品，請確認連線後重試。": "Your listings could not be loaded. Check your connection and retry.",
  "商品分頁游標已失效，請重新載入；已載入的商品仍保留。": "The listing cursor is no longer valid. Reload; your loaded listings are retained.",
  "有原商品操作待查核；重開只讀取回執，不會自動重送。": "An original listing operation needs verification. Reopening reads its receipt without resending.",
  "仍無法取得原操作回執；紀錄保留，不會自動重送。": "The original receipt is still unavailable. Its journal is retained without resending.",
  "無法安全恢復商品操作紀錄；請重新載入恢復，未查核前不會送出。": "The listing journal could not be restored safely. Reload to recover it; changes are paused until verification.",
  "原商品操作已確認完成；不會再次套用。": "The original listing operation is confirmed complete. It will not be applied again.",
  "原商品操作未套用；請比較最新資料與您的修改。": "The original listing operation was not applied. Compare the latest data with your changes.",
  "原商品操作已取消；此識別碼不會再套用。": "The original listing operation was safely stopped. This operation ID cannot apply changes.",
  "原商品操作已完成，但本機編輯草稿尚未清理；草稿仍保留，請重開編輯比較。": "The original operation completed, but its local edit draft could not be cleared. Reopen the editor to compare the retained draft.",
  "原操作回執已確認，但目前商品資料仍無法安全核對；紀錄已保留，請只查詢最新狀態。": "The original receipt is confirmed, but the current listing could not be verified. Its journal is retained; read the latest state.",
  "仍無法核對最新商品；原操作不會重送，請稍後只查詢狀態。": "The latest listing could not be verified. The original operation was not resent; retry reading its state later.",
  "無法安全保存原操作；未送出。請重新載入恢復後再試。": "The original operation could not be saved safely. Nothing was sent. Reload to recover and retry.",
  "原操作內容衝突；請先查核回執，勿重送或覆蓋。": "The original operation conflicts. Read its receipt before retrying or making changes.",
  "操作結果尚未確認；紀錄已保留，請先查核回執，勿連續重送。": "The result is unconfirmed. Its journal is retained. Read the original receipt before retrying.",
  "仍未取得原操作回執；紀錄保留，不會自動重送。": "The original receipt is unavailable. Its journal is retained without automatic resending.",
  "已保留您的修改；尚未送出。請逐欄比較後明確儲存，會使用最新版本與新操作識別碼。": "Your changes are retained and have not been sent. Compare each field before saving with the latest version and a new operation ID.",
  "已讀原操作結果並清理此份本機紀錄；沒有重送。": "The original result was acknowledged and this local journal cleared. Nothing was resent.",
  "紀錄已被另一分頁更新或清理；請重新載入恢復，不會清除其他操作。": "Another tab changed or cleared the journal. Reload to recover it; other operations will not be cleared.",
  "移除後不會出現在探索地圖，無法從此頁恢復。": "It will leave the Explore map and cannot be restored from this page.",
  "延長刊登不會自動更新地圖顯示。": "Extending a listing does not renew map display.",
  "這次顯示商品約 2 公里模糊位置一小時？可取消；不顯示使用者即時位置，不會自動續期。": "Display the approximate product location for one hour? You can cancel. This does not show a user's live location and never renews automatically.",
  "停止地圖顯示？商品刊登及聊天仍保留。": "Stop map display? The listing and chat will remain available.",
  "已確認這次地圖顯示，一小時後停止；不會自動續期。": "Map display confirmed for this check-in. It stops after one hour and never renews automatically.",
  "已停止地圖顯示。": "Map display stopped.",
  "地圖顯示尚未確認；請重新載入查看最新期限，不會自動重送。": "Map display is unconfirmed. Reload to check the latest deadline; this will not resend automatically.",
  "地圖顯示至 {time}；不會自動續期。": "Map display until {time}; it never renews automatically.",
  "目前不在地圖顯示；需手動確認這次顯示。": "Currently hidden from the map. Each check-in requires manual confirmation.",
  "手動顯示地圖一小時": "Check in on the map for one hour",
  "地圖顯示": "Map display",
  "確認商品地圖顯示": "Confirm product map display",
  "確認這次顯示一小時": "Confirm this one-hour check-in",
  "確認停止地圖顯示": "Confirm stop map display",
  "取消": "Cancel",
  "原操作顯示期限：{time}": "Original check-in deadline: {time}",
  "原操作已停止地圖顯示。": "The original operation stopped map display.",
  "停止地圖顯示": "Stop map display",
  "價格洽詢": "Ask for price",
  "免費贈送": "Free giveaway",
  "已複製商品分享連結與名稱／價格。": "Listing link, title, and price copied.",
  "無法開啟分享或複製連結，請使用下方商品網址。": "Sharing or copying failed. Use the listing URL below.",
  "在售": "For sale",
  "已保留": "Reserved",
  "草稿": "Drafts",
  "已售出": "Sold",
  "已失效": "Expired",
  "已移除": "Removed",
  "返回我的／設定": "Back to Settings",
  "我的商品": "My listings",
  "刊登好物": "Sell an item",
  "我的商品狀態": "My listing statuses",
  "重新載入商品操作紀錄": "Restore listing journal",
  "原商品操作與最新資料比較": "Compare original operation with latest listing",
  "編輯資訊": "Edit details",
  "延長期限": "Extend expiry",
  "狀態變更": "Status change",
  "未套用，資料有衝突或不符合規則": "Not applied: conflict or invalid changes",
  "已取消": "Stopped",
  "待查核": "Unconfirmed",
  "您的原操作內容（已保存）": "Your original operation (saved)",
  "後台最新商品資料（只讀）": "Latest listing from the server (read only)",
  "未填": "Not provided",
  "未設定": "Not set",
  " · 原操作完成後又有更新": " · Updated again after the original operation",
  "標記保留": "Mark reserved",
  "恢復在售": "Return to sale",
  "標記售出": "Mark sold",
  "移除": "Remove",
  "尚未核對；不會用目前卡片推定原操作成功。": "Not yet verified. The current card does not prove the original operation succeeded.",
  "只查核原操作回執與最新商品": "Read original receipt and latest listing",
  "明確重試同一原操作": "Retry the same original operation",
  "取消原操作…": "Stop original operation…",
  "若已完成會保留真實結果；取消不會刪除商品。": "If already applied, its real result is retained. Stopping will not delete the listing.",
  "確認取消此原操作": "Confirm stopping original operation",
  "返回查核": "Back to verification",
  "已讀結果，清理本機紀錄": "Acknowledge result and clear local journal",
  "保留我的修改，以最新版本重新編輯": "Keep my changes and edit the latest version",
  "無照片": "No photo",
  "售價未填": "Price not provided",
  "二手": "Used",
  "新品": "New",
  "地點未填": "Location not provided",
  "尚未填寫說明": "No description yet",
  "未分類": "Uncategorized",
  "收合詳情": "Hide details",
  "查看詳情": "View details",
  "分享連結": "Share link",
  "商品網址": "Listing URL",
  "此商品已失效；請先延長期限，再編輯或繼續刊登。": "This listing expired. Extend its expiry before editing or continuing publication.",
  "分享連結仍可複製，但其他人只會看到「已停止刊登」。": "You can copy the share link, but visitors will see that publication has stopped.",
  "新的失效日期（台灣時間）": "New expiry date (Taiwan time)",
  "取消延長": "Cancel extension",
  "確認延長": "Confirm extension",
  "載入或確認中…": "Loading or verifying…",
  "載入更多我的商品": "Load more listings",
  "重新載入": "Reload",
  "已恢復本機編輯草稿；尚未更新商品。": "Local edit draft restored. The listing has not been updated.",
  "無法安全讀取商品編輯草稿；原資料保留，請關閉後重試。": "The edit draft could not be read safely. Original data is retained. Close and retry.",
  "正在保存本機草稿；尚未更新商品。": "Saving local draft. The listing has not been updated.",
  "此頁修改尚未保存；後台商品未更改。": "Changes on this page are unsaved. The server listing is unchanged.",
  "草稿未安全保存，可能已被另一分頁更新；此頁修改仍保留，請先複製文字，再關閉後重新開啟比較。": "The draft could not be saved safely; another tab may have changed it. Your text remains here. Copy it before closing and reopening to compare.",
  "本機草稿已保存；尚未更新商品。": "Local draft saved. The listing has not been updated.",
  "草稿已被另一分頁更新，請先複製此頁文字，再重新開啟比較。": "Another tab changed the draft. Copy your text before reopening to compare.",
  "無法安全送出商品修改，草稿保留。": "Listing changes could not be sent safely. The draft is retained.",
  "確認捨棄這份尚未送出的本機編輯草稿？不會更改後台商品。": "Discard this unsent local edit draft? The server listing will not change.",
  "另一分頁已更新草稿；未清除其內容，請保留文字並重新開啟比較。": "Another tab updated the draft. Its contents were not cleared. Keep your text and reopen to compare.",
  "編輯商品資訊": "Edit listing details",
  "尚未送出草稿與最新商品比較": "Compare unsent draft with latest listing",
  "保留草稿，以最新版本繼續編輯": "Keep draft and use latest version",
  "商品名稱": "Listing title",
  "商品說明": "Description",
  "售價（NT$，0 代表免費贈送）": "Price (TWD; 0 means free giveaway)",
  "關閉編輯，保留草稿": "Close editor and keep draft",
  "捨棄本機草稿": "Discard local draft",
  "儲存修改": "Save changes",
  "額外選項": "More options",
  "請先儲存商品資訊，再使用行銷小助手。": "Save listing details before using the marketing assistant.",
  "確認{action}「{title}」？{warning}": "{action} “{title}”? {warning}",
  "請選擇 {minimum} 或之後的有效日期。": "Choose a valid date on or after {minimum}.",
  "確認延長至 {date}？{warning}": "Extend expiry to {date}? {warning}",
  "看看「{title}」｜{price}：{url}": "See “{title}” | {price}: {url}",
  "本頁「{tab}」已載入 {visible} 件；全部狀態共已載入 {total} 件，還有更多。": "{visible} loaded in {tab}; {total} loaded across all statuses. More listings are available.",
  "原商品操作 · ": "Original operation · ",
  "商品：": "Listing: ",
  " · 原版本 ": " · Original version ",
  "已完成版本 {version}": "Applied version {version}",
  "商品名稱：": "Listing title: ",
  "商品說明：": "Description: ",
  "售價（NT$）：": "Price (TWD): ",
  "新的失效日期（台灣時間）：": "New expiry date (Taiwan time): ",
  "動作：": "Action: ",
  "版本：": "Version: ",
  "狀態：": "Status: ",
  "失效日期（台灣時間）：": "Expiry date (Taiwan time): ",
  "這個狀態目前沒有已載入商品": "No listings loaded for this status",
  "；可繼續載入更多。": "; load more to continue.",
  "。": ".",
  "{title}商品縮圖": "{title} listing thumbnail",
  " · 至 {date}": " · Until {date}",
  "分類：": "Category: ",
  " · 建立：": " · Created: ",
  " · 商品編號：": " · Listing ID: ",
  "請先 ": "Please ",
  "登入": "sign in",
  " 再閱覽與管理自己的商品。": " to view and manage your listings.",
  "本機草稿以版本 {base} 編輯；後台已是版本 {latest}。請先比較，不會自動覆蓋。": "The local draft uses version {base}; the server is at version {latest}. Compare first; nothing will be overwritten automatically.",
  "後台商品名稱：": "Server title: ",
  "後台商品說明：": "Server description: ",
  "後台售價（NT$）：": "Server price (TWD): "
} as const;

export function managementEnglish() {
  try { return !getUserLocale().startsWith('zh'); } catch { return true; }
}
export function managementText(key: keyof typeof english, values: Record<string, string | number> = {}) {
  const template = managementEnglish() ? english[key] : key;
  return template.replace(/\{(\w+)\}/g, (whole, name: string) => String(values[name] ?? whole));
}
