import { getUserLocale } from '../utils/localization';

const english = {
  '個人資料': 'Personal profile', '管理你的帳號與偏好設定': 'Manage your account and preferences',
  '重試讀取設定': 'Retry reading settings', '個人資料儲存狀態': 'Profile save status',
  '查核原儲存結果': 'Verify original save result', '重試清理恢復標記': 'Retry recovery journal cleanup',
  '重試同一儲存操作': 'Retry the same save operation', '安全取消原操作': 'Safely stop original operation',
  '尚未套用的原操作將永久停止；若後台已儲存，不會撤回資料。是否繼續？': 'An unapplied original operation will be stopped permanently. Saved server data will not be reversed. Continue?',
  '確認停止原操作': 'Confirm stopping original operation', '保留原操作': 'Keep original operation',
  '重試安全讀取': 'Retry safe reading', '我的功能': 'My features',
  '我的願望': 'My wishes', '拍照與 AI 辨識': 'Photos and AI recognition',
  '我的商品': 'My listings', '閱覽與管理': 'View and manage', '聊天與面交': 'Chat and meetups',
  '訊息與預約': 'Messages and appointments', '刊登好物': 'Sell an item', '連拍或批次上傳': 'Camera or batch upload',
  '個人資料與隱私設定': 'Profile and privacy settings', '大頭照與暱稱': 'Avatar and nicknames',
  '上傳大頭照': 'Upload avatar', '點擊或按 Enter 選擇大頭照': 'Click or press Enter to choose an avatar',
  '大頭照': 'Avatar', '暱稱': 'Nicknames', '大頭照上傳狀態': 'Avatar upload status',
  '查核目前大頭照': 'Read current avatar', '清除本機上傳提醒': 'Clear local upload reminder',
  '僅清除本機提醒，不會取消原請求。原上傳仍可能稍後完成；再次上傳可能覆蓋目前大頭照。是否清除提醒？': 'Only the local reminder is cleared; the original request is not cancelled and may finish later. Another upload may replace the current avatar. Clear the reminder?',
  '確認只清除提醒': 'Confirm clearing reminder only', '保留提醒': 'Keep reminder',
  '重試讀取上傳提醒': 'Retry reading upload reminder', '私人資料與公開權限': 'Private information and public visibility',
  '隱藏真實姓名': 'Hide real name', '公開真實姓名': 'Show real name', '隱藏生日': 'Hide birthday', '公開生日': 'Show birthday',
  '隱藏寄送地址': 'Hide delivery address', '公開寄送地址': 'Show delivery address',
  '聯絡資料與公開權限': 'Contact information and public visibility', '公開': 'Public', '隱藏': 'Hidden',
  '手機{phone} · 信箱{email}': 'Phone {phone} · Email {email}',
  '隱藏手機號碼': 'Hide phone number', '公開手機號碼': 'Show phone number', '隱藏電子信箱': 'Hide email address', '公開電子信箱': 'Show email address',
  '進階功能': 'More features', 'AI 整合・交易紀錄・安裝網頁 App・好友與送禮': 'AI integration, purchases, install Web app, friends and gifts',
  '原願望清單 · 分享與送禮': 'Original wishlists · Sharing and gifts', '好友與社交': 'Friends and social',
  '我的商品檢舉 · 查看處理狀態': 'My listing reports · View status',
  '點一下「分享」按鈕': 'Tap the Share button', '往下捲動並選擇「加入主畫面」': 'Scroll down and tap Add to Home Screen', '點一下「加入」': 'Tap Add',
  'AI 整合': 'AI integration', '🤖 讓 AI 幫你管理願望清單': '🤖 Let AI help manage your wishlists',
  '點擊下方按鈕複製指令，然後貼到 ChatGPT 或 Claude 即可開始！': 'Copy the instructions below, then paste them into ChatGPT or Claude to get started.',
  '✅ 已複製！請貼到 ChatGPT 或 Claude': '✅ Copied. Paste into ChatGPT or Claude.',
  '複製失敗，請重試': 'Copying failed. Retry.', '一鍵複製 AI 指令': 'Copy AI instructions', '查看 API 文件': 'View API documentation',
  '既有願望清單權益': 'Existing wishlist benefits',
  '語言偏好未能保存；目前語言保留，請稍後重試。': 'Your language preference could not be saved. The current language is retained. Retry later.',
  '請先完成保存或保留此頁文字；未保存的修改不會因切換語言而丟失。': 'Finish saving or keep the text on this page first. Language switching is paused while changes remain unsaved.',
  '後台已確認儲存。': 'The server confirmed the save.',
  '原變更已儲存，但資料已被之後的變更取代；請核對目前資料。': 'The original changes were saved, but later changes replaced them. Verify the current data.',
  '資料已被其他操作更新；本次未套用。請核對保留的草稿後再儲存。': 'Another operation updated the data. These changes were not applied. Review your retained draft before saving again.',
  '原操作已安全取消，不會再套用；未儲存的草稿仍保留在本頁。': 'The original operation was safely stopped and cannot apply. Unsent drafts remain on this page.',
  '已確認原操作；另一個待確認操作仍存在，請查核後再編輯。': 'The original operation is verified. Another unconfirmed operation remains; verify it before editing.',
  '後台原操作已確認，但本機恢復標記尚未清理；只需重試清理，不要重送。': 'The original server result is verified, but its local recovery journal needs cleanup. Retry cleanup only; do not resend.',
  '原儲存結果尚未確認；重開只查核，不會自動重送。': 'The original save is unconfirmed. Reopening only verifies it without resending.',
  '無法安全讀取帳號資料或恢復標記，暫停儲存。請重試讀取，不代表資料為空。': 'Account data or its recovery journal could not be read safely. Saving is paused. Retry reading; this does not mean your data is empty.',
  '正在保存與確認…': 'Saving and verifying…', '資料沒有變更。': 'No changes to save.',
  '尚未確認儲存結果；請查核原回執，或明確重試同一操作。': 'The save is unconfirmed. Verify the original receipt or explicitly retry the same operation.',
  '無法安全保存或恢復待確認操作。請重試恢復；不會在未保存時送出。': 'The pending operation could not be saved or restored safely. Retry recovery; nothing is sent without saving.',
  '無法保存；尚未送出。請先保留文字，再重試安全讀取。': 'Saving failed; nothing was sent. Keep your text, then retry safe reading.',
  '原儲存結果仍未確認；不會改用新操作，也不會自動重送。': 'The original save is still unconfirmed. No new operation or automatic resend will be used.',
  '帳號資料或儲存回執不正確，請重新查核': 'The account data or save receipt could not be verified. Recheck it.',
  '最多5個暱稱，每個50字內': 'Use up to 5 nicknames, each no longer than 50 characters.',
  '生日須為有效日期，且不可晚於今天': 'Use a valid birthday that is not later than today.', '請輸入有效的電子信箱': 'Enter a valid email address.',
  '{field}超過{limit}字': '{field} exceeds {limit} characters.', '地址': 'Address', '姓名': 'Name', '信箱': 'Email',
  '上次大頭照上傳結果尚未確認。重開不會再次上傳；請查核目前大頭照。': 'The previous avatar upload is unconfirmed. Reopening will not upload again. Read the current avatar.',
  '無法安全讀取大頭照恢復提醒，暫停上傳。請重試讀取。': 'The avatar recovery reminder could not be read safely. Uploading is paused. Retry reading.',
  '請選擇10MB內的圖片。': 'Choose an image of up to 10 MB.', '正在上傳並確認大頭照…': 'Uploading and verifying avatar…',
  '後台已回覆大頭照上傳成功。': 'The server acknowledged the avatar upload.',
  '上傳已回覆，但本機提醒仍存在；請查核目前大頭照後清理。': 'The upload was acknowledged, but a local reminder remains. Read the current avatar before cleanup.',
  '上傳已回覆成功，但本機提醒未清理；請查核目前大頭照後清理。': 'The upload was acknowledged, but its local reminder was not cleared. Read the current avatar before cleanup.',
  '大頭照上傳結果尚未確認；後台可能已保存。請查核目前大頭照，不會自動重送。': 'The avatar upload is unconfirmed; the server may have saved it. Read the current avatar. Nothing is resent automatically.',
  '無法保存大頭照恢復提醒；尚未上傳。請重試讀取。': 'The avatar recovery reminder could not be saved. Nothing was uploaded. Retry reading.',
  '已讀取目前大頭照。此查核無法證明原上傳是否完成；原請求仍可能稍後完成。': 'The current avatar was read. This does not prove the original upload completed; that request may still finish later.',
  '無法查核目前大頭照；上傳結果仍未知，請重試查核。': 'The current avatar could not be read. The upload result is still unknown. Retry reading.',
  '另一份上傳提醒仍存在；請重新查核。': 'Another upload reminder remains. Recheck it.',
  '已清除本機提醒。這不會取消原請求或撤回後台大頭照。': 'The local reminder was cleared. This does not cancel the original request or reverse the server avatar.',
  '無法清理本機提醒；不會再次上傳。請重試清理。': 'The local reminder could not be cleared. Nothing will be uploaded again. Retry cleanup.',
  '贊助與升級': 'Support and upgrades', '購買與訂閱操作暫停': 'Purchases and subscriptions are paused', '贊助服務': 'Support the service',
  '目前未開放收款，不會導向付款頁。': 'Payments are unavailable. No payment page will open.',
  '商店付款與後端驗單尚未開放；既有權益不受影響。': 'Store payments and server receipt verification are unavailable. Existing benefits remain unchanged.',
  '尊榮版訂閱 · NT$90／月': 'Premium subscription · TWD 90/month',
  '既有尊榮會員；請於原付款平台管理訂閱。': 'Existing premium member. Manage your subscription on the original payment platform.',
  '每月 100 次行銷額度；購買尚未開放。': '100 monthly marketing uses; purchases are unavailable.', '會員狀態暫時無法確認。': 'Membership status is temporarily unverified.',
  '若有持續扣款，請由原付款平台管理；未驗證的商店交易不會開通權益。': 'Manage recurring charges on the original payment platform. Unverified store transactions do not unlock benefits.',
  '行銷小助手加值 · US$1／10 次': 'Marketing credits · USD 1/10 uses', '次數不限期；購買尚未開放。': 'Credits do not expire; purchases are unavailable.',
  '永久加值剩餘：{balance}': 'Permanent credits remaining: {balance}', '{count} 次': '{count} uses', '暫時無法核對': 'Temporarily unverified',
  '本月免費次數已用完': 'Free monthly uses are exhausted', '權益讀取失敗；不會以舊資料或零次代替。': 'Benefits could not be read. Old data or a zero balance will not be substituted.',
  '重新核對權益': 'Recheck benefits',
  '帳號安全': 'Account security', '密碼・登入裝置・登出・刪除帳號': 'Password, signed-in devices, sign out and account deletion',
  '請輸入目前密碼以確認操作。密碼不會儲存在瀏覽器，也不會自動重送。': 'Enter your current password to confirm. Passwords are not stored in the browser or resent automatically.',
  '目前密碼': 'Current password', '新密碼': 'New password', '再次輸入新密碼': 'Confirm new password',
  '新密碼 8–72 字元，包含英文字母與數字；符號限 @$!%*?&。': 'Use 8–72 characters, including letters and numbers. Allowed symbols: @$!%*?&.',
  '確認中…': 'Verifying…', '更新密碼並重新登入': 'Update password and sign in again', '撤銷所有裝置登入': 'Revoke all device sessions',
  '登出此裝置': 'Sign out on this device', '刪除本人帳號與資料': 'Delete my account and data',
  '確認更新密碼？所有裝置都需重新登入，個人 API key 將失效。管理與上架簽章不受影響。': 'Update password? All devices must sign in again and your personal API key will be revoked. Administration and release signing are unchanged.',
  '撤銷所有裝置登入？包含此裝置，所有裝置都需重新登入。個人 API key、管理與上架簽章不變。': 'Revoke all device sessions, including this device? All devices must sign in again. Your personal API key, administration and release signing are unchanged.',
  '請輸入有效的目前密碼。': 'Enter a valid current password.', '兩次新密碼不一致。': 'The new passwords do not match.',
  '新密碼需為 8–72 個字元，包含英文字母與數字；符號限 @$!%*?&。': 'The new password must contain 8–72 characters, including letters and numbers. Allowed symbols: @$!%*?&.',
  '目前密碼不正確，尚未確認任何變更。': 'The current password is incorrect. No changes are confirmed.', '帳號操作過於頻繁，請稍後重試。': 'Too many account operations. Retry later.',
  '無法確認帳號操作，請確認網路後再試；不會自動重送。': 'The account operation could not be verified. Check your connection and retry; nothing is resent automatically.',
  '請檢查輸入。': 'Check your input.',
} as const;

export function settingsChinese() { try { return getUserLocale().startsWith('zh'); } catch { return false; } }
export function settingsText(key: keyof typeof english, values: Record<string,string|number> = {}) {
  return (settingsChinese()?key:english[key]).replace(/\{(\w+)\}/g,(whole,name:string)=>String(values[name]??whole));
}
export function settingsMessage(value:string) {
  if(!value||settingsChinese())return value;
  if(Object.hasOwn(english,value))return english[value as keyof typeof english];
  const length=/^(地址|姓名|信箱|暱稱)超過(100|254|500)字$/.exec(value);
  if(length)return settingsText('{field}超過{limit}字',{field:settingsText(length[1] as '地址'|'姓名'|'信箱'|'暱稱'),limit:length[2]});
  return 'The operation needs verification. Keep your changes and retry reading.';
}
