import { getDisplayLocale } from '../utils/localization';
const copy = {
 approximateLocation: ['概略位置，非取貨點；實際所在地與取貨方式仍待原賣家確認。','Approximate location, not a pickup point. Confirm the actual location and pickup options with the original seller.'],
 title: ['Wishlist AI 聊聊','Wishlist AI chat'], back: ['返回商品','Back to item'], update: ['更新','Refresh'], price: ['售價待詢問','Ask about price'], item: ['商品ID：','Item ID: '], external: ['外部來源','External source'], original: ['查看原始來源','View original source'],
 route: ['原賣家收訊路由待核實；貼文連結不能直接當作私訊收件人。','The original seller contact route needs verification. A post link is not a private-message recipient.'],
 intro: ['Wishlist AI 協助按本商品來源代問，不是原賣家。現貨、價格與交易條件尚待確認，不會下訂或付款。','Wishlist AI helps ask about this source item. Stock, price and transaction terms still need confirmation. No order or payment is created.'],
 review: ['此詢問需要人工核查或正在撤回；已保存的外送回執不代表可以繼續轉交。','This inquiry needs human review or withdrawal is in progress. Saved delivery evidence does not authorize further forwarding.'], cancelled: ['後續代問已取消。','Further inquiries have been cancelled.'],
 unavailable: ['來源商品已失效或變更，後續代問已停止；保留原詢問供核查。','The source item is unavailable or has changed. Further inquiries have stopped; the original inquiry remains available for review.'], waiting: ['已接至 Wishlist AI 收件；','Received by Wishlist AI; '], notSent: ['尚未送給賣家','Not sent to the seller'], delivered: ['已人工轉交','Forwarded by a human'], evidence: ['已保存外送回執，後續待核查','Delivery evidence saved; further review required'],
 deliveredNotice: ['已記錄代轉回執，等待原賣家回覆；不是成交。','Forwarding evidence recorded. Awaiting the original seller’s reply; no transaction completed.'], compose: ['請輸入商品問題，送出即接至 Wishlist AI 代問收件。','Enter your item question. Send submits it to Wishlist AI for inquiry handling.'], empty: ['輸入你想確認的商品問題；送出後由 Wishlist AI 處理，不需要你另外尋找原賣家。','Enter what you want to confirm about the item. Wishlist AI will handle your submitted inquiry.'], receipt: ['詢問編號：','Inquiry ID: '], seller: ['原賣家回覆 · Wishlist AI 代轉：','Original seller reply · forwarded by Wishlist AI: '], consentEvent: ['已同意代問','Consent recorded'], cancelEvent: ['已取消','Withdrawn'],
 login: ['登入後聯絡賣家','Sign in to contact the seller'], read: ['讀取已存詢問','Read saved inquiry'], purchase: ['我想購買，先代問現貨與條件','Ask about stock and purchase terms'], purchaseDraft: ['我有購買意願。請先確認是否仍在售、價格與數量、實際所在地、取貨方式及交易條件。','I am interested in buying. Please confirm availability, price, quantity, actual location, pickup options and transaction terms.'], question: ['詢問內容','Question'],
 consent: ['按送出即同意 Wishlist AI 按此商品來源代轉本對話問題給核實的原賣家，不附加帳號聯絡資料；不下訂或付款。','Sending authorizes Wishlist AI to forward this item’s questions to the verified original seller, without your account contact details. No order or payment is created.'], send: ['送出並委託聯絡賣家','Send and ask Wishlist AI to contact the seller'], consentButton: ['同意只轉交上列問題給核實的原賣家','Consent to forward only the questions above to the verified original seller'], cancel: ['撤回委託','Withdraw inquiry'],
 pending: ['原操作已保存，結果仍待確認；可讀取回執或明確重新送出原操作。','The original operation is saved and its result is unconfirmed. Read its receipt or explicitly retry the original operation.'], legacy: ['舊版只保存了操作編號；可讀取回執或撤回，無法還原原問題重新送出。','The previous version saved only an operation ID. Read its receipt or withdraw; the original question cannot be reconstructed for retry.'], retry: ['重新送出原操作','Retry original operation'], savedQuestion: ['已保存的原問題','Saved original question'], restore: ['重試恢復已存操作','Retry restoring saved operation'],
 storage: ['無法安全讀取或更新已存操作。請先重試恢復，再送出；原紀錄仍保留。','The saved operation could not be safely read or updated. Retry restoring it before sending. The original record is retained.'], failure: ['操作結果仍待確認，請讀取最新收件回執；不代表已送給賣家。','The result is unconfirmed. Read the latest inquiry receipt; this does not mean it was sent to the seller.'], auth: ['登入狀態需要重新確認。原操作仍保留；登入後請讀取回執。','Sign-in needs to be verified again. The original operation is retained; sign in and read its receipt.'], limited: ['請求暫時受限，原操作仍保留；等待後請讀取回執。','Requests are temporarily limited. The original operation is retained. Read its receipt after the wait.'], wait: ['{seconds} 秒後可再試。','Try again in {seconds}s.'], changed: ['問題內容已更新，請重新閱讀後再次確認同意','The questions have changed. Read them again before confirming consent.'], noRoom: ['尚無相符的已存詢問，請重新讀取後繼續。','No matching saved inquiry is available. Read again before continuing.'], stopped: ['撤回已確認，先前未確認的操作不會再重送。','Withdrawal is confirmed. The earlier unresolved operation will not be retried.'],
} satisfies Record<string, [string, string]>;
export function sourceContactText(key: keyof typeof copy, values: Record<string, string | number> = {}) {
 return copy[key][getDisplayLocale().startsWith('zh') ? 0 : 1].replace(/\{([a-zA-Z]+)\}/g, (match, field: string) => values[field] === undefined ? match : String(values[field]));
}
