import { getDisplayLocale } from '../utils/localization';
import { WishManagementError, type ManagedWish } from './wishManagement';
import { PendingStoreError } from './webPendingStore';
const en = {
  "我的願望": "My wishes",
  "登入後使用與 APP 相同的照片辨識與願望資料。": "Sign in to use the same photo recognition and wish data as the app.",
  "登入": "Sign in",
  " 商品圖片": " product image",
  " 圖片載入失敗": " image could not be loaded",
  " 尚未提供圖片": " has no image",
  "圖片未載入": "Image unavailable",
  "尚無圖片": "No image",
  "願望讀取失敗，不代表沒有資料。請重新載入核對。": "Wishes could not be read. This does not mean there is no data. Retry the read.",
  "原建立資料已刪除，不會重新建立替代品。": "The original created record was deleted. No replacement will be created.",
  "後台已確認建立；AI 狀態以最新資料為準。": "Creation is confirmed. Read the current data for the latest AI status.",
  "建立已確認，但本機恢復標記未清理；只重試清理，不會再送出建立。": "Creation is confirmed, but its local recovery marker remains. Retry only local cleanup, without resending creation.",
  "建立已確認，但清單讀取失敗，請重新載入查看。": "Creation is confirmed, but the lists could not be read. Retry the read.",
  "後台已移除照片引用，實體檔案仍待清理；不會重建原照片。": "The photo reference was removed. Physical files still await cleanup; the original photo will not be recreated.",
  "後台已確認照片移除與實體檔案清理。": "Photo removal and physical file cleanup are confirmed.",
  "照片移除已確認，但本機標記未清理；只重試本機清理，不會重新移除或重傳。": "Photo removal is confirmed, but its local marker remains. Retry only local cleanup, without removing or uploading again.",
  "原照片移除仍待確認；查不到照片不等於已移除，只查核原回執。": "The original photo removal is unconfirmed. A missing photo is not proof of removal. Read the original receipt.",
  "有待確認照片；先查核或選回原照片明確重試，不會自動上傳。": "A photo is unconfirmed. Check it, or select the same photo for an explicit retry. Nothing uploads automatically.",
  "尚未查到原建立回執；不代表未成立，只有明確重試才會送出原內容。": "The original creation receipt is unavailable. This does not prove creation failed. Only an explicit retry resends the original content.",
  "無法安全恢復願望或讀取資料，請重試；不會在未確認時建立新願望。": "Safe recovery or data reading is unavailable. Retry recovery; no new wish is created while unconfirmed.",
  "後台已確認願望資料修改。": "Wish changes are confirmed.",
  "尚未確認保存；請先查核原回執，不會自動另建。": "Saving is unconfirmed. Check the original receipt; no replacement is created automatically.",
  "原建立仍待確認，識別碼與內容已保留；不會自行重建或丟棄。": "The original creation is unconfirmed. Its identity and content are retained, without automatic recreation or discard.",
  "照片已上傳，儲存願望後才會進入 AI 辨識排隊。": "The photo is uploaded. Save the wish to queue AI recognition.",
  "照片上傳尚未確認；先查核，不會自動換新識別碼。": "Photo upload is unconfirmed. Check the original upload; no new identity is substituted automatically.",
  "已查到原照片。": "The original photo was found.",
  "照片仍待確認；若需要重送，請選回同一照片後明確重試。": "The photo is unconfirmed. Select the same photo before an explicit upload retry.",
  "原照片移除或本機清理尚未確認；請查核原回執，不會假稱成功或自動重傳。": "Original photo removal or local cleanup is unconfirmed. Check the original receipt; no success is assumed and no upload is resent automatically.",
  "原照片移除仍待確認；識別碼與內容已保留，不會自動重送或丟棄。": "The original photo removal is unconfirmed. Its identity and content are retained without automatic resend or discard.",
  "後台已確認更新。": "The update is confirmed.",
  "更新結果尚未確認，請重新讀取核對；不會自動重送或顯示假成功。": "The update is unconfirmed. Read current data to check it; nothing is resent automatically and success is not assumed.",
  "原清單目前無法查看，請回清單核對；此讀取不是操作回執。": "The original list is currently unavailable. Check your lists; this read is not an operation receipt.",
  "仍無法取得最新資料，更新操作繼續暫停。": "Current data remains unavailable. Updates stay paused.",
  "正在處理願望…": "Processing wishes…",
  "只核對最新更新狀態": "Read current update state only",
  "重試安全恢復": "Retry safe recovery",
  "原建立已確認；只需要清理本機標記。": "Original creation is confirmed. Only local marker cleanup remains.",
  "有原建立待確認，新建立暫停；重新開啟只查核，不會自動送出。": "An original creation is unconfirmed. New creation is paused. Reopening checks only and never resends automatically.",
  "只重試本機清理": "Retry local cleanup only",
  "只查核原建立回執": "Read original creation receipt only",
  "明確重試相同建立": "Explicitly retry the same creation",
  "照片移除已確認；只需要清理本機標記。": "Photo removal is confirmed. Only local marker cleanup remains.",
  "原照片移除待確認；新上傳與新建立暫停，重新開啟只查核，不會自動重送。": "Original photo removal is unconfirmed. New uploads and creation are paused. Reopening checks only, without automatic resend.",
  "只重試照片本機清理": "Retry local photo cleanup only",
  "只查核原照片移除回執": "Read original photo removal receipt only",
  "明確重試原照片移除": "Explicitly retry original photo removal",
  "確定移除這張未使用照片？無法復原；後台確認後才會清理本機標記，實體檔案依後台流程清理。": "Remove this unused photo permanently? Its local marker is cleared only after confirmation. Physical files follow the server cleanup process.",
  "確認移除未使用照片": "Confirm unused photo removal",
  "保留這張照片": "Keep this photo",
  "照片、AI 狀態與最高預算與 APP 共用。AI 價格僅供參考，請自行核對。": "Photos, AI status and maximum budgets use the same data as the app. AI prices are estimates; check them yourself.",
  "原有清單分享、送禮與社交功能": "Original list sharing, gifts and social features",
  "返回清單": "Back to lists",
  "編輯清單與公開設定": "Edit list and visibility",
  "分享／送禮與標籤": "Sharing, gifts and wish details",
  "公開清單：未隱藏願望與備註可供他人查看": "Public list: other people can view wishes and notes that are not hidden",
  "私人清單：只有自己可查看": "Private list: visible only to you",
  "新增願望 · 拍照／上傳／手動": "Add wish · camera, upload or manual",
  "這個清單還沒有願望。": "This list has no wishes yet.",
  "AI 參考價格": "AI reference price",
  "幣別未確認": "Currency unconfirmed",
  "未設定預算": "No budget set",
  "最高預算 {currency} {amount}": "Maximum budget {currency} {amount}",
  " · 已隱藏": " · Hidden",
  " · 已完成": " · Completed",
  "詳細資訊與備註": "Details and notes",
  "參考商品連結": "Reference product link",
  "參考商品連結無法安全開啟": "The reference product link cannot be opened safely.",
  "AI 參考商品": "AI reference product",
  "編輯願望": "Edit wish",
  "取消隱藏": "Unhide wish",
  "隱藏願望": "Hide wish",
  "取消完成": "Undo completion",
  "標記完成": "Mark complete",
  "查附近符合商品": "Find nearby matching items",
  "刪除願望": "Delete wish",
  "載入更多願望": "Load more wishes",
  "重新讀取願望": "Read wishes again",
  "刪除整個清單": "Delete entire list",
  "建立願望清單": "Create wishlist",
  "重新讀取清單": "Read lists again",
  "搜尋已載入清單": "Search loaded lists",
  "清單排序": "List order",
  "最新建立": "Newest first",
  "最早建立": "Oldest first",
  "名稱": "Name",
  "還有未載入清單，搜尋只涵蓋目前已載入內容。": "More lists remain unloaded. Search covers only the currently loaded lists.",
  "尚無願望清單，先建立一份記下想找的好物。": "No wishlists yet. Create one to record things you want.",
  "公開": "Public",
  "私人": "Private",
  "{visibility} · {count} 個願望 · 每份上限 {max}": "{visibility} · {count} wishes · Limit {max} per list",
  "查看「{title}」": "View “{title}”",
  "載入更多清單": "Load more lists",
  "願望清單": "Wishlist",
  "新增願望": "Add wish",
  "清單名稱": "List title",
  "清單說明（選填）": "List description · optional",
  "公開清單（預設私人；未隱藏願望與備註可供他人查看）": "Public list · private by default; other people can view wishes and notes that are not hidden",
  "快捷選用 · 照片交給 AI": "Optional · Let AI recognize a photo",
  "單張照片或圖片網址擇一；儲存願望後進入排隊。": "Choose one photo or image URL. Save the wish to enter the queue.",
  "選取的願望照片": "Selected wish photo",
  "照片移除待確認": "Photo removal unconfirmed",
  "原照片已上傳": "Original photo uploaded",
  "照片仍待確認": "Photo unconfirmed",
  "選回原照片明確重試": "Select the original photo for an explicit retry",
  "從相簿選擇願望照片": "Choose a wish photo from the library",
  "拍攝願望照片": "Take a wish photo",
  "只查核原照片": "Check original photo only",
  "明確重試原照片上傳": "Explicitly retry original photo upload",
  "移除未使用照片": "Remove unused photo",
  "願望照片檔案": "Wish photo file",
  "拍攝願望照片檔案": "Wish camera photo file",
  "後台會去除位置資訊並產生縮圖；知道照片網址的人仍可能查看照片，請勿上傳個資。": "The server removes location metadata and creates a thumbnail. People who know the photo URL may still view it; avoid uploading personal information.",
  "AI 商品圖片網址（HTTPS）": "AI product image URL · HTTPS",
  "願望名稱（有照片可留空）": "Wish name · optional with a photo",
  "願望名稱（必填）": "Wish name · required",
  "商品圖片網址（唯讀）": "Saved product image URL · read-only",
  "最高預算（選填）": "Maximum budget · optional",
  "預算幣別": "Budget currency",
  "備註（公開清單會顯示）": "Notes · shown on public lists",
  "參考商品連結（選填）": "Reference product link · optional",
  "儲存後開始 AI 辨識": "Save and queue AI recognition",
  "儲存願望資料": "Save wish data",
  "稍後處理（保留待確認操作）": "Handle later · keep unconfirmed work",
  "確認刪除願望資料": "Confirm wish data deletion",
  "確定刪除「{title}」{children}？無法復原；照片將依後台流程清理。": "Permanently delete “{title}”{children}? This cannot be undone. Photos follow the server cleanup process.",
  "與其中所有願望": " and every wish in it",
  "確認永久刪除": "Confirm permanent deletion",
  "關閉": "Close",
  "AI 排隊中": "AI queued",
  "AI 辨識中": "AI recognizing",
  "AI 辨識完成": "AI recognition complete",
  "AI 辨識失敗，請核對圖片後重建": "AI recognition failed. Check the image before creating a replacement wish.",
  "未啟用 AI 辨識": "AI recognition not enabled",
  "願望資料不正確": "Wish data could not be verified.",
  "回覆與送出的願望欄位不一致，尚未確認更新": "Returned wish fields do not match the submitted fields. The update is unconfirmed.",
  "請先查核照片上傳，或完成照片移除標記清理": "Check the photo upload or finish cleaning its removal marker first.",
  "照片已用於另一筆商品或願望，請查核原資料，不會重複附加": "The photo is attached to another item or wish. Check the original record; it will not be attached twice.",
  "照片已被使用，不能當未使用照片移除": "This photo is already in use and cannot be removed as an unused photo.",
  "請填寫200字內名稱與1000字內備註": "Use a name up to 200 characters and notes up to 1000 characters.",
  "請填寫有效的商品連結": "Enter a valid product link.",
  "連結只能使用無帳密的http(s)網址": "Use an HTTP or HTTPS link without embedded credentials.",
  "請填寫有效的公開圖片網址": "Enter a valid public image URL.",
  "AI 圖片必須是公開 HTTPS 圖片網址": "AI images require a public HTTPS image URL.",
  "請選擇照片或圖片網址其中一種": "Choose either a photo or an image URL.",
  "預算須為非負金額，最多兩位小數": "Use a non-negative budget with at most two decimal places.",
  "請填寫支援的幣別，例如TWD／USD／JPY": "Use a supported currency, such as TWD, USD or JPY.",
  "無法安全恢復上次建立；不會丟棄識別碼重新建立": "The original creation cannot be recovered safely. Its identity will not be discarded to create a replacement.",
  "清單名稱須為200字內，說明1000字內": "Use a list title up to 200 characters and a description up to 1000 characters.",
  "建立回執不吻合": "The creation receipt does not match the original operation.",
  "已離開此帳號，不會送出": "This account was left. Nothing will be sent.",
  "照片回應不正確": "The photo response could not be verified.",
  "照片恢復紀錄損壞": "The photo recovery record could not be verified.",
  "照片不可為空": "The photo file must not be empty.",
  "請選回原本同一張照片；不會用不同照片重送原識別碼": "Select the same original photo. A different photo cannot reuse the original upload identity.",
  "已離開此帳號，不會上傳": "This account was left. No photo will be uploaded.",
  "照片移除恢復紀錄損壞": "The photo removal recovery record could not be verified.",
  "照片移除回執不吻合": "The photo removal receipt does not match the original operation.",
  "已離開此帳號，不會移除照片": "This account was left. No photo will be removed.",
  "無法安全保存或恢復待確認操作。請重試恢復；不會在未保存時送出。": "Unconfirmed work cannot be saved or recovered safely. Retry recovery; nothing is sent without saving first."
} as const;
export type WishPageCopy = keyof typeof en;
export function wishPageText(key: WishPageCopy, values: Record<string,string|number> = {}) {
  const zh = getDisplayLocale().startsWith('zh');
  const copy = zh ? key === '分享／送禮與標籤' ? '分享／送禮與願望詳情' : key : en[key];
  return copy.replace(/\{(\w+)\}/g, (match, field) => Object.hasOwn(values,field) ? String(values[field]) : match);
}
export function wishDisplayError(error: unknown, fallback: WishPageCopy) {
  if ((error instanceof WishManagementError || error instanceof PendingStoreError) && Object.hasOwn(en,error.message)) return wishPageText(error.message as WishPageCopy);
  return wishPageText(fallback);
}
export function wishStatusText(status: ManagedWish['aiStatus']) {
  const keys = { PENDING:'AI 排隊中', PROCESSING:'AI 辨識中', COMPLETED:'AI 辨識完成', FAILED:'AI 辨識失敗，請核對圖片後重建', SKIPPED:'未啟用 AI 辨識' } as const;
  return wishPageText(keys[status]);
}
