
export const API_ERROR_CODES = {
    // Auth & Validation (400/401/403)
    MISSING_FIELDS: 'MISSING_FIELDS',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    USER_EXISTS: 'USER_EXISTS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_OTP: 'INVALID_OTP',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
    ACCESS_DENIED: 'ACCESS_DENIED',
    INVALID_INPUT: 'INVALID_INPUT',

    // Resource (404)
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    WISHLIST_NOT_FOUND: 'WISHLIST_NOT_FOUND',
    ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',

    // Server (500)
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    AI_PROCESSING_FAILED: 'AI_PROCESSING_FAILED',
    FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
} as const;

export type ApiErrorCode = typeof API_ERROR_CODES[keyof typeof API_ERROR_CODES];
