"""Reproduce the fixed Web composition. Requires Pillow; never edits inputs."""
from pathlib import Path
from PIL import Image
import hashlib
import json

client = Path(__file__).resolve().parents[1]
inputs = client / 'icon-source'
recipe = json.loads((inputs / 'recipe.json').read_text())
for key in ('original', 'H'):
    source = inputs / recipe[key]['path']
    assert hashlib.sha256(source.read_bytes()).hexdigest() == recipe[key]['sha256']
assert recipe['originalTransform'] == 'identity'
original = Image.open(inputs / recipe['original']['path']).convert('RGBA')
assert list(original.size) == recipe['canvas']
placement = recipe['HPlacement']
assert placement['colorOrOpacityAdjustment'] is False
layer = Image.open(inputs / recipe['H']['path']).convert('RGBA').resize(tuple(placement['size']), Image.Resampling.LANCZOS)
result = original.copy()
result.alpha_composite(layer, tuple(placement['position']))
for name, output in recipe['outputs'].items():
    image = result if output['size'] == original.width else result.resize((output['size'], output['size']), Image.Resampling.LANCZOS)
    target = client / 'public' / name
    image.save(target)
    assert hashlib.sha256(target.read_bytes()).hexdigest() == output['sha256'], f'Unexpected generated bytes: {name}'
print('All four Web icons reproduce the recorded identity composition.')
