import { describe, it, expect, vi, afterEach } from 'vitest';
import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import SourceLeadMapPage, { mapPoint, currentLead } from './SourceLeadMapPage';
const dates=()=>({checkedAt:new Date().toISOString(),postedEarliestAt:new Date(Date.now()-86400000).toISOString(),postedLatestAt:new Date(Date.now()-86400000).toISOString()});
const auth=vi.hoisted(()=>({token:null as string|null,user:{id:1}}));
vi.mock('../context/AuthContext',()=>({useAuth:()=>auth}));
afterEach(()=>{auth.token=null;sessionStorage.clear();cleanup();vi.unstubAllGlobals()});
describe('source lead public map',()=>{
 it('rejects expired, future, or missing original dates and stale checks',()=>{const row:any={...dates()};expect(currentLead(row)).toBe(true);expect(currentLead({...row,checkedAt:new Date(Date.now()-49*3600000).toISOString()})).toBe(false);expect(currentLead({...row,postedEarliestAt:new Date(Date.now()-100*86400000).toISOString()})).toBe(false);expect(currentLead({...row,postedLatestAt:new Date(Date.now()+86400000).toISOString()})).toBe(false);expect(currentLead({...row,postedEarliestAt:null})).toBe(false);});
 it('projects public WGS84 locations inside Taiwan viewport',()=>{for(const [lat,lng] of [[22.998651,120.2362147],[24.9537692,121.2412775]]){const p=mapPoint(lat,lng);expect(p.x).toBeGreaterThan(0);expect(p.x).toBeLessThan(512);expect(p.y).toBeGreaterThan(0);expect(p.y).toBeLessThan(768)}});
 it('reads all pages and shows public facts with login boundary',async()=>{const lead=(id:string)=>({...dates(),id,title:'來源 '+id,summary:'庫存待確認',canonicalUrl:'https://example.invalid/source/'+id,publicPlaceName:'公開地點',publicAddress:'公共地址',latitude:23,longitude:120.2,stockStatus:'UNKNOWN'});const fetch=vi.fn().mockResolvedValueOnce({ok:true,json:async()=>({items:[lead('a')],nextCursor:'a'})}).mockResolvedValueOnce({ok:true,json:async()=>({items:[lead('b')],nextCursor:null})});vi.stubGlobal('fetch',fetch);render(<MemoryRouter><SourceLeadMapPage/></MemoryRouter>);await screen.findByText('2 件來源線索・1 個公共地點');expect(fetch).toHaveBeenCalledTimes(2);expect(screen.getByText('登入後詢問')).toBeTruthy();fireEvent.change(screen.getByRole('combobox'),{target:{value:'b'}});expect(screen.getByRole('heading',{name:'來源 b'})).toBeTruthy();expect(screen.queryByRole('button',{name:'保存問題'})).toBeNull();});
 it('reports read failure instead of inventing zero confirmed goods',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false}));render(<MemoryRouter><SourceLeadMapPage/></MemoryRouter>);await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('來源暫時無法讀取'));expect(screen.queryByText('0 件來源線索・0 個公共地點')).toBeNull();});
 it('unknown ASK result recovers the same receipt without another action write',async()=>{
  auth.token='synthetic-token';const row={...dates(),id:'a',title:'來源 a',summary:'待確認',canonicalUrl:'https://example.invalid/a',publicPlaceName:'公共地點',publicAddress:'公共地址',latitude:23,longitude:120.2};let payload:any;let opens=0;const fetch=vi.fn(async(url:string,init:any)=>{
   if(url.endsWith('/actions')){payload=JSON.parse(init.body);throw Error('unknown');}
   if(url.endsWith('/inquiry')){opens++;return{ok:true,json:async()=>({id:'room',state:'INQUIRY',transferHash:'x',events:opens>1?[{...payload,at:'now'}]:[],delivered:false})};}
   return{ok:true,json:async()=>url.endsWith('/source-leads')?{items:[row],nextCursor:null}:row};});vi.stubGlobal('fetch',fetch);render(<MemoryRouter><SourceLeadMapPage/></MemoryRouter>);await screen.findByRole('heading',{name:'來源 a'});fireEvent.change(screen.getByRole('textbox'),{target:{value:'synthetic question'}});fireEvent.click(screen.getByRole('button',{name:'保存問題'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'保存問題'}));await screen.findByText('synthetic question');expect(fetch.mock.calls.filter(([url])=>url.endsWith('/actions'))).toHaveLength(1);
 });
 it('logout immediately hides saved private questions from the rendered scope',async()=>{
  auth.token='synthetic-token';const row={...dates(),id:'a',title:'來源 a',summary:'待確認',canonicalUrl:'https://example.invalid/a',publicPlaceName:'公共地點',publicAddress:'公共地址',latitude:23,longitude:120.2};vi.stubGlobal('fetch',vi.fn(async(url:string)=>({ok:true,json:async()=>url.endsWith('/inquiry')?{id:'room',state:'INQUIRY',events:[{action:'ASK',text:'private question'}],transferHash:'x'}:url.endsWith('/source-leads')?{items:[row],nextCursor:null}:row})));const view=render(<MemoryRouter><SourceLeadMapPage/></MemoryRouter>);await screen.findByRole('heading',{name:'來源 a'});fireEvent.click(screen.getByRole('button',{name:'讀取已存詢問'}));await screen.findByText('private question');auth.token=null;view.rerender(<MemoryRouter><SourceLeadMapPage/></MemoryRouter>);expect(screen.queryByText('private question')).toBeNull();
 });
 it('a definite rejected ASK clears its journal and allows cancellation',async()=>{
 auth.token='synthetic-token';const row={...dates(),id:'a',title:'來源 a',summary:'待確認',canonicalUrl:'https://example.invalid/a',publicPlaceName:'公共地點',publicAddress:'公共地址',latitude:23,longitude:120.2};const fetch=vi.fn(async(url:string,init:any)=>{if(url.endsWith('/actions')){const action=JSON.parse(init.body).action;return action==='ASK'?{ok:false,status:409}:{ok:true,json:async()=>({id:'room',state:'CANCELLED',events:[],transferHash:'x'})};}return{ok:true,json:async()=>url.endsWith('/inquiry')?{id:'room',state:'INQUIRY',events:[],transferHash:'x'}:url.endsWith('/source-leads')?{items:[row],nextCursor:null}:row};});vi.stubGlobal('fetch',fetch);render(<MemoryRouter><SourceLeadMapPage/></MemoryRouter>);await screen.findByRole('heading',{name:'來源 a'});fireEvent.change(screen.getByRole('textbox'),{target:{value:'question'}});fireEvent.click(screen.getByRole('button',{name:'保存問題'}));await screen.findByRole('alert');expect(sessionStorage.getItem('source-lead-request:1:a')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'撤回委託'}));await screen.findByText(/CANCELLED/);
 });
 it('a recovered unknown request blocks new writes until receipt or cancel, without storing private text',async()=>{
 auth.token='synthetic-token';sessionStorage.setItem('source-lead-request:1:a',JSON.stringify({requestId:'old-request',action:'ASK'}));const row={...dates(),id:'a',title:'來源 a',summary:'待確認',canonicalUrl:'https://example.invalid/a',publicPlaceName:'公共地點',publicAddress:'公共地址',latitude:23,longitude:120.2};const fetch=vi.fn(async(url:string)=>({ok:true,json:async()=>url.endsWith('/inquiry')?{id:'room',state:'INQUIRY',events:[],transferHash:'x'}:url.endsWith('/source-leads')?{items:[row],nextCursor:null}:row}));vi.stubGlobal('fetch',fetch);render(<MemoryRouter><SourceLeadMapPage/></MemoryRouter>);await screen.findByRole('heading',{name:'來源 a'});fireEvent.change(screen.getByRole('textbox'),{target:{value:'private new draft'}});fireEvent.click(screen.getByRole('button',{name:'保存問題'}));await screen.findByRole('alert');expect(fetch.mock.calls.some(([url])=>url.endsWith('/actions'))).toBe(false);expect(sessionStorage.getItem('source-lead-request:1:a')).not.toContain('private new draft');auth.token=null;
 });
});
