import {sourceLocationLabel} from '../lib/sourceLeadData';
import { ListingPhoto, ListingPhotoGallery } from '../components/ListingPhoto';
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { API_URL } from '../config';
type Lead = { locationPrecision?:'COUNTY_ILLUSTRATION'; media?:{id:string;sourceUrl:string;imageUrl:string;thumbnailUrl:string;alt:string}[]; county?:string;district?:string; id:string; title:string; summary:string; canonicalUrl:string; publicPlaceName:string; publicAddress:string; latitude:number; longitude:number; stockStatus:string; checkedAt:string; postedEarliestAt:string; postedLatestAt:string; publicFacts?:{priceText:string;originalDateLabel:string;sourceAccessNotice:string} };
export const mapPoint = (latitude:number, longitude:number) => ({x:((longitude+180)/360*128-106)*256,y:((1-Math.asinh(Math.tan(latitude*Math.PI/180))/Math.PI)/2*128-53)*256});
export function currentLead(lead:Lead, now=Date.now()) {
 const [year,month,day]=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now)).split('-').map(Number);
 const first=new Date(Date.UTC(year,month-3,1));const end=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();const cutoff=Date.UTC(first.getUTCFullYear(),first.getUTCMonth(),Math.min(day,end))-8*3600000;
 const lower=Date.parse(lead.postedEarliestAt),upper=Date.parse(lead.postedLatestAt),checked=Date.parse(lead.checkedAt);
 return Number.isFinite(lower)&&Number.isFinite(upper)&&Number.isFinite(checked)&&lower>=cutoff&&lower<=upper&&upper<=now&&checked<=now&&now-checked<=48*3600000;
}
export default function SourceLeadMapPage() {
 const navigate=useNavigate();const [params,setParams]=useSearchParams();const [items,setItems]=useState<Lead[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const selected=items.find(i=>i.id===params.get('id'))??items[0];
 useEffect(()=>{let stopped=false;let loading=false;async function refresh(){if(loading)return;loading=true;try{const all:Lead[]=[];let cursor:string|null=null;const seen=new Set<string>();do{const r:Response=await fetch(`${API_URL}/source-leads?presentation=1&approximate=1${cursor?'&cursor='+encodeURIComponent(cursor):''}`);if(!r.ok)throw Error('來源暫時無法讀取');const data:{items:Lead[];nextCursor:string|null}=await r.json();if(!Array.isArray(data.items))throw Error('來源回應無效');all.push(...data.items);cursor=data.nextCursor;if(cursor&&seen.has(cursor))throw Error('分頁未前進');if(cursor)seen.add(cursor);}while(cursor);if(!stopped){setItems(all.filter(r=>currentLead(r)));setLoaded(true);setError('');}}catch(e){if(!stopped){setItems([]);setLoaded(false);setError((e as Error).message);}}finally{loading=false;}}
 const foreground=()=>{if(document.visibilityState==='visible')void refresh()};void refresh();const timer=setInterval(()=>void refresh(),30000);document.addEventListener('visibilitychange',foreground);return()=>{stopped=true;clearInterval(timer);document.removeEventListener('visibilitychange',foreground)};},[]);
 const points=Array.from(new Map(items.map(i=>[`${i.latitude},${i.longitude}`,i])).values());
 return <main className="max-w-6xl mx-auto p-4 space-y-4"><h1 className="text-2xl font-bold">來源線索地圖</h1><p>庫存、圖文權利與交易仍待確認；來源線索不計入已驗證商品達成率。公共面交點不是賣家或現貨所在地；概略位置是縣市示意，非取貨點。</p><p>{loaded?`${items.length} 件來源線索・${points.length} 個公共／概略示意位置`:'讀取中…'}</p>{error&&<p role="alert">{error}</p>}
 <div className="grid md:grid-cols-2 gap-4"><div><div className="relative overflow-hidden border rounded" style={{aspectRatio:'2/3'}} aria-label="台灣來源線索位置地圖"><svg viewBox="0 0 512 768" role="img" aria-label="OpenStreetMap 台灣來源示意位置"><title>來源線索公共與概略位置地圖</title>{[106,107].flatMap(x=>[53,54,55].map(y=><foreignObject key={`${x}-${y}`} x={(x-106)*256} y={(y-53)*256} width="256" height="256"><img alt="" referrerPolicy="origin" src={`https://tile.openstreetmap.org/7/${x}/${y}.png`} width="256" height="256" /></foreignObject>))}{points.map(i=>{const p=mapPoint(i.latitude,i.longitude);const count=items.filter(j=>j.latitude===i.latitude&&j.longitude===i.longitude).length;return <g key={i.id} role="button" tabIndex={0} aria-label={i.publicPlaceName} onClick={()=>setParams({id:i.id})} onKeyDown={e=>{if(e.key==='Enter')setParams({id:i.id})}}><circle cx={p.x} cy={p.y} r="9" fill="#2563eb"/><text x={p.x+12} y={p.y} fontSize="12" fill="#111">{count}件</text></g>;})}</svg></div><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL</a><p>地圖含公共地點與縣市示意點；概略位置，非取貨點，不提供精確距離或導航。實際面交地點待確認可轉告後私訊買家。</p></div>
 <div className="space-y-3"><div className="max-h-80 overflow-auto space-y-2" aria-label="來源商品清單">{items.map(i=><button key={i.id} onClick={()=>setParams({id:i.id})} aria-label={`查看 ${i.title}`} className="flex w-full gap-3 rounded-2xl border border-stone-200 bg-white p-3 text-left"><ListingPhoto src={i.media?.[0]?.thumbnailUrl} alt={i.media?.[0]?.alt||i.title}/><span className="min-w-0 space-y-1"><span className="block text-xs text-stone-500">外部來源 · 庫存待確認</span><span className="block font-semibold text-stone-900">{i.title}</span><span className="block font-semibold text-blue-700">{i.publicFacts?.priceText||"售價待詢問"}</span><span className="block text-sm text-stone-600">{i.county}{i.district} · {sourceLocationLabel(i)}</span></span></button>)}</div><label>選擇線索 <select className="w-full border p-2" value={selected?.id??''} onChange={e=>setParams({id:e.target.value})}>{items.map(i=><option key={i.id} value={i.id}>{i.title} — {i.publicPlaceName}</option>)}</select></label>{selected&&<><article className="overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm"><ListingPhotoGallery key={selected.id} photos={selected.media??[]} title={selected.title}/><div className="space-y-4 p-5"><p className="text-sm text-stone-500">外部來源 · 庫存與交易待確認</p><h2 className="text-2xl font-bold text-stone-900">{selected.title}</h2><p className="text-2xl font-semibold text-blue-700">{selected.publicFacts?.priceText||"售價待詢問"}</p><p className="text-stone-600">{selected.county}{selected.district} · {sourceLocationLabel(selected)}，非現貨所在地</p><h3 className="font-semibold">商品說明</h3><p className="whitespace-pre-wrap text-stone-700">{selected.summary}</p><p className="text-sm text-stone-600">{selected.locationPrecision==='COUNTY_ILLUSTRATION'?selected.publicAddress:selected.publicPlaceName+'：'+selected.publicAddress}</p></div></article><p>{selected.publicFacts?.originalDateLabel}</p><p>{selected.publicFacts?.sourceAccessNotice}</p><a className="underline" href={selected.canonicalUrl} target="_blank" rel="noreferrer">查看原始來源</a><button className="min-h-12 rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white" onClick={()=>navigate('/chat?source='+selected.id)}>聯絡賣家</button></>}</div></div></main>;
}
