import { act,cleanup,fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { MemoryRouter,Route,Routes } from 'react-router-dom';
import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest';
import WishlistDetail from './WishlistDetail';
import { API_URL } from '../config';
import { photoUploadJournal,parsePhotoUploadJournal } from '../lib/listingPhotoUploadWeb';
const {identity,store}=vi.hoisted(()=>({identity:{user:{id:42},token:'synthetic-a'},store:{get:vi.fn(),save:vi.fn(),clear:vi.fn()}}));
vi.mock('../context/AuthContext',()=>({useAuth:()=>identity}));
vi.mock('../lib/webPendingStore',async load=>({...await load<object>(),pendingRequestKey:async (_api:string,id:number,feature:string)=>`${id}.${feature}`,privatePendingStore:store}));
vi.mock('../utils/analytics',()=>({Analytics:{logViewItemList:vi.fn(),logShare:vi.fn()}}));
const row={id:1,userId:42,title:'合成新增清單',description:'合成说明',isPublic:false,maxItems:100,items:[]};
const response=(body:unknown,status=200)=>({ok:status>=200 && status<300,status,json:async()=>body});
const fetcher=vi.fn(),saved=new Map<string,string>(),id='11111111-1111-4111-8111-111111111111',mediaId='22222222-2222-4222-8222-222222222222';
const file=()=>new File(['synthetic-photo'],'fixture.jpg',{type:'image/jpeg'});
function tree(){return <MemoryRouter initialEntries={['/wishlists/1']}><Routes><Route path="/wishlists/:id" element={<WishlistDetail/>}/></Routes></MemoryRouter>;}
const mount=()=>render(tree());
const writes=()=>fetcher.mock.calls.filter(c=>['PUT','POST','DELETE'].includes(c[1]?.method));
async function open(kind='LINK'){const add=await screen.findByRole('button',{name:'新增'});await waitFor(()=>expect(add).toBeEnabled());fireEvent.click(add);fireEvent.click(screen.getByRole('button',{name:kind==='LINK'?'新增連結':'上傳圖片'}));return screen.getByRole('dialog',{name:kind==='LINK'?'新增願望 · 網址或文字':'新增願望 · 照片辨識'});}
const ack=(body:Record<string,unknown>,extra={})=>({id:50,wishlistId:1,name:body.name,notes:body.notes,price:body.price,currency:body.currency,maxPrice:body.maxPrice,priceCurrency:body.maxPrice===null?null:body.priceCurrency,link:String(body.url).startsWith('https:')?body.url:null,proxy_end_user_id:null,aiStatus:body.mediaId || String(body.url).startsWith('https:')?'PENDING':'SKIPPED',aiError:null,uploadStatus:'COMPLETED',isPurchased:false,isHidden:false,clientRequestId:body.clientRequestId,requestHash:body.requestHash,createKind:body.mediaId?'PHOTO':'LINK',replayed:false,...extra});
const marker=()=>JSON.parse(saved.get('42.legacy-detail-operation')!);
async function photoFixture(listId=1){const body=await photoUploadJournal(file(),id,'MANUAL_PHOTO'),journal=await parsePhotoUploadJournal(body,'MANUAL_PHOTO'),createdAt=new Date().toISOString(),base=API_URL.replace(/\/api\/?$/,'');return {outer:JSON.stringify({version:1,listId,body}),receipt:{receipt:{clientUploadId:id,requestHash:journal.requestHash,state:'STORED',mediaId,createdAt},media:{id:mediaId,ownerUserId:42,clientUploadId:id,capturePurpose:'MANUAL_PHOTO',contentHash:'a'.repeat(64),listingId:null,wishItemId:null,imageUrl:base+'/api/listing-media/'+mediaId+'/image',thumbnailUrl:base+'/api/listing-media/'+mediaId+'/thumbnail',width:320,height:240,byteSize:123,createdAt}}};}
beforeEach(()=>{identity.user.id=42;identity.token='synthetic-a';saved.clear();window.localStorage.setItem('user-locale','zh-TW');store.get.mockReset().mockImplementation(async key=>saved.get(key)??null);store.save.mockReset().mockImplementation(async(key,raw)=>{if(saved.has(key)&&saved.get(key)!==raw)throw Error('CAS');saved.set(key,raw);});store.clear.mockReset().mockImplementation(async(key,raw)=>{if(saved.get(key)!==raw)return false;saved.delete(key);return true;});fetcher.mockReset().mockResolvedValue(response(row));vi.stubGlobal('fetch',fetcher);});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe('durable legacy link/text and photo UI',()=>{
  it('accepts text without URL-only browser validation and confirms all independent price/budget fields',async()=>{fetcher.mockImplementation(async(_url,init)=>response(init?.method==='POST'?ack(JSON.parse(init.body)):row));mount();const dialog=await open();expect(within(dialog).getByLabelText('商品網址或願望文字')).toHaveAttribute('type','text');fireEvent.change(within(dialog).getByLabelText('商品網址或願望文字'),{target:{value:'合成文字願望'}});for(const [label,value] of [['原網站參考價格','0'],['參考價格幣別','usd'],['最高預算','25.50'],['預算幣別','twd'],['備註','合成新增備註']])fireEvent.change(within(dialog).getByLabelText(label),{target:{value}});fireEvent.click(within(dialog).getByRole('button',{name:'保存並新增願望'}));await screen.findByRole('heading',{name:'合成文字願望'});await waitFor(()=>expect(saved.size).toBe(0));const body=JSON.parse(writes()[0][1].body);expect(body).toMatchObject({url:'合成文字願望',name:'合成文字願望',price:'0',currency:'USD',maxPrice:25.5,priceCurrency:'TWD',notes:'合成新增備註',requestHash:expect.stringMatching(/^[a-f0-9]{64}$/)});expect(body).not.toHaveProperty('link');expect(writes()).toHaveLength(1);expect(store.save.mock.invocationCallOrder[0]).toBeLessThan(fetcher.mock.invocationCallOrder[1]);});
  it.each(['https://user:pass@example.com/p','https://127.0.0.1/p','javascript:bad','a'.repeat(201)])('rejects invalid source before any storage or POST %s',async input=>{mount();const dialog=await open();fireEvent.change(within(dialog).getByLabelText('商品網址或願望文字'),{target:{value:input}});fireEvent.click(within(dialog).getByRole('button',{name:'保存並新增願望'}));await within(dialog).findByText(/請輸入無帳密/);expect(writes()).toHaveLength(0);expect(store.save).not.toHaveBeenCalled();});
  it.each([{wishlistId:9},{requestHash:'a'.repeat(64)},{createKind:'PHOTO'},{maxPrice:9}])('keeps an unconfirmed create identity and displays no false wish for mismatched ACK %#',async extra=>{fetcher.mockImplementation(async(_url,init)=>response(init?.method==='POST'?ack(JSON.parse(init.body),extra):row));mount();const dialog=await open();fireEvent.change(within(dialog).getByLabelText('商品網址或願望文字'),{target:{value:'未確認願望'}});fireEvent.click(within(dialog).getByRole('button',{name:'保存並新增願望'}));await screen.findAllByText(/尚未確認原願望建立/);expect(screen.queryByRole('heading',{name:'未確認願望'})).not.toBeInTheDocument();expect(marker()).toMatchObject({kind:'LINK_CREATE',id:1});expect(saved.get('42.legacy-detail-operation')).not.toContain('未確認願望');expect(within(dialog).getByRole('button',{name:'保存並新增願望'})).toBeDisabled();expect(writes()).toHaveLength(1);});
  it('does not POST when private storage cannot save the create marker',async()=>{store.save.mockRejectedValue(Error('quota'));mount();const dialog=await open();fireEvent.change(within(dialog).getByLabelText('商品網址或願望文字'),{target:{value:'合成願望'}});fireEvent.click(within(dialog).getByRole('button',{name:'保存並新增願望'}));await screen.findAllByText(/無法安全恢復或保存/);expect(writes()).toHaveLength(0);});
  it('restores an unknown create without replay and requires its exact historical receipt',async()=>{fetcher.mockImplementation(async(_url,init)=>response(init?.method==='POST'?{}:row,init?.method==='POST'?502:200));const view=mount();const dialog=await open();fireEvent.change(within(dialog).getByLabelText('商品網址或願望文字'),{target:{value:'合成願望'}});fireEvent.click(within(dialog).getByRole('button',{name:'保存並新增願望'}));await screen.findAllByText(/尚未確認原願望建立/);const original=marker();view.unmount();fetcher.mockImplementation(async url=>response(String(url).includes('/create-receipts/')?{...original,kind:'LINK',wishlistId:1,state:'CREATED',resourceId:50,resource:{id:50,wishlistId:1},deleted:false}:row));mount();fireEvent.click(await screen.findByRole('button',{name:'查核原願望建立'}));await screen.findByText(/原願望已建立/);expect(saved.size).toBe(1);fireEvent.click(screen.getByRole('button',{name:'清理已確認操作的本機標記'}));await waitFor(()=>expect(saved.size).toBe(0));expect(writes()).toHaveLength(1);});
  it('keeps a missing receipt and safely stops exactly its original identity',async()=>{const original={version:1,id:1,kind:'LINK_CREATE',clientRequestId:id,requestHash:'a'.repeat(64),localOperationId:mediaId};saved.set('42.legacy-detail-operation',JSON.stringify(original));fetcher.mockImplementation(async(url,init)=>String(url).includes('/create-receipts/')?response(init?.method==='POST'?{clientRequestId:id,requestHash:original.requestHash,kind:'LINK',wishlistId:1,state:'ABANDONED',resourceId:null,resource:null,deleted:false}:{},init?.method==='POST'?200:404):response(row));mount();fireEvent.click(await screen.findByRole('button',{name:'查核原願望建立'}));await screen.findByText(/尚未取得原建立回執/);expect(screen.getByRole('button',{name:'已讀目前狀態，清理標記並恢復操作'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'安全停止原願望建立'}));await screen.findByText(/原願望建立已安全停止/);expect(JSON.parse(writes()[0][1].body)).toEqual({kind:'LINK',wishlistId:1,requestHash:'a'.repeat(64)});expect(writes()).toHaveLength(1);});
  it('restores a confirmed unused manual photo by GET and allows only saving that owned media',async()=>{const f=await photoFixture();saved.set('42.legacy-wish-photo',f.outer);fetcher.mockImplementation(async(url,init)=>response(String(url).includes('/upload-receipts/')?f.receipt:init?.method==='POST'?ack(JSON.parse(init.body)):row));mount();await screen.findByText(/原照片已上傳/);expect(screen.getByRole('button',{name:'新增'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'新增願望 · 照片辨識'}));const dialog=screen.getByRole('dialog');expect(within(dialog).getByRole('button',{name:'選回同一照片，明確重試原上傳'})).toBeDisabled();fireEvent.change(within(dialog).getByLabelText('願望名稱（選填，照片可由 AI 更新）'),{target:{value:'合成照片願望'}});fireEvent.click(within(dialog).getByRole('button',{name:'保存並新增願望'}));await screen.findByRole('heading',{name:'合成照片願望'});expect(writes()[0][0]).toContain('/wishlists/1/items/from-media');expect(JSON.parse(writes()[0][1].body).mediaId).toBe(mediaId);expect(writes()).toHaveLength(1);});
  it('offers original-list navigation and never adopts another list photo for a new wish',async()=>{const f=await photoFixture(9);saved.set('42.legacy-wish-photo',f.outer);fetcher.mockImplementation(async url=>response(String(url).includes('/upload-receipts/')?f.receipt:row));mount();expect(await screen.findByRole('link',{name:'開啟原照片清單'})).toHaveAttribute('href','/wishlists/9');expect(screen.queryByRole('button',{name:'新增願望 · 照片辨識'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'新增'})).toBeDisabled();expect(writes()).toHaveLength(0);});
  it('cleans an attached photo only after readback and never offers reuse or removal',async()=>{const f=await photoFixture();f.receipt.media.wishItemId=50 as unknown as null;saved.set('42.legacy-wish-photo',f.outer);fetcher.mockImplementation(async url=>response(String(url).includes('/upload-receipts/')?f.receipt:row));mount();await screen.findByText(/照片已附加到願望/);expect(screen.queryByRole('button',{name:'移除未使用照片'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'清理已確認照片的本機標記'}));await waitFor(()=>expect(saved.size).toBe(0));expect(writes()).toHaveLength(0);});
  it('retains an unknown upload, stops with its hash, and never automatically resends the file',async()=>{const f=await photoFixture();saved.set('42.legacy-wish-photo',f.outer);fetcher.mockImplementation(async(url,init)=>String(url).includes('/upload-receipts/')?response(init?.method==='POST'?{receipt:{...f.receipt.receipt,state:'ABANDONED',mediaId:null},media:null}:{},init?.method==='POST'?200:404):response(row));mount();await screen.findByText(/原照片尚未確認/);expect(writes()).toHaveLength(0);fireEvent.click(screen.getByRole('button',{name:'安全停止原照片上傳'}));await screen.findByText(/原照片上傳已停止/);expect(JSON.parse(writes()[0][1].body)).toEqual({requestHash:f.receipt.receipt.requestHash});expect(writes()[0][0]).toContain('/upload-receipts/'+id+'/abandon');});
  it('opens a named removal confirmation and cancels without removing the original unused photo',async()=>{const f=await photoFixture();saved.set('42.legacy-wish-photo',f.outer);fetcher.mockImplementation(async url=>response(String(url).includes('/upload-receipts/')?f.receipt:row));mount();fireEvent.click(await screen.findByRole('button',{name:'移除未使用照片'}));const dialog=screen.getByRole('dialog',{name:'確認移除未使用照片'});expect(dialog).toContainElement(document.activeElement as HTMLElement);fireEvent.click(within(dialog).getByRole('button',{name:'取消'}));expect(writes()).toHaveLength(0);expect(saved.size).toBe(1);});
  it('saves a removal identity before POST and keeps both markers when the ACK is lost',async()=>{const f=await photoFixture();saved.set('42.legacy-wish-photo',f.outer);fetcher.mockImplementation(async(url,init)=>response(String(url).includes('/upload-receipts/')?f.receipt:init?.method==='POST'?{}:row,init?.method==='POST'?502:200));mount();fireEvent.click(await screen.findByRole('button',{name:'移除未使用照片'}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'移除未使用照片'}));await screen.findByText(/原照片移除待查核/);expect(saved.size).toBe(2);expect(writes()).toHaveLength(1);expect(writes()[0][0]).toContain('/native-wishes/photo-removals/'+id);expect(JSON.parse(saved.get('42.legacy-wish-photo-remove')!).photo).toBe(f.outer);});
  it('ignores a late create response after account departure and preserves its scoped marker',async()=>{let finish!:(v:unknown)=>void,body!:Record<string,unknown>;fetcher.mockImplementation((_url,init)=>init?.method==='POST'?new Promise(resolve=>{finish=resolve;body=JSON.parse(init.body);}):Promise.resolve(response(row)));const view=mount();const dialog=await open();fireEvent.change(within(dialog).getByLabelText('商品網址或願望文字'),{target:{value:'合成晚到願望'}});fireEvent.click(within(dialog).getByRole('button',{name:'保存並新增願望'}));await waitFor(()=>expect(finish).toBeDefined());identity.user.id=7;identity.token='synthetic-b';view.rerender(tree());await screen.findByRole('heading',{name:'合成新增清單'});await act(async()=>finish(response(ack(body))));expect(screen.queryByRole('heading',{name:'合成晚到願望'})).not.toBeInTheDocument();expect(saved.has('42.legacy-detail-operation')).toBe(true);expect(store.clear).not.toHaveBeenCalled();});
  it('honors the authoritative removal ACK, preserving confirmation through failed local cleanup',async()=>{const f=await photoFixture();saved.set('42.legacy-wish-photo',f.outer);store.clear.mockRejectedValue(Error('quota'));const removed={clientUploadId:id,mediaId,removed:true,cleanupPending:true,removedAt:new Date().toISOString()};fetcher.mockImplementation(async(url,init)=>response(String(url).includes('/upload-receipts/')?f.receipt:String(url).includes('/photo-removals/')?removed:row));mount();fireEvent.click(await screen.findByRole('button',{name:'移除未使用照片'}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'移除未使用照片'}));await screen.findByText(/已確認原照片移除/);await screen.findByText(/照片狀態已確認，但本機標記尚未清理/);expect(saved.size).toBe(2);expect(writes()).toHaveLength(1);store.clear.mockImplementation(async(key,raw)=>{if(saved.get(key)!==raw)return false;saved.delete(key);return true;});fireEvent.click(screen.getByRole('button',{name:'查核原照片移除'}));await waitFor(()=>expect(saved.size).toBe(0));expect(writes()).toHaveLength(1);});
  it('restores a removal by GET and never clears a newer photo marker',async()=>{const f=await photoFixture(),original=f.outer,journal=JSON.parse(JSON.parse(original).body),body=JSON.stringify({version:1,mediaId,photoBody:JSON.stringify({version:1,clientUploadId:id,digest:journal.sourceHash})}),removal=JSON.stringify({version:1,listId:1,photo:original,body});const newer=await photoFixture(9);saved.set('42.legacy-wish-photo',newer.outer);saved.set('42.legacy-wish-photo-remove',removal);fetcher.mockImplementation(async url=>response(String(url).includes('/photo-removals/')?{clientUploadId:id,mediaId,removed:true,cleanupPending:false,removedAt:new Date().toISOString()}:row));mount();await screen.findByText(/已確認原照片移除/);await waitFor(()=>expect(saved.has('42.legacy-wish-photo-remove')).toBe(false));expect(saved.get('42.legacy-wish-photo')).toBe(newer.outer);expect(writes()).toHaveLength(0);});
});
