import { act,cleanup,fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { MemoryRouter,Route,Routes } from 'react-router-dom';
import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest';
import WishlistDetail from './WishlistDetail';
const {identity,store}=vi.hoisted(()=>({identity:{user:{id:42},token:'synthetic-a'},store:{get:vi.fn(),save:vi.fn(),clear:vi.fn()}}));
vi.mock('../context/AuthContext',()=>({useAuth:()=>identity}));
vi.mock('../lib/webPendingStore',()=>({pendingRequestKey:async (_api:string,id:number,feature:string)=>`${id}.${feature}`,privatePendingStore:store}));
vi.mock('../utils/analytics',()=>({Analytics:{logViewItemList:vi.fn(),logShare:vi.fn()}}));
const item={id:4,wishlistId:1,name:'合成願望',price:'100.5',currency:'USD',maxPrice:750.75,priceCurrency:'TWD',isPurchased:false,isHidden:false,uploadStatus:'COMPLETED',aiStatus:'SKIPPED',notes:'原備註',link:'https://example.com/product',aiLink:'https://example.com/ai-product'};
const row={id:1,title:'合成清單',description:'原說明',userId:42,user:{id:42,name:'合成許願者'},isPublic:true,items:[item],maxItems:100};
const destination=()=>({id:2,title:'合成目標清單',description:null,userId:identity.user.id,isPublic:false,items:[],maxItems:2});
const response=(body:unknown,status=200)=>({ok:status>=200 && status<300,status,json:async()=>body});
const fetcher=vi.fn(),saved=new Map<string,string>();
function tree(){return <MemoryRouter initialEntries={['/wishlists/1']}><Routes><Route path="/wishlists/:id" element={<WishlistDetail/>}/></Routes></MemoryRouter>;}
const mount=()=>render(tree());
const writes=()=>fetcher.mock.calls.filter(c=>['PUT','POST','DELETE'].includes(c[1]?.method));
async function details(){fireEvent.click(await screen.findByRole('button',{name:'查看願望 合成願望'}));return screen.getByRole('dialog',{name:'合成願望'});}
async function editor(){const dialog=await details();await waitFor(()=>expect(within(dialog).getByRole('button',{name:'編輯願望'})).toBeEnabled());fireEvent.click(within(dialog).getByRole('button',{name:'編輯願望'}));return screen.getByRole('dialog',{name:'編輯願望 · 合成願望'});}
async function cloneDialog(){const button=await screen.findByRole('button',{name:'加入我的清單 合成願望'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);await screen.findByRole('radio',{name:'合成目標清單 · 0/2'});return screen.getByRole('dialog',{name:'加入我的清單 · 合成願望'});}
async function dispatchClone(){const dialog=await cloneDialog();fireEvent.click(within(dialog).getByRole('radio'));fireEvent.click(within(dialog).getByRole('button',{name:'確認加入清單'}));return dialog;}
const cloneAck=(body:Record<string,unknown>)=>({...item,id:50,wishlistId:2,clonedFromItemId:4,clientRequestId:body.clientRequestId,replayed:false});
function pendingClone(){return JSON.parse(saved.get('7.legacy-detail-operation')!);}
const receipt=(marker:ReturnType<typeof pendingClone>,extra={})=>({clientRequestId:marker.clientRequestId,kind:'CLONE',sourceItemId:4,targetWishlistId:2,state:'CREATED',resourceId:50,deleted:false,resource:{...item,id:50,wishlistId:2},...extra});
beforeEach(()=>{identity.user.id=42;identity.token='synthetic-a';saved.clear();window.localStorage.setItem('user-locale','zh-TW');store.get.mockReset().mockImplementation(async key=>saved.get(key)??null);store.save.mockReset().mockImplementation(async (key,raw)=>{saved.set(key,raw);});store.clear.mockReset().mockImplementation(async (key,raw)=>{if(saved.get(key)!==raw)return false;saved.delete(key);return true;});fetcher.mockReset().mockImplementation(async url=>response(String(url).endsWith('/wishlists')?[destination()]:row));vi.stubGlobal('fetch',fetcher);});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe('legacy item dialog and durable clone operations',()=>{
  it('shows distinct original reference price and maximum budget and retains source links and attribution',async()=>{
    mount();const dialog=await details();expect(within(dialog).getByText('100.5 USD')).toBeInTheDocument();expect(within(dialog).getByText('750.75 TWD')).toBeInTheDocument();expect(within(dialog).getByRole('link',{name:'參考商品連結'})).toHaveAttribute('href','https://example.com/product');expect(within(dialog).getByRole('link',{name:'AI 參考商品'})).toHaveAttribute('href','https://example.com/ai-product');expect(within(dialog).getByRole('link',{name:'查看許願者個人頁'})).toHaveAttribute('href','/users/42/profile');expect(writes()).toHaveLength(0);
  });
  it('normalizes and confirms all editable price, budget, currency, name, notes and URL fields',async()=>{
    fetcher.mockImplementation(async (url,init)=>response(init?.method==='PUT'?{...item,...JSON.parse(init.body)}:String(url).endsWith('/wishlists')?[destination()]:row));mount();const dialog=await editor();fireEvent.change(within(dialog).getByLabelText('願望名稱'),{target:{value:' 新願望名稱 '}});fireEvent.change(within(dialog).getByLabelText('原網站參考價格'),{target:{value:'123.50'}});fireEvent.change(within(dialog).getByLabelText('參考價格幣別'),{target:{value:'eur'}});fireEvent.change(within(dialog).getByLabelText('最高預算'),{target:{value:'0'}});fireEvent.change(within(dialog).getByLabelText('預算幣別'),{target:{value:'twd'}});fireEvent.change(within(dialog).getByLabelText('備註'),{target:{value:'新備註'}});fireEvent.change(within(dialog).getByLabelText('參考商品連結'),{target:{value:'https://example.com'}});fireEvent.click(within(dialog).getByRole('button',{name:'儲存'}));await screen.findByRole('dialog',{name:'新願望名稱'});await waitFor(()=>expect(saved.size).toBe(0));expect(JSON.parse(writes()[0][1].body)).toEqual({name:'新願望名稱',price:'123.5',currency:'EUR',maxPrice:0,priceCurrency:'TWD',notes:'新備註',link:'https://example.com/'});expect(writes()[0][0]).toMatch(/\/items\/4$/);expect(screen.getByRole('dialog',{name:'新願望名稱'})).toBeInTheDocument();
  });
  it('supports explicit clearing of price, budget and URL with null acknowledgments',async()=>{
    fetcher.mockImplementation(async (_url,init)=>response(init?.method==='PUT'?{...item,...JSON.parse(init.body),priceCurrency:null}:row));mount();const dialog=await editor();for(const label of ['原網站參考價格','最高預算','參考商品連結'])fireEvent.change(within(dialog).getByLabelText(label),{target:{value:''}});fireEvent.click(within(dialog).getByRole('button',{name:'儲存'}));await waitFor(()=>expect(screen.queryByRole('dialog',{name:'編輯願望 · 合成願望'})).not.toBeInTheDocument());expect(JSON.parse(writes()[0][1].body)).toMatchObject({price:null,maxPrice:null,link:null});expect(saved.size).toBe(0);
  });
  it.each([{id:5},{wishlistId:99},{maxPrice:99},{price:'99'},{link:'https://wrong.example/'}])('does not optimistically display edited fields when ACK mismatches %#',async override=>{
    fetcher.mockImplementation(async (_url,init)=>response(init?.method==='PUT'?{...item,...JSON.parse(init.body),...override}:row));mount();const dialog=await editor();fireEvent.change(within(dialog).getByLabelText('願望名稱'),{target:{value:'未確認名稱'}});fireEvent.click(within(dialog).getByRole('button',{name:'儲存'}));await screen.findAllByText(/結果尚未確認/);expect(screen.getByRole('heading',{name:'合成願望'})).toBeInTheDocument();expect(screen.queryByRole('heading',{name:'未確認名稱'})).not.toBeInTheDocument();expect(within(dialog).getByRole('button',{name:'儲存'})).toBeDisabled();expect(saved.size).toBe(1);expect(writes()).toHaveLength(1);
  });
  it('holds one item edit through storage and network waits, blocking close and repeated submit',async()=>{
    let finish!:(value:unknown)=>void;fetcher.mockImplementation((_url,init)=>init?.method==='PUT'?new Promise(resolve=>{finish=resolve;}):Promise.resolve(response(row)));mount();const dialog=await editor();fireEvent.click(within(dialog).getByRole('button',{name:'儲存'}));await waitFor(()=>expect(finish).toBeDefined());fireEvent.click(within(dialog).getByRole('button',{name:'儲存'}));fireEvent.keyDown(dialog,{key:'Escape'});expect(within(dialog).getByRole('button',{name:'關閉'})).toBeDisabled();expect(writes()).toHaveLength(1);await act(async()=>finish(response({...item,name:'合成願望',notes:'原備註',link:'https://example.com/product',price:'100.5',currency:'USD',maxPrice:750.75,priceCurrency:'TWD'})));
  });
  it('offers read-only detail while storage restoration failure disables every modal write',async()=>{
    store.get.mockRejectedValue(new Error('synthetic unavailable'));mount();const dialog=await details();await screen.findAllByText(/無法安全恢復/);expect(within(dialog).getByRole('button',{name:'編輯願望'})).toBeDisabled();expect(within(dialog).getByRole('button',{name:'刪除願望'})).toBeDisabled();expect(within(dialog).getByText('750.75 TWD')).toBeInTheDocument();expect(writes()).toHaveLength(0);
  });
  it('requires an explicit own target selection and uses the source clone endpoint with a saved request identity',async()=>{
    identity.user.id=7;fetcher.mockImplementation(async (url,init)=>response(init?.method==='POST'?cloneAck(JSON.parse(init.body)):String(url).endsWith('/wishlists')?[destination()]:row));mount();const dialog=await cloneDialog();expect(within(dialog).getByRole('link',{name:'建立我的清單'})).toHaveAttribute('href','/dashboard');expect(within(dialog).getByRole('button',{name:'確認加入清單'})).toBeDisabled();fireEvent.click(within(dialog).getByRole('radio'));fireEvent.click(within(dialog).getByRole('button',{name:'確認加入清單'}));await screen.findAllByText('願望複製已確認。');await waitFor(()=>expect(saved.size).toBe(0));expect(writes()).toHaveLength(1);expect(writes()[0][0]).toMatch(/\/items\/4\/clone$/);expect(JSON.parse(writes()[0][1].body)).toEqual({targetWishlistId:2,clientRequestId:expect.stringMatching(/^[0-9a-f-]{36}$/)});expect(store.save.mock.invocationCallOrder[0]).toBeLessThan(fetcher.mock.invocationCallOrder[fetcher.mock.calls.findIndex(c=>c[1]?.method==='POST')]);
  });
  it('routes the detail dialog clone action through the same target picker, never through nested item creation',async()=>{
    identity.user.id=7;mount();const dialog=await details();await waitFor(()=>expect(within(dialog).getByRole('button',{name:'加入我的清單'})).toBeEnabled());fireEvent.click(within(dialog).getByRole('button',{name:'加入我的清單'}));await screen.findByRole('radio',{name:'合成目標清單 · 0/2'});expect(screen.queryByRole('dialog',{name:'合成願望'})).not.toBeInTheDocument();expect(writes()).toHaveLength(0);
  });
  it('labels the English target picker and creation alternative without untranslated keys',async()=>{
    identity.user.id=7;window.localStorage.setItem('user-locale','en-US');mount();const button=await screen.findByRole('button',{name:'Add to my wishlist 合成願望'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);await screen.findByRole('radio',{name:'合成目標清單 · 0/2'});const dialog=screen.getByRole('dialog',{name:'Add to my wishlist · 合成願望'});expect(within(dialog).getByRole('link',{name:'Create my wishlist'})).toHaveAttribute('href','/dashboard');expect(within(dialog).getByRole('button',{name:'Confirm copy to list'})).toBeDisabled();expect(dialog.textContent).not.toContain('detail.');expect(writes()).toHaveLength(0);
  });
  it('retains a clone across reload and reads only its original immutable receipt before cleanup',async()=>{
    identity.user.id=7;fetcher.mockImplementation(async (url,init)=>response(init?.method==='POST'?{}:String(url).endsWith('/wishlists')?[destination()]:row,init?.method==='POST'?502:200));const view=mount();await dispatchClone();await screen.findAllByText(/尚未確認原複製結果/);const marker=pendingClone();expect(marker).toMatchObject({id:1,itemId:4,targetWishlistId:2,kind:'CLONE'});expect(saved.values().next().value).not.toContain('合成願望');view.unmount();
    fetcher.mockImplementation(async url=>response(String(url).includes('/clone-receipts/')?receipt(marker):row));mount();await screen.findByText(/原願望複製待查核/);expect(writes()).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'查核原願望複製'}));await screen.findByText('原複製已建立；目前願望可到目標清單查看。');expect(saved.size).toBe(1);expect(fetcher.mock.calls.filter(c=>String(c[0]).includes('/clone-receipts/') && c[1]?.method==='GET')).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'清理已確認操作的本機標記'}));await waitFor(()=>expect(saved.size).toBe(0));expect(writes()).toHaveLength(1);
  });
  it('retains a missing receipt and safely stops the original identity without retrying the clone',async()=>{
    identity.user.id=7;const marker={version:1,id:1,kind:'CLONE',itemId:4,targetWishlistId:2,clientRequestId:'11111111-1111-4111-8111-111111111111',localOperationId:'22222222-2222-4222-8222-222222222222'};saved.set('7.legacy-detail-operation',JSON.stringify(marker));fetcher.mockImplementation(async (url,init)=>String(url).includes('/clone-receipts/')?response(init?.method==='POST'?receipt(marker,{state:'ABANDONED',resourceId:null,resource:null}):{},init?.method==='POST'?200:404):response(row));mount();fireEvent.click(await screen.findByRole('button',{name:'查核原願望複製'}));await screen.findByText(/尚未取得原複製回執/);expect(screen.getByRole('button',{name:'已讀目前狀態，清理標記並恢復操作'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'安全停止原複製'}));await screen.findByText('原複製已安全停止；晚到請求不會建立願望。');expect(writes()).toHaveLength(1);expect(writes()[0][0]).toContain('/clone-receipts/'+marker.clientRequestId+'/abandon');expect(JSON.parse(writes()[0][1].body)).toEqual({sourceItemId:4,targetWishlistId:2});expect(saved.size).toBe(1);
  });
  it('recognizes a historical created-and-later-deleted clone without recreating it',async()=>{
    identity.user.id=7;const marker={version:1,id:1,kind:'CLONE',itemId:4,targetWishlistId:2,clientRequestId:'11111111-1111-4111-8111-111111111111',localOperationId:'22222222-2222-4222-8222-222222222222'};saved.set('7.legacy-detail-operation',JSON.stringify(marker));fetcher.mockImplementation(async url=>response(String(url).includes('/clone-receipts/')?receipt(marker,{deleted:true,resource:null}):row));mount();fireEvent.click(await screen.findByRole('button',{name:'查核原願望複製'}));await screen.findByText('原複製曾建立，但願望後來已刪除；不會重新建立。');expect(writes()).toHaveLength(0);
  });
  it.each([{sourceItemId:99},{targetWishlistId:99},{resource:{id:99,wishlistId:2}}])('rejects a mismatched clone receipt and preserves its identity %#',async override=>{
    identity.user.id=7;const marker={version:1,id:1,kind:'CLONE',itemId:4,targetWishlistId:2,clientRequestId:'11111111-1111-4111-8111-111111111111',localOperationId:'22222222-2222-4222-8222-222222222222'};saved.set('7.legacy-detail-operation',JSON.stringify(marker));fetcher.mockImplementation(async url=>response(String(url).includes('/clone-receipts/')?receipt(marker,override):row));mount();fireEvent.click(await screen.findByRole('button',{name:'查核原願望複製'}));await screen.findByText(/尚未取得原複製回執/);expect(saved.size).toBe(1);expect(store.clear).not.toHaveBeenCalled();expect(writes()).toHaveLength(0);
  });
  it('rejects wrong-owner target reads and allows a fresh read without a false empty state',async()=>{
    identity.user.id=7;let good=false;fetcher.mockImplementation(async url=>response(String(url).endsWith('/wishlists')?[{...destination(),userId:good?7:42}]:row));mount();const button=await screen.findByRole('button',{name:'加入我的清單 合成願望'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);await screen.findByText('尚未確認我的清單；請重試讀取。');expect(screen.queryByText('尚無可用的本人清單。')).not.toBeInTheDocument();good=true;fireEvent.click(screen.getByRole('button',{name:'重新讀取我的清單'}));await screen.findByRole('radio',{name:'合成目標清單 · 0/2'});expect(writes()).toHaveLength(0);
  });
  it('keeps confirmed clone creation when local cleanup fails and only cleans its marker again',async()=>{
    identity.user.id=7;store.clear.mockRejectedValue(new Error('synthetic quota'));fetcher.mockImplementation(async (url,init)=>response(init?.method==='POST'?cloneAck(JSON.parse(init.body)):String(url).endsWith('/wishlists')?[destination()]:row));mount();await dispatchClone();await screen.findByText(/後台已確認操作，但本機標記未清理/);store.clear.mockImplementation(async key=>{saved.delete(key);return true;});fireEvent.click(screen.getByRole('button',{name:'清理已確認操作的本機標記'}));await waitFor(()=>expect(saved.size).toBe(0));expect(writes()).toHaveLength(1);
  });
  it('ignores a late clone response after account departure and retains the original account marker',async()=>{
    identity.user.id=7;let finish!:(value:unknown)=>void,body!:Record<string,unknown>;fetcher.mockImplementation((url,init)=>init?.method==='POST'?new Promise(resolve=>{finish=resolve;body=JSON.parse(init.body);}):Promise.resolve(response(String(url).endsWith('/wishlists')?[destination()]:row)));const view=mount();await dispatchClone();await waitFor(()=>expect(finish).toBeDefined());identity.user.id=42;identity.token='synthetic-b';view.rerender(tree());await screen.findByRole('button',{name:'編輯清單'});await act(async()=>finish(response(cloneAck(body))));expect(screen.queryByText('願望複製已確認。')).not.toBeInTheDocument();expect(saved.has('7.legacy-detail-operation')).toBe(true);expect(store.clear).not.toHaveBeenCalled();
  });
  it('names the item deletion confirmation, traps focus and cancels without a DELETE',async()=>{
    mount();const dialog=await details();await waitFor(()=>expect(within(dialog).getByRole('button',{name:'刪除願望'})).toBeEnabled());fireEvent.click(within(dialog).getByRole('button',{name:'刪除願望'}));const confirmation=screen.getByRole('dialog',{name:'刪除願望 · 合成願望'});expect(confirmation).toContainElement(document.activeElement as HTMLElement);fireEvent.click(within(confirmation).getByRole('button',{name:'取消'}));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(writes()).toHaveLength(0);
  });
  it('requires exact additive item deletion ACK and preserves the original item for a message-only reply',async()=>{
    fetcher.mockImplementation(async (_url,init)=>response(init?.method==='DELETE'?{message:'Item deleted'}:row));mount();const button=await screen.findByRole('button',{name:'刪除願望 合成願望'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);fireEvent.click(within(screen.getByRole('dialog',{name:'刪除願望 · 合成願望'})).getByRole('button',{name:'刪除願望'}));await screen.findByText(/結果尚未確認/);expect(screen.getByRole('heading',{name:'合成願望'})).toBeInTheDocument();expect(saved.size).toBe(1);expect(writes()).toHaveLength(1);
  });
  it('accepts exact list deletion after commit and provides explicit dashboard navigation',async()=>{
    fetcher.mockImplementation(async (_url,init)=>response(init?.method==='DELETE'?{id:1,deleted:true,message:'Wishlist deleted successfully'}:row));mount();const button=await screen.findByRole('button',{name:'刪除清單'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);fireEvent.click(within(screen.getByRole('dialog',{name:'刪除清單 · 合成清單'})).getByRole('button',{name:'刪除清單'}));await screen.findByText('已確認刪除清單。');await waitFor(()=>expect(saved.size).toBe(0));expect(screen.getByRole('link',{name:'返回我的清單'})).toHaveAttribute('href','/dashboard');expect(writes()).toHaveLength(1);
  });
  it('lets an unknown list deletion read current 404 without claiming historical success or resending DELETE',async()=>{
    const marker={version:1,id:1,kind:'DELETE_LIST',localOperationId:'11111111-1111-4111-8111-111111111111'};saved.set('42.legacy-detail-operation',JSON.stringify(marker));fetcher.mockResolvedValue(response({},404));mount();fireEvent.click(await screen.findByRole('button',{name:'讀取目前清單狀態'}));await screen.findByText(/這不是原操作的歷史回執/);expect(screen.queryByText('已確認刪除清單。')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'已讀目前狀態，清理標記並恢復操作'}));await waitFor(()=>expect(saved.size).toBe(0));expect(writes()).toHaveLength(0);
  });
  it('omits unsafe links and offers an accurately named shopping search fallback in English',async()=>{
    window.localStorage.setItem('user-locale','en-US');fetcher.mockResolvedValue(response({...row,items:[{...item,link:'javascript:alert(1)',aiLink:'https://user:pass@example.com/'}]}));mount();fireEvent.click(await screen.findByRole('button',{name:'View wish 合成願望'}));const dialog=screen.getByRole('dialog',{name:'合成願望'});expect(within(dialog).queryByRole('link',{name:'Reference product link'})).not.toBeInTheDocument();expect(within(dialog).queryByRole('link',{name:'AI reference product'})).not.toBeInTheDocument();expect(within(dialog).getByRole('link',{name:'Search for product'})).toHaveAttribute('href',expect.stringContaining('https://www.google.com/search?tbm=shop'));expect(within(dialog).getByRole('button',{name:'Edit wish'})).toBeInTheDocument();
  });
});
