import express from 'express';
import request from 'supertest';
import { randomUUID } from 'node:crypto';
import jwt from 'jsonwebtoken';
import prisma from '../../lib/prisma';
import listings from '../../routes/listingRoutes';
import chat from '../../routes/chatRoutes';
import { sendEmail } from '../../lib/emailService';
jest.mock('../../lib/emailService', () => ({ sendEmail: jest.fn(async () => ({ success: false })) }));
require('../../../../scripts/assert-test-database.cjs').assertTestDatabase(process.env.TEST_DATABASE_URL);
if (process.env.DATABASE_URL !== process.env.TEST_DATABASE_URL) throw Error('Use identical isolated test DB');
const app = express(); app.use(express.json()); app.use('/listings', listings); app.use('/chat', chat);
const secret = 'synthetic-apple-remediation-tests', previousSecret = process.env.JWT_SECRET;
let owner: number, other: number, outsider: number, listingId: string, roomId: string, messageId: string;
const submissions: string[] = [];
const auth = (id: number) => 'Bearer ' + jwt.sign({ id, authVersion: 0 }, secret, { algorithm: 'HS256' });
beforeAll(async () => {
  process.env.JWT_SECRET = secret;
  [owner, other, outsider] = await Promise.all(['owner', 'other', 'outsider'].map(async role => (await prisma.user.create({ data: { phoneNumber: 'apple-review-' + role + randomUUID(), password: 'fixture', isEmailVerified: true } })).id));
  listingId = (await prisma.listing.create({ data: { ownerUserId: owner, clientListingId: randomUUID(), requestHash: 'fixture', title: 'Synthetic review item', description: 'Only synthetic evidence', category: 'books', price: 1, currency: 'TWD', status: 'ACTIVE', publishedAt: new Date(), expiresAt: new Date(Date.now() + 86400000), deliveryMethods: ['MEETUP'], location: { create: { county: '臺北市', district: '中正區', publicLatitude: 25.03, publicLongitude: 121.51, precisionMeters: 2200 } } } })).id;
  roomId = (await prisma.conversation.create({ data: { listingId, buyerUserId: other, sellerUserId: owner, participants: { create: [{ userId: owner, role: 'SELLER' }, { userId: other, role: 'BUYER' }] } } })).id;
  messageId = (await prisma.message.create({ data: { conversationId: roomId, senderUserId: other, clientMessageId: randomUUID(), sequence: 1, text: 'Synthetic report target' } })).id;
});
afterAll(async () => {
  await prisma.feedback.deleteMany({ where: { userId: { in: [owner, other, outsider] } } });
  await prisma.submissionReceipt.deleteMany({ where: { clientSubmissionId: { in: submissions } } });
  await prisma.user.deleteMany({ where: { id: { in: [owner, other, outsider] } } });
  await prisma.conversation.deleteMany({ where: { id: roomId } });
  if (previousSecret === undefined) delete process.env.JWT_SECRET; else process.env.JWT_SECRET = previousSecret;
  await prisma.$disconnect();
});
it('allows declining map display, checks in only by the verified owner, and never renews on reads or extension', async () => {
  const browse = () => request(app).get('/listings').query({ bbox: '121,24,122,26' });
  const hidden=await browse();expect(hidden.headers['cache-control']).toBe('no-store');expect(hidden.body.items).toHaveLength(0);
  const put = (id: number, body: object) => request(app).put('/listings/' + listingId + '/map-presence').set('Authorization', auth(id)).send(body);
  expect((await put(outsider, { expectedVersion: 1, display: true, consentToMap: true })).status).toBe(404);
  expect((await put(owner, { expectedVersion: 1, display: true, consentToMap: false })).status).toBe(400);
  const checked = await put(owner, { expectedVersion: 1, display: true, consentToMap: true }); expect(checked.status).toBe(200);
  expect(Date.parse(checked.body.mapVisibleUntil) - Date.now()).toBeLessThanOrEqual(3600000);
  expect((await browse()).body.items).toHaveLength(1);
  await request(app).get('/listings/' + listingId);
  expect((await prisma.listing.findUniqueOrThrow({ where: { id: listingId } })).mapVisibleUntil?.toISOString()).toBe(checked.body.mapVisibleUntil);
  const off = await put(owner, { expectedVersion: 2, display: false }); expect(off.status).toBe(200); expect(off.body.mapVisibleUntil).toBeNull();
  expect((await browse()).body.items).toHaveLength(0);
  expect((await request(app).get('/listings/' + listingId)).status).toBe(200);
  expect((await put(owner, { expectedVersion: 2, display: true, consentToMap: true })).status).toBe(409);
  await prisma.listing.update({ where: { id: listingId }, data: { mapVisibleUntil: new Date(Date.now() - 1) } });
  expect((await browse()).body.items).toHaveLength(0);
  const expiryDate = new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10);
  expect((await request(app).post('/listings/' + listingId + '/extend').set('Authorization', auth(owner)).send({ expectedVersion: 3, expiryDate })).status).toBe(200);
  expect((await browse()).body.items).toHaveLength(0);
});
it('persists one real human-review report despite notification failure; both trading roles can report, with private receipts', async () => {
  const clientReportId = randomUUID(); submissions.push(clientReportId);
  const body = { clientReportId, reportedUserId: other, reason: 'OBJECTIONABLE', details: 'Synthetic evidence', messageId };
  const post = (id: number, b: Record<string, unknown> = body) => request(app).post('/chat/conversations/' + roomId + '/reports').set('Authorization', auth(id)).send(b);
  expect((await post(outsider)).status).toBe(404);
  const accepted = await post(owner); expect(accepted.status).toBe(201); expect(accepted.body.received).toBe(true);
  expect((await post(owner)).body.receiptId).toBe(accepted.body.receiptId);
  expect((await post(owner, { ...body, details: 'Changed evidence' })).status).toBe(409);
  expect(await prisma.feedback.count({ where: { userId: owner } })).toBe(1);
  expect(sendEmail).toHaveBeenCalledTimes(1);
  const receipt = (id: number) => request(app).get('/chat/conversations/' + roomId + '/reports/' + clientReportId).set('Authorization', auth(id));
  expect((await receipt(outsider)).status).toBe(404); expect((await receipt(other)).status).toBe(404);
  const got = await receipt(owner); expect(got.headers['cache-control']).toBe('private, no-store'); expect(JSON.stringify(got.body)).not.toContain('Synthetic evidence');
  const buyerId = randomUUID(); submissions.push(buyerId);
  expect((await post(other, { ...body, clientReportId: buyerId, reportedUserId: owner, messageId: null })).status).toBe(201);
});
