import express from 'express';
import request from 'supertest';
import prisma from '../../lib/prisma';
import {createSourceLeadRoutes,createSourceLeadAdmin} from '../../routes/sourceLeadRoutes';
import {countyIllustration,COUNTY_ILLUSTRATION_SOURCE} from '../../lib/sourceCountyIllustration';
const run=process.env.TEST_DATABASE_URL?describe:describe.skip;
run('county illustration safe public opt-in with real isolated database',()=>{
 const prefix='SYNTHETIC-COUNTY-OPTIN',admin='synthetic-counties-only';let verified=false,id:string;
 const body=()=>{const county='新北市',point=countyIllustration(county)!,url='https://www.facebook.com/groups/123456789/posts/987654321';return {archiveItemId:prefix,libraryFileId:'libfile_'+'a'.repeat(32),archiveVersion:1,archiveSha256:'b'.repeat(64),title:'合成候選椅',summary:'來源線索，是否在售待確認。',canonicalUrl:url,county,district:'板橋區',publicPlaceName:county+'概略示意位置',publicAddress:county+'（概略位置，非取貨點）',latitude:point.latitude,longitude:point.longitude,postedEarliestAt:new Date(Date.now()-86400000).toISOString(),postedLatestAt:new Date(Date.now()-86400000).toISOString(),checkedAt:new Date().toISOString(),evidence:{sourceUrl:url,sourcePublic:true,publicSourceRef:'review:synthetic-public',dateRef:'review:synthetic-date',locationRef:'review:synthetic-county',coordinateRef:'source:post-dataset-25489',locationSourceUrl:url,coordinateSourceUrl:COUNTY_ILLUSTRATION_SOURCE,publicPlace:false,locationType:'COUNTY_ILLUSTRATION',sourceMeetingPointConfirmed:false,independentlyReviewed:true,selfWrittenSummary:true,noCopiedTextOrImages:true,noPrivateData:true,reviewRef:'review:synthetic-approved',countyIllustration:{county,sourceUrl:url,sourceCountyRef:'review:synthetic-original-county',representativeKey:point.key,approvalRef:'consent:synthetic-county-only'}}};};
 const app=express();app.use(express.json());app.use('/leads',createSourceLeadRoutes());app.use('/admin',createSourceLeadAdmin(()=>admin));
 let flag:string|undefined;
 beforeAll(()=>{require('../../../../scripts/assert-test-database.cjs').assertTestDatabase(process.env.DATABASE_URL);verified=true;flag=process.env.SOURCE_LEADS_PUBLIC_ENABLED;process.env.SOURCE_LEADS_PUBLIC_ENABLED='1';});
 afterAll(async()=>{if(!verified)return;await prisma.externalSourceLead.deleteMany({where:{archiveItemId:{in:[prefix,prefix+'-CITY']}}});if(flag===undefined)delete process.env.SOURCE_LEADS_PUBLIC_ENABLED;else process.env.SOURCE_LEADS_PUBLIC_ENABLED=flag;await prisma.$disconnect();});
 test('dry run is read-only, repeated same archive cannot duplicate, no qualified stock created',async()=>{const b=body();const dry=await request(app).post('/admin/import').set('x-admin-key',admin).send({items:[b],dryRun:true});expect(dry.status).toBe(200);expect(dry.body.persistedCount).toBe(0);const before=await prisma.listing.count();const first=await request(app).post('/admin/import').set('x-admin-key',admin).send({items:[b],dryRun:false});expect(first.status).toBe(200);id=first.body.ids[0];const again=await request(app).post('/admin/import').set('x-admin-key',admin).send({items:[b],dryRun:false});expect(again.body.ids).toEqual([id]);expect(await prisma.externalSourceLead.count({where:{archiveItemId:prefix}})).toBe(1);expect(await prisma.listing.count()).toBe(before);});
 test('old internal clients cannot receive mislabeled county pins; opted-in Web sees safe metadata',async()=>{expect((await request(app).get('/leads')).body.items.some((x:any)=>x.id===id)).toBe(false);expect((await request(app).get('/leads/'+id)).status).toBe(404);const page=await request(app).get('/leads?approximate=1&presentation=1');expect(page.status).toBe(200);const item=page.body.items.find((x:any)=>x.id===id);expect(item.locationPrecision).toBe('COUNTY_ILLUSTRATION');expect(item.qualifiedSupply).toBe(false);expect(item.stockStatus).toBe('UNKNOWN');expect(item.checkoutEnabled).toBe(false);expect(item.publicAddress).toBe('新北市（概略位置，非取貨點）');expect(item).not.toHaveProperty('evidence');expect((await request(app).get('/leads/'+id+'?approximate=1')).status).toBe(200);expect((await request(app).get('/leads?approximate=wrong')).status).toBe(409);});
 test('city-only Taipei persists explicit unknown district without inventory or false pickup',async()=>{const b=body(),county='臺北市',point=countyIllustration(county)!;const city={...b,archiveItemId:prefix+'-CITY',county,district:'行政區未明示',publicPlaceName:county+'概略示意位置',publicAddress:county+'（概略位置，非取貨點）',latitude:point.latitude,longitude:point.longitude,evidence:{...b.evidence,countyIllustration:{...b.evidence.countyIllustration,county,representativeKey:point.key,districtStatus:'UNKNOWN'}}};const before=await prisma.listing.count();const dry=await request(app).post('/admin/import').set('x-admin-key',admin).send({items:[city],dryRun:true});expect(dry.status).toBe(200);expect(await prisma.externalSourceLead.count({where:{archiveItemId:city.archiveItemId}})).toBe(0);const applied=await request(app).post('/admin/import').set('x-admin-key',admin).send({items:[city],dryRun:false});expect(applied.status).toBe(200);const id=applied.body.ids[0];expect((await request(app).get('/leads/'+id)).status).toBe(404);const detail=await request(app).get('/leads/'+id+'?approximate=1');expect(detail.body.district).toBe('行政區未明示');expect(detail.body.stockStatus).toBe('UNKNOWN');expect(detail.body.qualifiedSupply).toBe(false);expect(detail.body.checkoutEnabled).toBe(false);expect(await prisma.listing.count()).toBe(before);});
});
