import {prepareSourcePhotoImport} from '../../lib/sourcePhotoImport';
import express from 'express';
import request from 'supertest';
import { createServer, type Server } from 'http';
import prisma from '../../lib/prisma';
import { createSourceLeadRoutes, createSourceLeadAdmin } from '../../routes/sourceLeadRoutes';
import { digest } from '../../lib/sourceLeadRules';
const run = !!process.env.TEST_DATABASE_URL ? describe : describe.skip;
run('independent source lead map -> inquiry (synthetic local DB)', () => {
    let verifiedDb = false;
    const previousFlag = process.env.SOURCE_LEADS_PUBLIC_ENABLED;
    let server: Server;
    let app: ReturnType<typeof express>, leadId: string, buyer: number, other: number, roomId: string;
    const key = require('crypto').randomUUID(), otherKey = require('crypto').randomUUID(), admin = 'synthetic-lead-admin';
    const body = (id = 'SYNTHETIC-LEAD') => ({ archiveItemId: id, libraryFileId: 'libfile_' + 'a'.repeat(32), archiveVersion: 3, archiveSha256: 'a'.repeat(64), title: '來源線索：合成二手書', summary: '合成測試來源；庫存與交易待確認。', canonicalUrl: 'https://www.facebook.com/groups/123456789/posts/' + id, county: '臺南市', district: '永康區', publicPlaceName: '合成公開面交點', publicAddress: '臺南市永康區合成路123號', latitude: 23.0, longitude: 120.236, postedEarliestAt: new Date(Date.now() - 86400000).toISOString(), postedLatestAt: new Date(Date.now() - 86400000).toISOString(), checkedAt: new Date().toISOString(), evidence: { sourceUrl: 'https://www.facebook.com/groups/123456789/posts/' + id, sourcePublic: true, publicSourceRef: 'self:synthetic-public', dateRef: 'self:synthetic-original-date', locationRef: 'self:synthetic-location', coordinateRef: 'self:synthetic-coordinate', locationSourceUrl: 'https://public.example.invalid/place/qa', coordinateSourceUrl: 'https://public.example.invalid/map/qa', publicPlace: true, locationType: 'PUBLIC_MEETING_POINT', sourceMeetingPointConfirmed: true, independentlyReviewed: true, selfWrittenSummary: true, noCopiedTextOrImages: true, noPrivateData: true, reviewRef: 'self:synthetic-review' } });
    const importLead = (items: any[], dryRun = false) => request(server).post('/admin/import').set('x-admin-key', admin).send({ items, dryRun });
    const open = () => request(server).post('/leads/' + leadId + '/inquiry').set('x-api-key', key).send({});
    const act = (b: any, k = key) => request(server).post('/leads/' + leadId + '/inquiry/' + roomId + '/actions').set('x-api-key', k).send(b);
    beforeAll(async () => { require('../../../../scripts/assert-test-database.cjs').assertTestDatabase(process.env.DATABASE_URL); verifiedDb = true; process.env.SOURCE_LEADS_PUBLIC_ENABLED = '1'; buyer = (await prisma.user.create({ data: { phoneNumber: 'synthetic-lead-buyer', password: 'unused', apiKey: key } })).id; other = (await prisma.user.create({ data: { phoneNumber: 'synthetic-lead-other', password: 'unused', apiKey: otherKey } })).id; });
    beforeEach(async () => { app = express(); app.use(express.json()); app.use('/leads', createSourceLeadRoutes()); app.use('/admin', createSourceLeadAdmin(() => admin)); server=createServer(app); await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>{server.removeListener('error',reject);resolve();});}); });
    afterEach(async()=>{if(server?.listening)await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));});
    afterAll(async () => { if (!verifiedDb) return; if (previousFlag === undefined) delete process.env.SOURCE_LEADS_PUBLIC_ENABLED; else process.env.SOURCE_LEADS_PUBLIC_ENABLED = previousFlag; await prisma.sourceLeadInquiry.deleteMany({ where: { buyerUserId: { in: [buyer, other] } } }); await prisma.externalSourceLead.deleteMany({ where: { archiveItemId: { startsWith: 'SYNTHETIC-' } } }); await prisma.user.deleteMany({ where: { id: { in: [buyer, other] } } }); await prisma.$disconnect(); });
    test('no admin, missing original date/public point/copied text/private contact: atomic reject; no inventory writes', async () => {
        expect((await request(server).post('/admin/import').send({ items: [body()], dryRun: false })).status).toBe(401);
        const invalid = [{ ...body(), postedEarliestAt: new Date(Date.now() - 100 * 86400000).toISOString() }, { ...body(), publicAddress: '臺南市永康區' }, { ...body(), summary: '聯絡 example@example.com' }, { ...body(), imageUrl: 'https://example.invalid/copied.jpg' }, { ...body(), evidence: { ...body().evidence, noCopiedTextOrImages: false } }, { ...body(), evidence: { ...body().evidence, sourcePublic: false } }, { ...body(), evidence: { ...body().evidence, sourceUrl: 'https://www.facebook.com/groups/other/posts/other' } }];
        for (const row of invalid)
            expect((await importLead([body('SYNTHETIC-GOOD'), row])).status).toBe(409);
        expect(await prisma.externalSourceLead.count()).toBe(0);
        expect(await prisma.listing.count()).toBe(0);
        expect((await importLead([body()], true)).body.persistedCount).toBe(0);
        expect(await prisma.externalSourceLead.count()).toBe(0);
    });
    test('public coordinate notes and place fields cannot expose private phone/email/LINE', async () => {
        for (const value of ['0935123456', 'seller@example.com', 'LINE ID:abc']) {
            const note = { ...body(), evidence: { ...body().evidence, publicFacts: { priceText: '原帖價格待確認', priceUnitStatus: 'unknown', currencyStatus: 'unknown', sourceAccessNotice: '可能需登入', originalDateLabel: '原始日期區間', locationRelation: '公共面交點非現貨位置', coordinateQualityNotes: [value] } } };
            expect((await importLead([note])).status).toBe(409);
            expect((await importLead([{ ...body(), publicPlaceName: value }])).status).toBe(409);
        }
    });
    test('published research lead needs no stock/images/rights; white-list DTO and bbox separate from inventory', async () => {
        const r = await importLead([body()]);
        expect(r.status).toBe(200);
        leadId = r.body.ids[0];
        expect(r.body.qualifiedSupplyCount).toBe(0);
        const pub = await request(server).get('/leads/' + leadId);
        expect(pub.status).toBe(200);
        expect(pub.body.stockStatus).toBe('UNKNOWN');
        expect(pub.body.checkoutEnabled).toBe(false);
        expect(pub.body).not.toHaveProperty('evidence');
        expect(pub.body).not.toHaveProperty('imageUrl');
        expect(pub.body).not.toHaveProperty('sellerRoute');
        expect((await request(server).get('/leads?bbox=120.23,22.99,120.24,23.01')).body.items).toHaveLength(1);
        expect((await request(server).get('/leads?bbox=121,25,122,26')).body.items).toHaveLength(0);
        expect((await importLead([{ ...body(), archiveVersion: 2 }])).body.errorCode).toBe('STALE_OR_CONFLICTING_LEAD');
        expect((await importLead([{ ...body(), summary: 'same version changed content' }])).status).toBe(409);
    });
    test('GET before and after opening reads only the authenticated buyer without allocating receipts', async () => {
        const before = await prisma.sourceLeadInquiry.count();
        for (let i = 0; i < 2; i++) {
            const result = await request(server).get('/leads/' + leadId + '/inquiry').set('x-api-key', key);
            expect(result.status).toBe(200);
            expect(result.body).toBeNull();
        }
        expect(await prisma.sourceLeadInquiry.count()).toBe(before);
        const opened = await open();
        expect(opened.status).toBe(200);
        const read = await request(server).get('/leads/' + leadId + '/inquiry').set('x-api-key', key);
        expect(read.body.id).toBe(opened.body.id);
        expect(read.body.events).toEqual([]);
        expect((await request(server).get('/leads/' + leadId + '/inquiry').set('x-api-key', otherKey)).body).toBeNull();
        expect(await prisma.sourceLeadInquiry.count()).toBe(before + 1);
    });
    test('single buyer room, ownership, exact request replay; consent freezes question IDs; waiting is not sent', async () => {
        const rooms = await Promise.all([open(), open()]);
        expect(rooms.every(r => r.status === 200)).toBe(true);
        expect(rooms[0].body.id).toBe(rooms[1].body.id);
        roomId = rooms[0].body.id;
        const b = { requestId: require('crypto').randomUUID(), action: 'ASK', text: '想詢問取貨方式' };
        expect((await act(b, otherKey)).status).toBe(409);
        const ask = await act(b);
        expect(ask.status).toBe(200);
        expect((await act(b)).body.events).toHaveLength(1);
        expect((await act({ ...b, text: 'different' })).status).toBe(409);
        const invalidConsent=await act({ requestId: require('crypto').randomUUID(), action: 'CONSENT', consent: true, transferHash: '0'.repeat(64) });expect({status:invalidConsent.status,error:invalidConsent.body.errorCode}).toEqual({status:409,error:'CONSENT_SNAPSHOT_MISMATCH'});
        const consent = await act({ requestId: require('crypto').randomUUID(), action: 'CONSENT', consent: true, transferHash: ask.body.transferHash });
        expect(consent.body.state).toBe('WAITING_ROUTE');
        expect(consent.body.delivered).toBe(false);
        expect(consent.body.routeVerified).toBe(false);
        expect((await act({ requestId: require('crypto').randomUUID(), action: 'ASK', text: '後補私人聯絡' })).status).toBe(409);
        expect((await request(server).post('/admin/inquiries/' + roomId + '/prepare-transfer').set('x-admin-key', admin).send({ requestId: require('crypto').randomUUID() })).status).toBe(409);
    });
    test('verified original seller UI route only; delivery binds exact route/consent/source and receipt; replay', async () => {
        const lead = await prisma.externalSourceLead.findUniqueOrThrow({ where: { id: leadId } });
        const route = { leadId, sourceUrl: lead.canonicalUrl, contentHash: lead.contentHash, channel: 'FACEBOOK_UI', publicRouteUrl: 'https://www.facebook.com/synthetic.seller', identityEvidenceRef: 'self:synthetic-seller', routeEvidenceRef: 'self:synthetic-ui-route', confirmOriginalSeller: true };
        const routePost = (b: any) => request(server).post('/admin/' + leadId + '/seller-route').set('x-admin-key', admin).send(b);
        expect((await routePost({ ...route, publicRouteUrl: lead.canonicalUrl })).status).toBe(409);
        expect((await routePost(route)).status).toBe(200);
        const transfer = await request(server).post('/admin/inquiries/' + roomId + '/prepare-transfer').set('x-admin-key', admin).send({ requestId: require('crypto').randomUUID() });
        expect(transfer.status).toBe(200);
        expect((await request(server).get('/admin/inquiries/' + roomId + '/transfer-preflight').set('x-admin-key', admin)).status).toBe(200);
        expect(transfer.body.snapshot.questions).toHaveLength(1);
        const proof = { requestId: require('crypto').randomUUID(), reservationId: transfer.body.reservation.id, payloadHash: transfer.body.reservation.payloadHash, routeHash: digest(transfer.body.route), leadId, sourceUrl: lead.canonicalUrl, channel: 'FACEBOOK_UI', receiptRef: 'self:synthetic-not-real-send', sentAt: new Date().toISOString(), outcome: 'CONFIRMED_SENT' };
        const deliver = (b: any) => request(server).post('/admin/inquiries/' + roomId + '/delivery').set('x-admin-key', admin).send(b);
        expect((await deliver({ ...proof, routeHash: '0'.repeat(64) })).status).toBe(409);
        await request(server).post('/admin/' + leadId + '/withdraw').set('x-admin-key', admin).send({ reasonRef: 'self:synthetic-reserved-withdraw' });
        const delivered = await deliver(proof);
        expect(delivered.status).toBe(200);
        expect(delivered.body.state).toBe('DELIVERY_REQUIRES_REVIEW');
        expect(delivered.body.delivery.verification).toBe('MANUAL_UI_RECEIPT');
        expect(delivered.body.delivery).not.toHaveProperty('receiptRef');
        expect(delivered.body.orderCreated).toBe(false);
        expect((await deliver(proof)).status).toBe(200);
        expect((await deliver({ ...proof, requestId: require('crypto').randomUUID() })).status).toBe(409);
    });
    test('cancel during reserved transfer blocks preflight; confirmed actual receipt stays auditable; feature OFF blocks new transfer', async () => {
        const added = await importLead([body('SYNTHETIC-RACE')]), id = added.body.ids[0];
        const opened = await request(server).post('/leads/' + id + '/inquiry').set('x-api-key', otherKey).send({});
        const rid = opened.body.id, actionPath = '/leads/' + id + '/inquiry/' + rid + '/actions';
        const ask = await request(server).post(actionPath).set('x-api-key', otherKey).send({ requestId: require('crypto').randomUUID(), action: 'ASK', text: '詢問交付' });
        await request(server).post(actionPath).set('x-api-key', otherKey).send({ requestId: require('crypto').randomUUID(), action: 'CONSENT', consent: true, transferHash: ask.body.transferHash });
        const lead = await prisma.externalSourceLead.findUniqueOrThrow({ where: { id } });
        await request(server).post('/admin/' + id + '/seller-route').set('x-admin-key', admin).send({ leadId: id, sourceUrl: lead.canonicalUrl, contentHash: lead.contentHash, channel: 'FACEBOOK_UI', publicRouteUrl: 'https://www.facebook.com/synthetic.seller', identityEvidenceRef: 'self:synthetic-seller', routeEvidenceRef: 'self:synthetic-route', confirmOriginalSeller: true });
        process.env.SOURCE_LEADS_PUBLIC_ENABLED = '0';
        expect((await request(server).post('/admin/inquiries/' + rid + '/prepare-transfer').set('x-admin-key', admin).send({ requestId: require('crypto').randomUUID() })).status).toBe(409);
        process.env.SOURCE_LEADS_PUBLIC_ENABLED = '1';
        const reserved = await request(server).post('/admin/inquiries/' + rid + '/prepare-transfer').set('x-admin-key', admin).send({ requestId: require('crypto').randomUUID() });
        expect(reserved.status).toBe(200);
        expect((await request(server).post(actionPath).set('x-api-key', otherKey).send({ requestId: require('crypto').randomUUID(), action: 'CANCEL' })).body.state).toBe('CANCEL_REQUESTED');
        expect((await request(server).get('/admin/inquiries/' + rid + '/transfer-preflight').set('x-admin-key', admin)).status).toBe(409);
        const v = reserved.body.reservation;
        const late = await request(server).post('/admin/inquiries/' + rid + '/delivery').set('x-admin-key', admin).send({ requestId: require('crypto').randomUUID(), reservationId: v.id, payloadHash: v.payloadHash, routeHash: v.routeHash, leadId: id, sourceUrl: lead.canonicalUrl, channel: v.channel, receiptRef: 'self:synthetic-race-receipt', sentAt: new Date().toISOString(), outcome: 'CONFIRMED_SENT' });
        expect(late.status).toBe(200);
        expect(late.body.state).toBe('DELIVERY_REQUIRES_REVIEW');
        expect(late.body.delivered).toBe(true);
        expect(late.body.orderCreated).toBe(false);
        await request(server).post('/admin/' + id + '/withdraw').set('x-admin-key', admin).send({ reasonRef: 'self:synthetic-race-withdraw' });
    });
    test('contact send atomically scopes consent, reaches admin inbox and never claims seller delivery', async()=>{
        const imported=await importLead([body('SYNTHETIC-CONTACT')]); const lid=imported.body.ids[0];
        const opened=await request(server).post('/leads/'+lid+'/inquiry?presentation=1').set('x-api-key',key).send({});
        const rid=opened.body.id,b={requestId:require('crypto').randomUUID(),action:'ASK',text:'請確認是否仍在售及取貨方式',consent:true,transferHash:opened.body.transferHash};
        const send=()=>request(server).post('/leads/'+lid+'/inquiry/'+rid+'/actions?presentation=1').set('x-api-key',key).send(b);
        const result=await send();expect(result.status).toBe(200);expect(result.body.state).toBe('WAITING_ROUTE');expect(result.body.delivered).toBe(false);expect(result.body.routeVerified).toBe(false);expect(result.body.orderCreated).toBe(false);
        expect((await send()).body.events).toHaveLength(1);
        const inbox=await request(server).get('/admin/inquiries').set('x-admin-key',admin); const item=inbox.body.items.find((r:any)=>r.id===rid);expect(item.source.id).toBe(lid);expect(item.source.archiveItemId).toBe('SYNTHETIC-CONTACT');expect(item.events[0].text).toBe(b.text);
        const own=await request(server).get('/leads/inquiries/mine').set('x-api-key',key);expect(own.body.items.some((r:any)=>r.id===rid)).toBe(true);
        const foreign=await request(server).get('/leads/inquiries/mine').set('x-api-key',otherKey);expect(foreign.body.items.some((r:any)=>r.id===rid)).toBe(false);
        const blocked=await request(server).post('/admin/inquiries/'+rid+'/prepare-transfer').set('x-admin-key',admin).send({requestId:require('crypto').randomUUID()});expect(blocked.status).toBe(409);
        await request(server).post('/leads/'+lid+'/inquiry/'+rid+'/actions').set('x-api-key',key).send({requestId:require('crypto').randomUUID(),action:'CANCEL'});
        expect((await request(server).post('/admin/inquiries/'+rid+'/prepare-transfer').set('x-admin-key',admin).send({requestId:require('crypto').randomUUID()})).status).toBe(409);
    });
    test('private exact receipts survive withdrawal and disabled sources without allocating or exposing another buyer',async()=>{
        const lid=(await importLead([body('SYNTHETIC-RECEIPT')])).body.ids[0];
        const opened=(await request(server).post('/leads/'+lid+'/inquiry').set('x-api-key',key).send({})).body;
        const actions='/leads/'+lid+'/inquiry/'+opened.id+'/actions',unknown=require('crypto').randomUUID();
        const snapshot=await prisma.sourceLeadInquiry.findUniqueOrThrow({where:{id:opened.id}});
        const empty=await request(server).get(actions+'/'+unknown).set('x-api-key',key);expect(empty.status).toBe(200);expect(empty.body).toBeNull();
        expect(await prisma.sourceLeadInquiry.findUniqueOrThrow({where:{id:opened.id}})).toEqual(snapshot);
        const ask={requestId:require('crypto').randomUUID(),action:'ASK',text:'原問題完整回執',consent:true,transferHash:opened.transferHash};
        expect((await request(server).post(actions).set('x-api-key',key).send(ask)).status).toBe(200);
        const endpoint=actions+'/'+ask.requestId,read=await request(server).get(endpoint).set('x-api-key',key);
        expect(read.status).toBe(200);expect(read.headers['cache-control']).toBe('private, no-store');expect(read.body.operation).toEqual(ask);expect(read.body.leadId).toBe(lid);expect(read.body.roomId).toBe(opened.id);expect(read.body.room.delivered).toBe(false);
        expect(Object.keys(read.body).sort()).toEqual(['leadId','operation','room','roomId']);expect(read.body.room).not.toHaveProperty('buyerUserId');expect(read.body.room).not.toHaveProperty('sellerRoute');expect(read.body.room).not.toHaveProperty('evidence');
        expect((await request(server).get(endpoint)).status).toBe(401);expect((await request(server).get(endpoint).set('x-api-key',otherKey)).status).toBe(404);
        expect((await request(server).get(endpoint+'?presentation=1').set('x-api-key',key)).status).toBe(404);
        expect((await request(server).get('/leads/'+leadId+'/inquiry/'+opened.id+'/actions/'+ask.requestId).set('x-api-key',key)).status).toBe(404);
        const foreignRoom=(await request(server).post('/leads/'+lid+'/inquiry').set('x-api-key',otherKey).send({})).body;
        expect((await request(server).get('/leads/'+lid+'/inquiry/'+foreignRoom.id+'/actions/'+ask.requestId).set('x-api-key',otherKey)).body).toBeNull();
        await request(server).post('/admin/'+lid+'/withdraw').set('x-admin-key',admin).send({reasonRef:'self:synthetic-receipt-withdraw'});process.env.SOURCE_LEADS_PUBLIC_ENABLED='0';
        try {
            expect((await request(server).get(endpoint).set('x-api-key',key)).body.operation).toEqual(ask);
            const cancel={requestId:require('crypto').randomUUID(),action:'CANCEL'};expect((await request(server).post(actions).set('x-api-key',key).send(cancel)).body.state).toBe('CANCELLED');
            const confirmed=await request(server).get(actions+'/'+cancel.requestId).set('x-api-key',key);expect(confirmed.body.operation).toEqual(cancel);expect(confirmed.body.room.state).toBe('CANCELLED');
            const before=await prisma.sourceLeadInquiry.findUniqueOrThrow({where:{id:opened.id}});expect((await request(server).post(actions).set('x-api-key',key).send({...ask,requestId:require('crypto').randomUUID()})).status).toBe(409);
            expect((await request(server).get(endpoint).set('x-api-key',key)).body.operation).toEqual(ask);expect(await prisma.sourceLeadInquiry.findUniqueOrThrow({where:{id:opened.id}})).toEqual(before);
        }finally{process.env.SOURCE_LEADS_PUBLIC_ENABLED='1';}
    });
    test('one-step consent rejects multi-device changed history and private contact details',async()=>{
        const imported=await importLead([body('SYNTHETIC-CONTACT-RACE')]);expect({status:imported.status,error:imported.body.errorCode}).toEqual({status:200,error:undefined});const lid=imported.body.ids[0];const room=(await request(server).post('/leads/'+lid+'/inquiry').set('x-api-key',key).send({})).body;
        const path='/leads/'+lid+'/inquiry/'+room.id+'/actions';
        await request(server).post(path).set('x-api-key',key).send({requestId:require('crypto').randomUUID(),action:'ASK',text:'另一裝置問題'});
        const changed=await request(server).post(path).set('x-api-key',key).send({requestId:require('crypto').randomUUID(),action:'ASK',text:'購買意願',consent:true,transferHash:room.transferHash});expect(changed.body.errorCode).toBe('CONSENT_SNAPSHOT_MISMATCH');
        const latest=(await request(server).get('/leads/'+lid+'/inquiry').set('x-api-key',key)).body;
        const privateMsg=await request(server).post(path).set('x-api-key',key).send({requestId:require('crypto').randomUUID(),action:'ASK',text:'請回覆 seller@example.com',consent:true,transferHash:latest.transferHash});expect(privateMsg.body.errorCode).toBe('PRIVATE_CONTACT_NOT_FORWARDED');
        expect((await request(server).get('/leads/'+lid+'/inquiry').set('x-api-key',key)).body.events).toHaveLength(1);
    });
    test('seller reply requires item/post/verified route/actual receipt; repeats cannot cross buyer threads',async()=>{
        const imported=await importLead([body('SYNTHETIC-REPLY')]);const lid=imported.body.ids[0];const l=await prisma.externalSourceLead.findUniqueOrThrow({where:{id:lid}});
        const review={leadId:lid,sourceUrl:l.canonicalUrl,contentHash:l.contentHash,status:'UNAVAILABLE',identityEvidenceRef:'review:synthetic-author-observed',routeEvidenceRef:'review:synthetic-page-cannot-message',reason:'以品牌粉專核對原賣家訊息入口，平台顯示無法聯絡；未外送。',checkedAt:new Date().toISOString()};
        const reviewPath='/admin/'+lid+'/seller-route-review';
        expect((await request(server).post(reviewPath).send(review)).status).toBe(401);
        expect((await request(server).post(reviewPath).set('x-admin-key',admin).send({...review,status:'VERIFIED'})).status).toBe(409);
        expect((await request(server).post(reviewPath).set('x-admin-key',admin).send({...review,sourceUrl:'https://example.invalid/wrong-post'})).status).toBe(409);
        expect((await request(server).post(reviewPath).set('x-admin-key',admin).send(review)).body.routeVerified).toBe(false);
        const reviewed=(await request(server).get('/leads/'+lid+'?presentation=1')).body;
        expect(reviewed.contactRouting.status).toBe('UNAVAILABLE');expect(reviewed.contactRouting).not.toHaveProperty('identityEvidenceRef');
        const room=(await request(server).post('/leads/'+lid+'/inquiry').set('x-api-key',key).send({})).body;
        await request(server).post('/leads/'+lid+'/inquiry/'+room.id+'/actions').set('x-api-key',key).send({requestId:require('crypto').randomUUID(),action:'ASK',text:'確認現貨',consent:true,transferHash:room.transferHash});
        await request(server).post('/admin/'+lid+'/seller-route').set('x-admin-key',admin).send({leadId:lid,contentHash:l.contentHash,sourceUrl:l.canonicalUrl,channel:'FACEBOOK_UI',publicRouteUrl:'https://m.me/synthetic-seller',identityEvidenceRef:'review:synthetic-identity',routeEvidenceRef:'review:synthetic-route',confirmOriginalSeller:true});
        const reservationId=require('crypto').randomUUID();const prepared=await request(server).post('/admin/inquiries/'+room.id+'/prepare-transfer').set('x-admin-key',admin).send({requestId:reservationId});expect(prepared.status).toBe(200);
        const reservation=prepared.body.reservation;
        await request(server).post('/admin/inquiries/'+room.id+'/delivery').set('x-admin-key',admin).send({requestId:require('crypto').randomUUID(),reservationId,payloadHash:reservation.payloadHash,routeHash:reservation.routeHash,leadId:lid,sourceUrl:l.canonicalUrl,channel:'FACEBOOK_UI',receiptRef:'review:synthetic-send-receipt',sentAt:new Date().toISOString(),outcome:'CONFIRMED_SENT'});
        const reply={requestId:require('crypto').randomUUID(),leadId:lid,sourceUrl:l.canonicalUrl,routeHash:reservation.routeHash,reservationId,text:'合成原賣家：仍在售，僅本地測試',receiptRef:'review:synthetic-reply-receipt',receivedAt:new Date().toISOString()};
        const endpoint='/admin/inquiries/'+room.id+'/seller-reply';
        expect((await request(server).post(endpoint).set('x-admin-key',admin).send({...reply,leadId:require('crypto').randomUUID()})).status).toBe(409);
        expect((await request(server).post(endpoint).set('x-admin-key',admin).send({...reply,receivedAt:new Date(Date.now()-3600000).toISOString()})).status).toBe(409);
        const posted=await request(server).post(endpoint).set('x-admin-key',admin).send(reply);expect(posted.status).toBe(200);expect(posted.body.events.filter((e:any)=>e.action==='SELLER_REPLY')).toHaveLength(1);
        expect((await request(server).post(endpoint).set('x-admin-key',admin).send(reply)).body.events.filter((e:any)=>e.action==='SELLER_REPLY')).toHaveLength(1);
        const legacy=(await request(server).get('/leads/'+lid+'/inquiry').set('x-api-key',key)).body;expect(legacy.events.some((e:any)=>e.action==='SELLER_REPLY')).toBe(false);
        const modern=(await request(server).get('/leads/'+lid+'/inquiry?presentation=1').set('x-api-key',key)).body;expect(modern.events.some((e:any)=>e.text===reply.text)).toBe(true);
        expect((await request(server).get('/leads/'+lid+'/inquiry?presentation=1').set('x-api-key',otherKey)).body).toBeNull();
        const stored=await prisma.sourceLeadInquiry.findUniqueOrThrow({where:{id:room.id}}),delivery=stored.delivery as any;
        const current=await prisma.externalSourceLead.findUniqueOrThrow({where:{id:lid}}),originalRoute=current.sellerRoute as any;
        const oldTime=new Date(Date.now()-25*3600000).toISOString();
        await prisma.sourceLeadInquiry.update({where:{id:room.id},data:{delivery:{...delivery,receipt:{...delivery.receipt,sentAt:oldTime}}}});
        await prisma.externalSourceLead.update({where:{id:lid},data:{sellerRoute:{...originalRoute,verifiedAt:oldTime}}});
        const lateReply={...reply,requestId:require('crypto').randomUUID(),text:'合成賣家隔日回覆',receiptRef:'review:synthetic-nextday-reply',receivedAt:new Date().toISOString()};
        expect((await request(server).post(endpoint).set('x-admin-key',admin).send(lateReply)).status).toBe(409);
        const reverify=(publicRouteUrl:string)=>request(server).post('/admin/'+lid+'/seller-route').set('x-admin-key',admin).send({leadId:lid,contentHash:l.contentHash,sourceUrl:l.canonicalUrl,channel:originalRoute.channel,publicRouteUrl,identityEvidenceRef:originalRoute.identityEvidenceRef,routeEvidenceRef:'review:synthetic-new-attestation',confirmOriginalSeller:true});
        await reverify('https://m.me/wrong-seller');
        expect((await request(server).post(endpoint).set('x-admin-key',admin).send(lateReply)).status).toBe(409);
        await reverify(originalRoute.publicRouteUrl);
        expect((await request(server).post(endpoint).set('x-admin-key',admin).send(lateReply)).status).toBe(200);
        expect(((await prisma.sourceLeadInquiry.findUniqueOrThrow({where:{id:room.id}})).delivery as any).receipt.routeHash).toBe(delivery.receipt.routeHash);

    });

    test('twenty synthetic leads validate atomically without stock or copied images', async () => {
        const before = await prisma.externalSourceLead.count();
        const result = await importLead(Array.from({length:20}, (_,i)=>body('SYNTHETIC-DRY-'+i)), true);
        expect(result.status).toBe(200);
        expect(result.body.validatedCount).toBe(20);
        expect(result.body.persistedCount).toBe(0);
        expect(await prisma.externalSourceLead.count()).toBe(before);
    });
    test('two buyers, same-name different items, multiple rounds and late/duplicate replies remain bound',async()=>{
        const imported=await importLead([body('SYNTHETIC-ROUND-A'),body('SYNTHETIC-ROUND-B')]);expect(imported.status).toBe(200);const [lid,secondId]=imported.body.ids;
        const lead=await prisma.externalSourceLead.findUniqueOrThrow({where:{id:lid}});
        await request(server).post('/admin/'+lid+'/seller-route').set('x-admin-key',admin).send({leadId:lid,contentHash:lead.contentHash,sourceUrl:lead.canonicalUrl,channel:'FACEBOOK_UI',publicRouteUrl:'https://m.me/synthetic-round-seller',identityEvidenceRef:'review:synthetic-round-identity',routeEvidenceRef:'review:synthetic-round-route',confirmOriginalSeller:true});
        const openFor=async(id:string,apiKey:string)=>(await request(server).post('/leads/'+id+'/inquiry?presentation=1').set('x-api-key',apiKey).send({})).body;
        const a=await openFor(lid,key),b=await openFor(lid,otherKey),c=await openFor(secondId,key);expect(new Set([a.id,b.id,c.id]).size).toBe(3);
        const askFor=async(room:any,apiKey:string,text:string)=>{const before=(await request(server).get('/leads/'+lid+'/inquiry?presentation=1').set('x-api-key',apiKey)).body;const payload={requestId:require('crypto').randomUUID(),action:'ASK',text,consent:true,transferHash:before.transferHash};const route='/leads/'+lid+'/inquiry/'+room.id+'/actions?presentation=1';const first=await request(server).post(route).set('x-api-key',apiKey).send(payload);expect(first.status).toBe(200);expect((await request(server).post(route).set('x-api-key',apiKey).send(payload)).body.events.filter((e:any)=>e.requestId===payload.requestId)).toHaveLength(1);return payload;};
        const transfer=async(room:any)=>{const rid=require('crypto').randomUUID(),route='/admin/inquiries/'+room.id+'/prepare-transfer';const first=await request(server).post(route).set('x-admin-key',admin).send({requestId:rid});expect(first.status).toBe(200);expect(first.body.outboundSent).toBe(false);expect((await request(server).post(route).set('x-admin-key',admin).send({requestId:rid})).body.reservation.id).toBe(rid);return first.body;};
        const delivered=async(room:any,t:any)=>{const v=t.reservation,receipt={requestId:require('crypto').randomUUID(),reservationId:v.id,payloadHash:v.payloadHash,routeHash:v.routeHash,leadId:lid,sourceUrl:lead.canonicalUrl,channel:'FACEBOOK_UI',receiptRef:'review:synthetic-round-send',sentAt:new Date().toISOString(),outcome:'CONFIRMED_SENT'};const r=await request(server).post('/admin/inquiries/'+room.id+'/delivery').set('x-admin-key',admin).send(receipt);expect(r.status).toBe(200);return receipt;};
        const reply=async(room:any,t:any,text:string,at=new Date().toISOString())=>({requestId:require('crypto').randomUUID(),leadId:lid,sourceUrl:lead.canonicalUrl,routeHash:t.reservation.routeHash,reservationId:t.reservation.id,text,receiptRef:'review:synthetic-round-reply',receivedAt:at});
        const postReply=(room:any,payload:any)=>request(server).post('/admin/inquiries/'+room.id+'/seller-reply').set('x-admin-key',admin).send(payload);
        const qa=await askFor(a,key,'合成提議面交，未確認');const ta=await transfer(a);const da=await delivered(a,ta);
        const qb=await askFor(b,otherKey,'另一買家詢問');const tb=await transfer(b);await delivered(b,tb);
        const first=await reply(a,ta,'合成賣家第一輪回覆，僅引用文字');expect((await postReply(a,first)).status).toBe(200);expect((await postReply(b,first)).status).toBe(409);expect((await postReply(c,first)).status).toBe(409);
        const follow=await askFor(a,key,'合成追問：改約與確認需要雙方核實');const next=await transfer(a);expect(next.reservation.roundNumber).toBe(2);expect(next.outboundQuestions.map((q:any)=>q.requestId)).toEqual([follow.requestId]);expect(next.snapshot.questions.map((q:any)=>q.requestId)).toEqual([qa.requestId,follow.requestId]);
        const late=await reply(a,ta,'合成第一輪晚到回覆');expect((await postReply(a,late)).status).toBe(200);expect((await postReply(a,late)).body.events.filter((e:any)=>e.requestId===late.requestId)).toHaveLength(1);
        expect((await postReply(a,{...late,requestId:require('crypto').randomUUID(),reservationId:undefined})).status).toBe(409);
        expect((await request(server).post('/admin/inquiries/'+a.id+'/delivery').set('x-admin-key',admin).send(da)).status).toBe(200);expect((await prisma.sourceLeadInquiry.findUniqueOrThrow({where:{id:a.id}})).state).toBe('TRANSFER_RESERVED');
        const beforeSend=await request(server).get('/admin/inquiries/'+a.id+'/transfer-preflight').set('x-admin-key',admin);expect(beforeSend.body.outboundQuestions).toEqual(next.outboundQuestions);const dn=await delivered(a,next);
        const newer=await reply(a,next,'合成新輪：已確認、改約、取消文字不代表結構化面交');expect((await postReply(a,newer)).status).toBe(200);
        const earlier=await reply(a,ta,'合成亂序舊輪消息',new Date(Date.parse(newer.receivedAt)-1).toISOString());expect((await postReply(a,earlier)).status).toBe(200);
        const ra=(await request(server).get('/leads/'+lid+'/inquiry?presentation=1').set('x-api-key',key)).body,rb=(await request(server).get('/leads/'+lid+'/inquiry?presentation=1').set('x-api-key',otherKey)).body;
        expect(ra.id).toBe(a.id);expect(ra.events.filter((e:any)=>e.action==='ASK').map((e:any)=>e.requestId)).toEqual([qa.requestId,follow.requestId]);expect(rb.events.some((e:any)=>e.requestId===qa.requestId||e.requestId===follow.requestId||e.action==='SELLER_REPLY')).toBe(false);expect(rb.events.find((e:any)=>e.action==='ASK').requestId).toBe(qb.requestId);expect((await openFor(secondId,key)).events).toEqual([]);
        const third=await askFor(a,key,'合成第三輪尚未送出');const stop=await request(server).post('/leads/'+lid+'/inquiry/'+a.id+'/actions?presentation=1').set('x-api-key',key).send({requestId:require('crypto').randomUUID(),action:'CANCEL'});expect(stop.body.state).toBe('CANCELLED');expect((await request(server).post('/admin/inquiries/'+a.id+'/prepare-transfer').set('x-admin-key',admin).send({requestId:require('crypto').randomUUID()})).status).toBe(409);
        expect(((await prisma.sourceLeadInquiry.findUniqueOrThrow({where:{id:a.id}})).delivery as any).history).toHaveLength(2);
        console.log(JSON.stringify({sourceMultiRound:'PASS',buyersSameProduct:2,sameNameProducts:2,rounds:3,confirmedSyntheticReceipts:2,lateAndOutOfOrderReplies:true,duplicateReceiptsAndQuestions:'idempotent',sellerMissingReference:'rejected pending verification',externalUIActions:0,meetupConfirmedByText:false}));
    });
    test('withdrawal stops map/ASK/consent, cancel works; 31-row pagination and buyer erase cascade', async () => {
        const extra = body('SYNTHETIC-WITHDRAW');
        const added = await importLead([extra]);
        const id = added.body.ids[0];
        const room = await request(server).post('/leads/' + id + '/inquiry').set('x-api-key', otherKey).send({});
        const endpoint = '/leads/' + id + '/inquiry/' + room.body.id + '/actions';
        expect((await request(server).post('/admin/' + id + '/withdraw').set('x-admin-key', admin).send({ reasonRef: 'self:synthetic-withdraw' })).status).toBe(200);
        expect((await request(server).get('/leads/' + id)).status).toBe(404);
        expect((await request(server).post(endpoint).set('x-api-key', otherKey).send({ requestId: require('crypto').randomUUID(), action: 'ASK', text: 'hi' })).status).toBe(409);
        expect((await request(server).post(endpoint).set('x-api-key', otherKey).send({ requestId: require('crypto').randomUUID(), action: 'CANCEL' })).body.state).toBe('CANCELLED');
        const beforePagination = await request(server).get('/leads');
        const baselineIds: string[] = beforePagination.body.items.map((r: any) => r.id);
        expect(beforePagination.body.nextCursor).toBeNull();
        for (let i = 0; i < 30; i += 10)
            expect((await importLead(Array.from({ length: 10 }, (_, j) => body('SYNTHETIC-PAGE-' + (i + j))))).status).toBe(200);
        const ids: string[] = [];
        let cursor: null | string = null;
        do {
            const page = await request(server).get('/leads' + (cursor ? '?cursor=' + cursor : ''));
            expect(page.status).toBe(200);
            ids.push(...page.body.items.map((r: any) => r.id));
            cursor = page.body.nextCursor;
        } while (cursor);
        expect(new Set(ids).size).toBe(baselineIds.length + 30);
        expect(baselineIds.every(id => ids.includes(id))).toBe(true);
        await prisma.user.delete({ where: { id: other } });
        expect(await prisma.sourceLeadInquiry.count({ where: { buyerUserId: other } })).toBe(0);
    });

    test('photo contract opt-in; rejects same/cross batch wrong-item images and partial replacement',async()=>{
      const stamp=new Date().toISOString();
      const make=(name:string,start:number,count=10)=>{
        const raw=body(name),photos=Array.from({length:count},(_,i)=>String(9000+i));
        const inventory={archiveItemId:raw.archiveItemId,sourceUrl:raw.canonicalUrl,checkedAt:stamp,reviewRef:'review:synthetic-all-angles',sourceRevision:'synthetic-1',coverage:'FULL_POST' as const,photos:photos.map(sourcePhotoId=>({sourcePhotoId,classification:'SAME_ITEM' as const,archiveItemId:raw.archiveItemId}))};
        const receipts:any[]=photos.map((sourcePhotoId,i)=>({state:'UPLOADED_AND_VERIFIED',archiveItemId:raw.archiveItemId,sourcePostUrl:raw.canonicalUrl,sourcePhotoId,mediaId:`22222222-2222-4222-8222-${String(start+i).padStart(12,'0')}`,photoId:String(start+i),mappingEvidenceRef:'review:synthetic-photo-map',rightsBasis:'HANK_USER_DIRECTED',rightsEvidenceRef:'consent:synthetic-user-display',uploadReceiptRef:'source:synthetic-flickr-upload',verifiedAt:stamp,flickrOriginal:{source:`https://live.staticflickr.com/1/${start+i}_abc_b.jpg`},thumbnailSource:`https://live.staticflickr.com/1/${start+i}_abc_s.jpg`}));
        return prepareSourcePhotoImport(raw,inventory,receipts,{version:4,sha256:'b'.repeat(64)});
      };
      const row=make('SYNTHETIC-PHOTOS-A',10000),imported=await importLead([row]);expect(imported.status).toBe(200);
      const id=imported.body.ids[0],legacy=await request(server).get('/leads/'+id+'?presentation=1');expect(legacy.status).toBe(200);expect(legacy.body).not.toHaveProperty('photoCompleteness');expect(legacy.body.media).toHaveLength(8);expect(legacy.body.notice).toContain('完整商品圖片請使用最新版網頁');
      const current=await request(server).get('/leads/'+id+'?presentation=1&photos=2');expect(current.body.media).toHaveLength(10);expect(current.body.photoCompleteness).toMatchObject({status:'IMPORTED_COMPLETE',sourceCount:10,physicalSourceCount:10,importedCount:10});
      expect((await request(server).get('/leads/'+id+'?photos=2')).status).toBe(409);
      expect((await importLead([make('SYNTHETIC-PHOTOS-B',10000)],true)).body.errorCode).toBe('SOURCE_PHOTO_CROSS_ITEM_CONFLICT');
      expect((await importLead([make('SYNTHETIC-PHOTOS-C',20000),make('SYNTHETIC-PHOTOS-D',20000)],true)).body.errorCode).toBe('SOURCE_PHOTO_CROSS_ITEM_CONFLICT');
      const missing={...row,archiveVersion:5,archiveSha256:'c'.repeat(64),evidence:{...row.evidence,media:row.evidence.media.slice(0,1)}};expect((await importLead([missing],true)).body.errorCode).toBe('SOURCE_PHOTO_COMPLETENESS_REQUIRED');
      const erased={...row,archiveVersion:5,archiveSha256:'c'.repeat(64),evidence:{...row.evidence,media:[]}};expect((await importLead([erased],true)).body.errorCode).toBe('SOURCE_PHOTO_COMPLETENESS_REQUIRED');
    });

});
