const {test}=require('node:test'),assert=require('node:assert/strict'),{audit}=require('./audit-proposal.cjs');
const item=(id='one',patch={})=>({id,source_post_url:'https://example.invalid/post/one',enumeration_complete:true,physical_product_photo_count:1,source_listing_media_count:1,same_physical_instance_count:1,source_photos:[{source_photo_id:'photo-one',role:'physical_product'}],...patch});
const run=items=>audit({schema_version:'proposed-source-media-audit/1.0',posts:[{source_post_url:'https://example.invalid/post/one',enumeration_complete:true}],items});
test('explicit mapping ready for review still cannot be called production-ready',()=>{const r=run([item()]);assert.equal(r.reviewReadyCount,1);assert.equal(r.items[0].readyForProductionImport,false);assert.equal(r.sourcePhotoDownloads,0);});
test('capacity-conflicting same-photo items preserve both IDs and both are blocked',()=>{const r=run([item('1.8L'),item('2.0L')]);assert.equal(r.items.length,2);assert.equal(r.blockedCount,2);});
test('missing brush-head photo is blocked, never borrowed',()=>{const r=run([item('brush-head',{physical_product_photo_count:0,source_listing_media_count:0,source_photos:[]})]);assert.ok(r.items[0].blockers.includes('NO_CONFIRMED_ITEM_IMAGES'));});
test('variant group or unidentified collage cannot count as one physical object',()=>{const r=run([item('bracelets',{same_physical_instance_count:13,source_photos:[{source_photo_id:'collage',role:'variant_collage'}]})]);assert.equal(r.blockedCount,1);});
test('packaging image is an image, not physical object evidence',()=>{const r=run([item('clock',{physical_product_photo_count:0,source_photos:[{source_photo_id:'box',role:'product_packaging'}]})]);assert.equal(r.items[0].physicalSourceCount,0);assert.equal(r.items[0].proposedExactMedia[0].classification,'ITEM_PACKAGING');});
test('unknown total stays unknown instead of turning the one confirmed box into complete coverage',()=>{const r=run([item('clock',{source_listing_media_count:null,enumeration_complete:false})]);assert.equal(r.blockedCount,1);assert.equal(r.items[0].sourceListingMediaCount,null);});
