const {test}=require('node:test'),assert=require('node:assert/strict'),{uploadMemory}=require('./upload-memory.cjs');
const sourcePhotoId='1587500909841251',post='https://www.facebook.com/groups/138730922963023/posts/3595555557280525',observation={sourcePhotoId,sourcePostUrl:post,viewerURL:'https://www.facebook.com/photo?fbid='+sourcePhotoId+'&set=pcb.3595555557280525',imageSrc:'https://scontent.test.fbcdn.net/test.jpg',checkedAt:new Date().toISOString()},mapping={archiveItemId:'FB138730922963023-3595555557280525-01',sourcePhotoId,sourcePostUrl:post,reviewed:true,role:'PHYSICAL',rightsBasis:'HANK_USER_DIRECTED',rightsEvidenceRef:'consent:synthetic-display-test',mappingEvidenceRef:'review:synthetic-normal-ui'};
const fixture=()=>{let uploads=0,fetches=0;const saved=[];return{saved,get uploads(){return uploads},get fetches(){return fetches},storage:{upload:async(id,bytes)=>{uploads++;assert.ok(Buffer.isBuffer(bytes));return{photoId:'123',thumbnailSource:'https://live.staticflickr.com/1/123_abc_s.jpg'}},rest:async()=>({sizes:{size:[{label:'Original',source:'https://live.staticflickr.com/1/123_abc_b.jpg'}]}}),read:async()=>Buffer.from('synthetic-image')},fetchSource:async()=>{fetches++;return{ok:true,body:[Buffer.from('synthetic-image')],headers:new Headers({'content-type':'image/jpeg'})}},sharp:()=>({metadata:async()=>({width:20,height:30})}),save:async r=>saved.push(structuredClone(r)),validatedFlickrSource:x=>x};};
test('all bytes stay in RAM, only metadata ledger, both originals and thumbs read back',async()=>{const f=fixture(),r=await uploadMemory(observation,mapping,f);assert.equal(r.state,'UPLOADED_AND_VERIFIED');assert.equal(r.imageBytesWrittenToDisk,0);assert.equal(f.uploads,1);assert.deepEqual(f.saved.map(x=>x.state),['UPLOAD_STARTING_NO_RETRY','UPLOADED','UPLOADED_AND_VERIFIED']);assert.equal(JSON.stringify(f.saved).includes(observation.imageSrc),false);assert.ok(f.saved.every(r=>Object.values(r).every(v=>!Buffer.isBuffer(v))));});
test('stale UI locator does not fetch or upload',async()=>{const f=fixture();await assert.rejects(()=>uploadMemory({...observation,checkedAt:new Date(Date.now()-31*60000).toISOString()},mapping,f),/FRESH_NORMAL_UI/);assert.equal(f.fetches,0);assert.equal(f.uploads,0);});
test('wrong same-post photo, wrong CDN or unreviewed mapping fails before fetch',async()=>{for(const patch of[{sourcePhotoId:'other'},{imageSrc:'https://attacker.invalid/image.jpg'},{viewerURL:'https://www.facebook.com/photo?fbid='+sourcePhotoId+'&set=pcb.999'}]){const f=fixture();await assert.rejects(()=>uploadMemory({...observation,...patch},mapping,f));assert.equal(f.fetches,0);}});
test('failed source link cannot be uploaded or certified',async()=>{const f=fixture();f.fetchSource=async()=>({ok:false});await assert.rejects(()=>uploadMemory(observation,mapping,f),/SOURCE_ASSET_UNAVAILABLE/);assert.equal(f.uploads,0);assert.equal(f.saved.length,0);});
test('uncertain upload records STARTING once and never retries',async()=>{const f=fixture();let attempts=0;f.storage.upload=async()=>{attempts++;throw Error('synthetic-timeout');};await assert.rejects(()=>uploadMemory(observation,mapping,f));assert.equal(attempts,1);assert.equal(f.saved.at(-1).state,'UPLOAD_STARTING_NO_RETRY');});
test('failed storage readback remains UPLOADED, never VERIFIED',async()=>{const f=fixture();f.storage.read=async()=>{throw Error('synthetic-read-error');};await assert.rejects(()=>uploadMemory(observation,mapping,f));assert.equal(f.saved.at(-1).state,'UPLOADED');});

test("official cloud CDN dash hostname is supported; lookalike external domain rejected",async()=>{const f=fixture();await uploadMemory({...observation,imageSrc:"https://scontent-den2-1.xx.fbcdn.net/test.jpg"},mapping,f);assert.equal(f.uploads,1);const bad=fixture();await assert.rejects(()=>uploadMemory({...observation,imageSrc:"https://scontent-den2-1.xx.fbcdn.net.attacker.invalid/test.jpg"},mapping,bad));assert.equal(bad.fetches,0);});
