import { nextHoliday } from './holidayCalendar';

export const getUserLocale = (): string => {
    if (typeof window !== 'undefined' && window.localStorage) {
        const saved = window.localStorage.getItem('user-locale');
        if (saved) return saved;
    }
    if (typeof navigator !== 'undefined') {
        return navigator.language || 'en-US';
    }
    return 'en-US';
};

export const getCurrencyCode = (): string => {
    const locale = getUserLocale();
    if (locale.startsWith('zh-TW')) return 'TWD'; // NT$
    if (locale.startsWith('zh')) return 'CNY'; // Fallback for other Chinese
    if (locale.startsWith('ja')) return 'JPY';
    if (locale.startsWith('en-GB')) return 'GBP';
    if (locale.startsWith('en-AU')) return 'AUD';
    if (locale.startsWith('en-CA')) return 'CAD';
    if (locale.startsWith('de') || locale.startsWith('fr') || locale.startsWith('it') || locale.startsWith('es')) return 'EUR';
    return 'USD';
};

export const getCurrencySymbol = (currencyCode: string): string => {
    try {
        return (0).toLocaleString(
            undefined,
            { style: 'currency', currency: currencyCode, minimumFractionDigits: 0, maximumFractionDigits: 0 }
        ).replace(/\d/g, '').trim();
    } catch (e) {
        return '$'; // Fallback
    }
}


export const formatPrice = (amount: number): string => {
    const currency = getCurrencyCode();
    try {
        return new Intl.NumberFormat(getUserLocale(), {
            style: 'currency',
            currency: currency,
            minimumFractionDigits: 0,
            maximumFractionDigits: 0,
        }).format(amount);
    } catch (e) {
        return `$${amount}`;
    }
};

export const getNextHoliday = () => nextHoliday(getUserLocale(), new Date());

const translations: Record<string, Record<string, string>> = {
    'zh-TW': {
        'route.loading': '正在載入頁面…',
        'route.unavailable': '此頁暫時無法顯示',
        'route.loadFailed': '頁面資源未能載入。請確認網路連線後重試。',
        'route.renderFailed': '頁面顯示時發生問題，可以重試或使用導覽前往其他功能。',
        'route.recoveryHint': '若重試仍失敗，可重新整理網站取得目前版本。若先前操作結果不明，請先查核結果。',
        'route.retry': '重試載入頁面',
        'route.reload': '重新整理網站',
        'route.home': '返回首頁',
        // Navigation
        'nav.home': '首頁',
        'nav.dashboard': '禮物',
        'nav.social': '朋友',
        'nav.settings': '設定',
        'nav.logout': '登出',
        'nav.login': '登入',

        // Homepage
        'home.title': '整理你的願望。',
        'home.subtitle': 'AI 智慧許願清單，拍照就能記錄。分享給朋友，送禮不再煩惱。',
        'home.getStarted': '開始使用',
        'home.learnMore': '了解更多',
        'home.feature1.title': '拍一下，願望就記住了 📱',
        'home.feature1.desc': 'AI 自動幫你找到商品名稱、價格和購買連結',
        'home.feature2.title': '送禮不踩雷，朋友說讚 🎁',
        'home.feature2.desc': '分享你的願望清單，讓朋友知道你想要什麼',
        'home.feature3.title': '願望不再忘記 ✨',
        'home.feature3.desc': '依照場合分類，生日、節日、犒賞自己都能輕鬆管理',
        'home.feature4.title': '偷看清單，送進心坎 💕',
        'home.feature4.desc': '另一半偷偷查看願望，買到心儀禮物超幸福',

        // Login Page
        'login.title': '歡迎回來',
        'login.subtitle': '輸入手機號碼或電子信箱以登入',
        'feedback.title': '意見回饋',
        'feedback.placeholder': '遇到問題？有功能建議？或只是想聊天？',
        'feedback.submit': '送出',
        'feedback.submitting': '處理中...',
        'feedback.cancel': '取消',
        'feedback.success': '感謝您的回饋！',
        'feedback.aiReply': 'Wishlist.ai 客服回覆:',
        'feedback.close': '關閉',
        'feedback.note': '注意：兩次提交之間需間隔 10 分鐘。',
        'settings.securityMandatory': '(系統強制)',

        // PWA
        'pwa.installTitle': '安裝網頁 App',
        'pwa.android': 'Android',
        'pwa.desktop': '電腦版',
        'pwa.noButton': '沒有看到安裝按鈕？',
        'pwa.manual': '瀏覽器提供安裝選項時，可依以下步驟操作：',
        'pwa.step1': '點選瀏覽器選單（三個點）',
        'pwa.step2': '選擇「安裝應用程式」或「加入主畫面」',
        'pwa.step3': '點選「安裝」',
        'pwa.howTo': '如何安裝？',
        'pwa.desktopDesc': '請檢查網址列右側的安裝圖示，或瀏覽器選單中的安裝選項。沒有安裝選項時仍可直接使用網站。',

        // Wishlist Detail
        'wishlist.emptyOwner': '此清單目前是空的。點擊 + 新增項目！',
        'wishlist.emptyVisitor': '此願望清單目前是空的。',
        'wishlist.shareText': '來看看我在 Wishlist.ai 上的願望清單！',
        'item.cloned': '已加入您的清單！',
        'dashboard.createNew': '建立新願望清單',
        'common.search': '搜尋',
        'purchase.emptyTitle': '尚無購買記錄',
        'purchase.emptyDesc': '您標記為已購買的物品將顯示於此。',
        'auth.codeSent': '驗證碼已發送！',
        'auth.resetSuccess': '密碼已成功重設！',
        'auth.pwdUpdated': '密碼已更新！',
        'login.phoneNumber': '手機號碼',
        'login.phoneOrEmail': '手機號碼或電子信箱',
        'login.phoneOrEmailPlaceholder': '0912345678 或 name@example.com',
        'login.password': '密碼',
        'login.forgotPassword': '忘記密碼？',
        'login.signIn': '登入',
        'login.signingIn': '登入中...',
        'login.noAccount': '還沒有帳號？',
        'login.signUp': '註冊',
        'login.resendVerification': '重新發送驗證信',
        'login.sendingVerification': '發送中...',
        'login.verificationSent': '驗證信已發送，請查收信箱。',
        'login.verificationRequested': '已收到請求；若帳號存在且尚未驗證，系統會嘗試寄送驗證信。請查看信箱，未收到可稍後重試。',
        'login.resendFailed': '發送失敗，請稍後再試。',
        'login.enterEmailToResend': '請使用電子信箱登入以重新發送驗證信。',

        // Register Page
        'register.title': '建立帳號',
        'register.subtitle': '輸入資料建立你的帳號',
        'register.name': '姓名',
        'register.namePlaceholder': '王小明',
        'register.birthday': '生日',
        'register.year': '年',
        'register.month': '月',
        'register.day': '日',
        'register.phoneNumber': '手機號碼',
        'register.password': '密碼',
        'register.passwordHint': '密碼長度至少需 6 個字元',
        'register.createAccount': '建立帳號',
        'register.creatingAccount': '建立中...',
        'register.hasAccount': '已有帳號？',
        'register.signIn': '登入',

        // Forgot Password
        'forgot.title': '忘記密碼',
        'forgot.subtitle': '輸入手機號碼重設密碼',
        'forgot.description': '輸入您的電子信箱以接收重設密碼連結。',
        'forgot.emailLabel': '電子信箱',
        'forgot.sendCode': '發送驗證碼',
        'forgot.sending': '發送中...',
        'forgot.submitButton': '發送重設連結',
        'forgot.checkInbox': '請檢查您的收件匣（及垃圾郵件夾）以獲取重設連結。',
        'forgot.otpSent': '驗證碼已發送',
        'forgot.enterOtp': '輸入驗證碼',
        'forgot.newPassword': '新密碼',
        'forgot.resetPassword': '重設密碼',
        'forgot.resetting': '重設中...',
        'forgot.backToLogin': '返回登入',
        'forgot.emailPlaceholder': 'name@example.com',
        'forgot.defaultSuccess': '重設連結已發送！請檢查您的信箱。',

        // Settings
        'settings.title': '設定',
        'settings.profile': '個人資料',
        'settings.changePassword': '修改密碼',
        'settings.notifications': '通知設定',
        'settings.premium': '升級 Premium',
        'settings.language': '語言',
        'settings.logout': '登出',
        'settings.save': '儲存',
        'settings.saving': '儲存中...',

        // Social
        'social.title': '朋友',
        'social.search': '搜尋使用者',
        'social.searchPlaceholder': '姓名、手機號碼或電子信箱',
        'social.loginRequired': '登入後才能查看朋友與追蹤資料。',
        'social.queryInvalid': '請輸入1至100字的搜尋內容。',
        'social.readError': '讀取失敗，尚未取得結果，不代表沒有朋友。請重試。',
        'social.loading': '正在讀取朋友資料…',
        'social.retrySearch': '重試搜尋',
        'social.retryFollowing': '重試讀取追蹤清單',
        'social.clearSearch': '清除搜尋',
        'social.privacyHint': '可搜尋公開顯示名稱與暱稱；手機、真實姓名與信箱僅在本人允許公開時可搜尋，信箱需完整輸入。',
        'social.refineSearch': '目前顯示前20位；請加入更精確的內容以縮小範圍。',
        'social.anonymous': '未設定顯示名稱',
        'social.contactHidden': '聯絡資料未公開',
        'social.viewProfile': '查看公開資料',
        'social.viewWishes': '查看公開願望',
        'social.limitUnknown': '尚未取得追蹤上限；不以預設數字代替。',
        'social.changeConfirmed': '後台已確認追蹤變更。',
        'social.changeUnknown': '尚未確認追蹤變更結果。請只讀查核目前狀態，不會自動重送。',
        'social.checkCurrentFollow': '查核目前追蹤狀態',
        'social.currentFollowing': '目前後台顯示已追蹤；這是目前狀態，不是原操作歷史回執。',
        'social.currentNotFollowing': '目前後台顯示未追蹤；這是目前狀態，不是原操作歷史回執。',
        'social.following': '追蹤中',
        'social.followers': '追蹤者',
        'social.follow': '追蹤',
        'social.unfollow': '取消追蹤',
        'social.noFollowing': '尚未追蹤任何人',
        'social.noFollowers': '還沒有追蹤者',

        // Dashboard
        'dashboard.myWishlists': '我的願望清單',
        'dashboard.items': '個願望',
        'dashboard.newWishlist': '新增清單',
        'dashboard.empty': '還沒有願望清單',
        'dashboard.createFirst': '建立你的第一個願望清單',

        // Wishlist Detail
        'wishlist.addItem': '新增項目',
        'wishlist.empty': '清單是空的',
        'wishlist.addFirst': '新增你的第一個願望',
        'wishlist.delete': '刪除',
        'wishlist.edit': '編輯',
        'wishlist.share': '分享',
        'wishlist.price': '價格',
        'wishlist.buyNow': '立即購買',

        // Detail
        'detail.addUrl': '新增連結',
        'detail.uploadImg': '上傳圖片',
        'detail.addItemTitle': '新增物品',
        'detail.itemLabel': '商品網址 (支援各大電商)',
        'detail.itemPlaceholder': 'https://shopee.tw/product/...',
        'detail.smartInputTip': '貼上商品網址，AI 將自動為您填寫名稱、價格和圖片！',
        'detail.cloneTitle': '加入我的清單',
        'detail.cloneDesc': '選擇要加入的清單',
        'detail.cloneConfirm': '確認加入',
        'detail.cloneSuccess': '成功加入清單',
        'detail.deleteItemTitle': '刪除物品',
        'detail.deleteItemMsg': '確定要刪除此物品嗎？',
        'detail.copied': '已複製！',

        // Common
        'common.loading': '載入中...',
        'common.error': '發生錯誤',
        'common.retry': '重試',
        'common.cancel': '取消',
        'common.confirm': '確認',
        'common.save': '儲存',
        'common.saved': '已儲存！',
        'common.language': '語言',
        'common.languageDesc': '選擇您偏好的顯示語言',

        // Dashboard
        'dashboard.emptyTitle': '開啟您的願望之旅',
        'dashboard.emptyDesc': '建立第一個願望清單，開始收集您喜愛的物品！',
        'common.delete': '刪除',
        'common.edit': '編輯',
        'common.close': '關閉',
        'common.back': '返回',
        'common.next': '下一步',
        'common.done': '完成',
        'common.add': '新增',
        'common.processing': '處理中...',

        // AI Status
        'ai.complete': 'AI 識別完成',
        'ai.failed': 'AI 識別失敗',
        'ai.analyzing': 'AI 分析中',
        'ai.skipped': '傳統模式',

        // Settings - Deep Content
        'settings.avatar': '大頭照',
        'settings.displayName': '顯示名稱',
        'settings.nickname': '暱稱',

        'settings.emailNotifs': '電子郵件通知',
        'settings.notifMarketing': '接收行銷與更新資訊',
        'settings.notifSecurity': '帳號安全警示 (強制開啟)',
        'settings.avatarVisible': '目前狀態: 所有人可見 (讓朋友更容易找到你)',
        'settings.avatarHidden': '目前狀態: 隱藏 (別人看到會是預設灰色人)',
        'settings.changeAvatar': '更換照片',
        'settings.uploading': '更新中...',
        'settings.nicknames': '暱稱',
        'settings.nicknamesDesc': '(最多5個，預設為 piggy) 越多暱稱使自己更容易被搜尋到。',
        'settings.nicknamesPlaceholder': '例如: piggy, 小豬, 佩琪 (用逗號分隔)',
        'settings.privacyTitle': '隱私資料 (禮物送到家專用)',
        'settings.realName': '真實姓名',
        'settings.address': '寄送地址',
        'settings.phone': '手機號碼',
        'settings.email': '電子信箱',
        'settings.emailPlaceholder': 'name@example.com',
        'settings.emailReadOnly': '電子信箱設定後無法更改',
        'settings.birthday': '生日',
        'settings.public': '公開顯示',
        'settings.hidden': '隱藏',
        'settings.statusPublic': '目前: 公開顯示',
        'settings.statusHidden': '目前: 隱藏 (僅用於送禮)',
        'settings.statusHiddenBirthday': '目前: 隱藏 (設為隱藏時，不會出現在朋友的生日提醒中)',
        'settings.securityTitle': '帳號安全',
        'settings.securityDesc': '為了您的帳號安全，建議定期更改密碼。點擊下方按鈕前往修改頁面。',
        'settings.monetizationTitle': '贊助與升級',
        'settings.expandList': '擴充清單容量',
        'settings.expandListDesc': '單一清單上限 +10',
        'settings.buyNow': '立即購買',
        'settings.purchaseUnavailable': '購買與訂閱操作暫停；既有權益不受影響。若有持續扣款，請透過原付款平台管理。',
        'settings.premiumTitle': '無限訂閱制',
        'settings.premiumDesc': '解鎖所有清單無限容量',
        'settings.subscribe': '立即訂閱',
        'settings.isPremium': '✨ 您目前是尊榮會員',
        'settings.cancelSubscription': '取消訂閱',
        'settings.historyTitle': '交易紀錄',
        'settings.viewHistory': '查看贊助與購買紀錄',
        'settings.installApp': '安裝應用程式',
        'settings.installDesc': '獲得更流暢的 App 體驗',
        'settings.installBtn': '立即安裝',
        'settings.loginName': '登入名稱',
        'settings.type': '類型',
        'ai.usageTitle': 'AI 辨識額度',
        'ai.unlimitedDesc': '訂閱會員享有無限 AI 辨識次數',
        'ai.freeDesc': '免費用戶每日可使用 10 次 AI 辨識',
        'ai.unlimited': '無限次數',
        'ai.usedToday': '今日已使用',
        'ai.limitReached': '額度已用完，新增商品將使用傳統模式（需手動編輯）',

        // Social - Extra
        'social.findFriends': '尋找朋友',
        'social.mutual': '朋友',
        'social.peek': '單向追蹤',
        'social.retryLimit': '重試讀取追蹤上限',
        "social.followRestoring": "正在恢復原追蹤操作；只查核，不會自動重送。",
        "social.followNotice.unknown": "原追蹤結果尚未確認；請查核回執或明確重試同一操作。",
        "social.followNotice.storage": "無法安全保存或恢復追蹤紀錄；暫停變更，未保存時不會送出。",
        "social.followNotice.read": "尚未取得可核對的追蹤狀態；未送出變更。",
        "social.followNotice.unavailable": "對象已不存在或不適用；未送出變更。",
        "social.followNotice.unchanged": "查核時已是所選追蹤狀態；沒有送出新操作。",
        "social.followNotice.cleaned": "已清理讀過的本機回執標記；後台關係不變。",
        "social.followNotice.cleanup": "原回執已確認，本機標記清理失敗；請重試清理，不要重送。",
        "social.followNotice.changed": "本機紀錄已被另一分頁更新；未清掉該紀錄，請重新查核。",
        "social.followNotice.other": "原紀錄已清理；另一筆追蹤操作仍待確認。",
        "social.followReceipt.APPLIED": "後台回執已確認原追蹤變更完成。",
        "social.followReceipt.CONFLICT": "追蹤版本已更新；原操作未套用。請核對後再提出新操作。",
        "social.followReceipt.LIMIT": "原操作因追蹤額度不足而未套用；不會自動購買或重試。",
        "social.followReceipt.UNAVAILABLE": "原操作的對象已不存在；沒有套用追蹤變更。",
        "social.followReceipt.ABANDONED": "原操作已安全停止，晚到的重試不會套用。",
        "social.followCurrent": "查核時對象 #{id} 的狀態：",
        "social.notFollowing": "未追蹤",
        "social.targetUnavailable": "對象已不存在",
        "social.followReceiptExplanation": "原回執是歷史證據；查核時狀態可能已被後續操作改變。",
        "social.followPending": "原操作紀錄保留中；新追蹤變更暫停。重開只查核，不會自動重送。",
        "social.followReadReceipt": "查核原追蹤回執",
        "social.followRetrySame": "重試同一追蹤操作",
        "social.followCleanup": "已讀回執，清理本機標記",
        "social.followAbandon": "安全停止原追蹤操作",
        "social.followAbandonWarning": "尚未套用的操作將停止；已完成的追蹤變更不會撤回。是否繼續？",
        "social.followConfirmAbandon": "確認停止原追蹤操作",
        "social.followKeep": "保留原追蹤操作",
        "social.followRetryRestore": "重試恢復追蹤紀錄",
        "social.closeDialog": "關閉",
        "friend.invalid": "使用者連結不正確。",
        "friend.missing": "這個使用者已不存在。",
        "friend.readError": "公開資料讀取失敗或無法核對；不代表使用者不存在。請重試。",
        "friend.retry": "重試讀取公開資料",
        "friend.backFriends": "返回朋友",
        "friend.notSet": "未提供",
        "friend.photoUnavailable": "照片未提供或未公開",
        'social.confirmUnfollow': '確定要取消追蹤 {name} 嗎？不會刪除對方的帳號或商品。',
        'social.unfollowErr': '無法追蹤',
        'social.birthdayPrefix': '生日: ',
        'social.nicknamePrefix': '暱稱: ',
        'social.noUsers': '找不到使用者',

        // Forgot Password - Extra
        'forgot.enterOtpDesc': '請輸入驗證碼與新密碼',
        'forgot.otpSentAlert': '驗證碼已發送',
        'forgot.resetSuccessAlert': '密碼重設成功！請使用新密碼登入。',

        // Change Password
        'changePwd.title': '修改密碼',
        'changePwd.desc': '請輸入目前密碼與新密碼。',
        'changePwd.current': '目前密碼',
        'changePwd.new': '新密碼',
        'changePwd.confirm': '確認新密碼',
        'changePwd.update': '更新密碼',
        'changePwd.updating': '更新中...',
        'changePwd.success': '密碼修改成功！',
        'changePwd.matchErr': '新密碼不相符',
        'changePwd.lengthErr': '新密碼需為 8–72 個字元，包含英文字母與數字；符號限 @$!%*?&。',

        // Friend Profile
        'friend.title': '好友資料',
        'friend.basicInfo': '基本資料',
        'friend.hidden': '已隱藏',
        'friend.viewWishlist': '查看願望清單',

        // Purchase History
        'purchase.accountTitle': '帳戶購買紀錄',
        'purchase.accountDesc': '訂閱與升級紀錄',
        'purchase.giftsTitle': '已送出的禮物',
        'purchase.giftsDesc': '您已標記為購買的物品',
        'purchase.noAccount': '查無購買紀錄',
        'purchase.noGifts': '尚未送出任何禮物',
        'purchase.for': '給 {name}',

        // Wishlist Dashboard
        'dashboard.totalItems': '物品總數',
        'dashboard.perList': '每份清單',

        'dashboard.userWishlists': '{name} 的公開清單',
        'dashboard.createTitle': '建立新清單',
        'dashboard.titlePlaceholder': '清單名稱 (例如: 2024 生日)',
        'dashboard.descPlaceholder': '描述 (選填)',
        'dashboard.searchPlaceholder': '搜尋清單...',
        'dashboard.noDesc': '無描述',
        'dashboard.publicLabel': '公開此清單 (Public)',
        'detail.price': '價格',
        'detail.link': '連結',
        'detail.currency': '幣別',
        'detail.imageUrl': '圖片網址',
        'detail.notes': '備註',
        'common.saving': '儲存中...',
        'dashboard.public': '所有人可見',
        'dashboard.private': '僅自己可見',
        'dashboard.createBtn': '建立清單',
        'dashboard.deleteConfirmTitle': '刪除願望清單',
        'dashboard.deleteConfirmMsg': '您確定要刪除整個願望清單嗎？包含其中的所有物品。此操作無法復原。',
        'dashboard.emptyOwner': '您還沒有建立任何清單。在上方建立一個吧！',
        'dashboard.emptyVisitor': '此用戶尚未建立任何公開清單。',
        'detail.linkCopied': '連結已複製！',


    },
    'en-US': {
        'pwa.installTitle': 'Install Web app',
        'pwa.android': 'Android',
        'pwa.desktop': 'Desktop',
        'pwa.noButton': 'No install button?',
        'pwa.manual': 'If your browser offers installation, follow these steps:',
        'pwa.step1': 'Open the browser menu with three dots',
        'pwa.step2': 'Choose Install app or Add to Home screen',
        'pwa.step3': 'Choose Install',
        'pwa.howTo': 'How to install',
        'pwa.desktopDesc': 'Look for the install icon on the right of the address bar or an install option in the browser menu. You can still use the website if installation is unavailable.',
        'route.loading': 'Loading page…',
        'route.unavailable': 'This page is temporarily unavailable',
        'route.loadFailed': 'Page resources could not be loaded. Check your connection and retry.',
        'route.renderFailed': 'This page encountered a display problem. Retry or use navigation to visit another feature.',
        'route.recoveryHint': 'If retry still fails, reload the site to get the current version. Verify any earlier operation whose result is unknown before acting again.',
        'route.retry': 'Retry loading page',
        'route.reload': 'Reload site',
        'route.home': 'Back to home',
        // Navigation
        'nav.home': 'Home',
        'nav.dashboard': 'Dashboard',
        'nav.social': 'Social',
        'nav.settings': 'Settings',
        'nav.logout': 'Logout',
        'nav.login': 'Login',

        // Homepage
        'home.title': 'Organize your desires.',
        'home.subtitle': 'A minimalist wishlist powered by AI. Snap a photo, we\'ll do the rest. Share with friends, simplify your gifting.',
        'home.getStarted': 'Get Started',
        'home.learnMore': 'Learn More',
        'home.feature1.title': 'Snap it, save it 📱',
        'home.feature1.desc': 'AI finds product name, price, and shopping links automatically',
        'home.feature2.title': 'Perfect gifts, happy friends 🎁',
        'home.feature2.desc': 'Share your wishlist so friends know what you really want',
        'home.feature3.title': 'Never forget a wish ✨',
        'home.feature3.desc': 'Organize by occasion - birthdays, holidays, treats for yourself',
        'home.feature4.title': 'Peek & surprise 💕',
        'home.feature4.desc': 'Your partner secretly checks your list and gets the perfect gift',

        // Login Page
        'login.title': 'Welcome back',
        'login.subtitle': 'Enter your phone number or email to sign in',
        'login.phoneNumber': 'Phone Number',
        'login.phoneOrEmail': 'Phone Number or Email',
        'login.phoneOrEmailPlaceholder': '0912345678 or name@example.com',
        'login.password': 'Password',
        'login.forgotPassword': 'Forgot password?',
        'login.signIn': 'Sign In',
        'login.signingIn': 'Signing In...',
        'login.noAccount': 'Don\'t have an account?',
        'login.signUp': 'Sign up',
        'login.resendVerification': 'Resend verification email',
        'login.sendingVerification': 'Sending...',
        'login.verificationSent': 'Verification email sent. Please check your inbox.',
        'login.verificationRequested': 'Request received. If the account exists and is unverified, we will attempt to send a verification email. Check your inbox or retry later.',
        'login.resendFailed': 'Failed to send. Please try again later.',
        'login.enterEmailToResend': 'Please use your email to login to resend verification.',

        // Register Page
        'register.title': 'Create an account',
        'register.subtitle': 'Enter your details to create your account',
        'register.name': 'Name',
        'register.namePlaceholder': 'John Doe',
        'register.birthday': 'Birthday',
        'register.year': 'Year',
        'register.month': 'Month',
        'register.day': 'Day',
        'register.phoneNumber': 'Phone Number',
        'register.password': 'Password',
        'register.createAccount': 'Create Account',
        'register.creatingAccount': 'Creating Account...',
        'register.hasAccount': 'Already have an account?',
        'register.signIn': 'Sign in',

        // Forgot Password
        'forgot.title': 'Forgot Password',
        'forgot.subtitle': 'Enter your phone number to reset password',
        'forgot.sendCode': 'Send Code',
        'forgot.sending': 'Sending...',
        'forgot.otpSent': 'Code Sent',
        'forgot.enterOtp': 'Enter Code',
        'forgot.newPassword': 'New Password',
        'forgot.resetPassword': 'Reset Password',
        'forgot.resetting': 'Resetting...',
        'forgot.backToLogin': 'Back to Login',
        'forgot.emailPlaceholder': 'name@example.com',
        'forgot.defaultSuccess': 'Reset link sent! Check your email.',

        // Settings
        'settings.title': 'Settings',
        'settings.profile': 'Profile',
        'settings.changePassword': 'Change Password',
        'settings.notifications': 'Notifications',
        'settings.premium': 'Upgrade to Premium',
        'settings.language': 'Language',
        'settings.logout': 'Logout',
        'settings.save': 'Save',
        'settings.saving': 'Saving...',

        // Social
        'social.title': 'Social',
        'social.search': 'Search Users',
        'social.searchPlaceholder': 'Name, phone number, or email',
        'social.loginRequired': 'Sign in to view friends and following.',
        'social.queryInvalid': 'Enter a search query of 1 to 100 characters.',
        'social.readError': 'The request failed; results are unknown, not empty. Please retry.',
        'social.loading': 'Loading friend details…',
        'social.retrySearch': 'Retry search',
        'social.retryFollowing': 'Retry following list',
        'social.clearSearch': 'Clear search',
        'social.privacyHint': 'Search public display names and nicknames. Phone numbers, real names and emails are searchable only when their owner makes them public. Enter the complete email address.',
        'social.refineSearch': 'Showing the first 20 people. Refine your query to narrow the results.',
        'social.anonymous': 'No display name',
        'social.contactHidden': 'Contact details are private',
        'social.viewProfile': 'View public profile',
        'social.viewWishes': 'View public wishes',
        'social.limitUnknown': 'The following limit is unknown; no default number is substituted.',
        'social.changeConfirmed': 'The backend confirmed the following change.',
        'social.changeUnknown': 'The change is unconfirmed. Read the current status; the operation will not be retried automatically.',
        'social.checkCurrentFollow': 'Check current following status',
        'social.currentFollowing': 'Currently following, according to the backend. This is the current state, not a historical receipt for the original operation.',
        'social.currentNotFollowing': 'Currently not following, according to the backend. This is the current state, not a historical receipt for the original operation.',
        'social.following': 'Following',
        'social.followers': 'Followers',
        'social.follow': 'Follow',
        'social.unfollow': 'Unfollow',
        'social.noFollowing': 'Not following anyone yet',
        'social.noFollowers': 'No followers yet',

        // Dashboard
        'dashboard.myWishlists': 'My Wishlists',
        'dashboard.items': 'wishes',
        'dashboard.newWishlist': 'New Wishlist',
        'dashboard.empty': 'No wishlists yet',
        'dashboard.createFirst': 'Create your first wishlist',

        // Wishlist Detail
        'wishlist.emptyOwner': 'This list is empty. Tap + to add items!',
        'wishlist.emptyVisitor': 'This wishlist is empty.',
        'wishlist.shareText': 'Check out my wishlist on Wishlist.ai!',
        'item.cloned': 'Added to your wishlist!',
        'dashboard.createNew': 'Create New Wishlist',
        'wishlist.addItem': 'Add Item',
        'wishlist.empty': 'This list is empty',
        'wishlist.addFirst': 'Add your first wish',
        'wishlist.delete': 'Delete',
        'wishlist.edit': 'Edit',
        'wishlist.share': 'Share',
        'wishlist.price': 'Price',
        'wishlist.buyNow': 'Buy Now',

        // Detail
        'detail.addUrl': 'Add URL',
        'detail.uploadImg': 'Upload Image',
        'detail.addItemTitle': 'Add Item',
        'detail.itemLabel': 'Product URL',
        'detail.itemPlaceholder': 'https://amazon.com/...',
        'detail.smartInputTip': 'Paste a product URL, and AI will auto-fill the name, price, and image!',
        'detail.cloneTitle': 'Add to My Wishlist',
        'detail.cloneDesc': 'Select a wishlist',
        'detail.cloneConfirm': 'Add to Wishlist',
        'detail.cloneSuccess': 'Added to wishlist successfully',
        'detail.deleteItemTitle': 'Delete Item',
        'detail.deleteItemMsg': 'Are you sure you want to delete this item?',
        'detail.copied': 'Copied!',

        // Common
        'common.loading': 'Loading...',
        'common.error': 'An error occurred',
        'common.retry': 'Retry',
        'common.cancel': 'Cancel',
        'common.confirm': 'Confirm',
        'common.save': 'Save',
        'common.saved': 'Saved!',
        'common.language': 'Language',
        'common.languageDesc': 'Choose your preferred language',

        // Dashboard
        'dashboard.emptyTitle': 'Start Your Wishlist Journey',
        'dashboard.emptyDesc': 'Create your first wishlist and start collecting items you love!',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.close': 'Close',
        'common.back': 'Back',
        'common.next': 'Next',
        'common.done': 'Done',
        'common.add': 'Add',
        'common.processing': 'Processing...',

        // AI Status
        'ai.complete': 'AI Complete',
        'ai.failed': 'AI Failed',
        'ai.analyzing': 'AI Analyzing',
        'ai.skipped': 'Manual Mode',

        // Settings - Deep Content
        'settings.avatar': 'Profile Picture',
        'settings.displayName': 'Display Name',
        'settings.nickname': 'Nickname',

        'settings.emailNotifs': 'Email Notifications',
        'settings.notifMarketing': 'Receive Marketing & Updates',
        'settings.notifSecurity': 'Security Alerts (Required)',
        'settings.avatarVisible': 'Status: Visible to everyone (Easier for friends to find you)',
        'settings.avatarHidden': 'Status: Hidden (Others see default avatar)',
        'settings.changeAvatar': 'Change Photo',
        'settings.uploading': 'Uploading...',
        'settings.nicknames': 'Nicknames',
        'settings.nicknamesDesc': '(Max 5, default is piggy) More nicknames make it easier to be found.',
        'settings.nicknamesPlaceholder': 'e.g., piggy, cutie, honey (separated by commas)',
        'settings.privacyTitle': 'Private Info (For Gift Delivery)',
        'settings.realName': 'Real Name',
        'settings.address': 'Delivery Address',
        'settings.phone': 'Phone Number',
        'settings.email': 'Email',
        'settings.emailPlaceholder': 'name@example.com',
        'settings.emailReadOnly': 'Email cannot be changed once set',
        'settings.birthday': 'Birthday',
        'settings.public': 'Visible',
        'settings.hidden': 'Hidden',
        'settings.statusPublic': 'Status: Visible',
        'settings.statusHidden': 'Status: Hidden (Only for gifting)',
        'settings.statusHiddenBirthday': 'Status: Hidden (Will not appear in friends\' birthday reminders)',
        'settings.securityTitle': 'Account Security',
        'settings.securityDesc': 'For your security, we recommend changing your password regularly.',
        'settings.monetizationTitle': 'Sponsorship & Upgrade',
        'settings.expandList': 'Expand List Capacity',
        'settings.expandListDesc': 'List limit +10',
        'settings.buyNow': 'Buy Now',
        'settings.purchaseUnavailable': 'Purchases and subscription changes are paused; existing benefits remain. Manage any ongoing charges through the original payment provider.',
        'settings.premiumTitle': 'Unlimited Subscription',
        'settings.premiumDesc': 'Unlock unlimited capacity for all lists',
        'settings.subscribe': 'Subscribe Now',
        'settings.isPremium': '✨ You are a Premium Member',
        'settings.cancelSubscription': 'Cancel Subscription',
        'settings.historyTitle': 'Transaction History',
        'settings.viewHistory': 'View History',
        'settings.installApp': 'Install App',
        'settings.installDesc': 'Get a smoother app experience',
        'settings.installBtn': 'Install Now',
        'settings.loginName': 'Login Name',
        'settings.type': 'Type',
        'ai.usageTitle': 'AI Credits',
        'ai.unlimitedDesc': 'Unlimited AI credits for Premium members',
        'ai.freeDesc': '10 free AI credits per day',
        'ai.unlimited': 'Unlimited',
        'ai.usedToday': 'Used Today',
        'ai.limitReached': 'Limit reached. Adding/Editing items will switch to manual mode.',
        'settings.deleteAccount': 'Delete Account',
        'settings.deleteAccountDesc': 'Permanently remove your account and all data',
        'settings.deleteConfirm': 'Are you sure? This action cannot be undone. All your wishlists and data will be lost forever.',

        // Social - Extra
        'social.findFriends': 'Find Friends',
        'social.mutual': 'Friend',
        'social.peek': 'Following',
        'social.retryLimit': 'Retry following limit',
        "social.followRestoring": "Restoring the original follow operation; reads only, never resends.",
        "social.followNotice.unknown": "Original result unknown; read its receipt or explicitly retry the same operation.",
        "social.followNotice.storage": "Private journal unavailable; changes paused. Nothing sent without saving.",
        "social.followNotice.read": "Follow state unavailable; no change sent.",
        "social.followNotice.unavailable": "Target unavailable or ineligible; no change sent.",
        "social.followNotice.unchanged": "Verified state already matches; no new operation sent.",
        "social.followNotice.cleaned": "Local receipt marker cleared; server relationships unchanged.",
        "social.followNotice.cleanup": "Receipt confirmed, local cleanup failed. Retry cleanup, not the mutation.",
        "social.followNotice.changed": "Another tab changed the journal; it was not cleared. Verify it again.",
        "social.followNotice.other": "Original marker cleared; another operation remains pending.",
        "social.followReceipt.APPLIED": "Server receipt confirms the original follow change completed.",
        "social.followReceipt.CONFLICT": "Follow version changed; original operation not applied. Review before creating a new one.",
        "social.followReceipt.LIMIT": "Original operation not applied due to capacity; no automatic purchase or retry.",
        "social.followReceipt.UNAVAILABLE": "Target unavailable; original change not applied.",
        "social.followReceipt.ABANDONED": "Original operation safely stopped; delayed retries cannot apply it.",
        "social.followCurrent": "Target #{id} at verification:",
        "social.notFollowing": "Not following",
        "social.targetUnavailable": "Target no longer exists",
        "social.followReceiptExplanation": "Receipt is historical evidence; later changes may alter the verified current state.",
        "social.followPending": "Original journal retained; new changes paused. Reopening only reads, never resends.",
        "social.followReadReceipt": "Read original follow receipt",
        "social.followRetrySame": "Retry the same follow operation",
        "social.followCleanup": "Acknowledge receipt and clear local marker",
        "social.followAbandon": "Safely stop original operation",
        "social.followAbandonWarning": "Stop an unapplied operation; applied changes will not be undone. Continue?",
        "social.followConfirmAbandon": "Confirm stopping original operation",
        "social.followKeep": "Keep original operation",
        "social.followRetryRestore": "Retry restoring follow journal",
        "social.closeDialog": "Close",
        "friend.invalid": "Invalid user link.",
        "friend.missing": "This user no longer exists.",
        "friend.readError": "Public profile failed to load or verify; this does not mean the user is missing. Retry.",
        "friend.retry": "Retry public profile",
        "friend.backFriends": "Back to friends",
        "friend.notSet": "Not provided",
        "friend.photoUnavailable": "Photo absent or private",
        'social.confirmUnfollow': 'Unfollow {name}? This will not delete their account or listings.',
        'social.unfollowErr': 'Cannot follow',
        'social.birthdayPrefix': 'Birthday: ',
        'social.nicknamePrefix': 'Nickname: ',
        'social.noUsers': 'No users found',

        // Forgot Password - Extra
        'forgot.enterOtpDesc': 'Enter verification code and new password',
        'forgot.otpSentAlert': 'Verification code sent',
        'forgot.resetSuccessAlert': 'Password reset successful! Please login.',

        // Change Password
        'changePwd.title': 'Change Password',
        'changePwd.desc': 'Enter your current password and a new password.',
        'changePwd.current': 'Current Password',
        'changePwd.new': 'New Password',
        'changePwd.confirm': 'Confirm New Password',
        'changePwd.update': 'Update Password',
        'changePwd.updating': 'Updating...',
        'changePwd.success': 'Password changed successfully!',
        'changePwd.matchErr': 'New passwords do not match',
        'changePwd.lengthErr': 'Use 8–72 characters with letters and numbers; symbols are limited to @$!%*?&.',

        // Friend Profile
        'friend.title': 'Profile',
        'friend.basicInfo': 'Basic Info',
        'friend.hidden': 'Hidden',
        'friend.viewWishlist': 'View Wishlists',

        // Purchase History
        'purchase.accountTitle': 'Account Purchases',
        'purchase.accountDesc': 'Subscriptions and Upgrades',
        'purchase.giftsTitle': 'Gifts Sent',
        'purchase.giftsDesc': 'Items you marked as purchased',
        'purchase.noAccount': 'No account purchases found.',
        'purchase.noGifts': 'You haven\'t marked any items as purchased yet.',
        'purchase.for': 'For {name}',

        // Wishlist Dashboard
        'dashboard.totalItems': 'Total Items',
        'dashboard.perList': 'Per List',

        'dashboard.userWishlists': '{name}\'s Public Wishlists',
        'dashboard.createTitle': 'Create New Wishlist',
        'dashboard.titlePlaceholder': 'List Name',
        'dashboard.descPlaceholder': 'Description (Optional)',
        'dashboard.searchPlaceholder': 'Search wishlists...',
        'dashboard.noDesc': 'No description',
        'dashboard.publicLabel': 'Public Wishlist',
        'detail.price': 'Price',
        'detail.link': 'Link',
        'detail.currency': 'Currency',
        'detail.imageUrl': 'Image URL',
        'detail.notes': 'Notes',
        'common.saving': 'Saving...',
        'dashboard.public': 'Visible to everyone',
        'dashboard.private': 'Visible only to me',
        'dashboard.createBtn': 'Create Wishlist',
        'dashboard.deleteConfirmTitle': 'Delete Wishlist',
        'dashboard.deleteConfirmMsg': 'Are you sure you want to delete this wishlist? This cannot be undone.',
        'dashboard.emptyOwner': 'You don\'t have any wishlists yet. Create one above!',
        'dashboard.emptyVisitor': 'This user hasn\'t created any public wishlists.',
        'detail.linkCopied': 'Link copied!',


    }
};

export const t = (key: string): string => {
    let locale = 'en-US';
    try { locale = getUserLocale(); } catch { /* Optional language storage must not break page rendering. */ }
    const lang = locale.startsWith('zh') ? 'zh-TW' : 'en-US';
    return translations[lang]?.[key] || translations['en-US'][key] || key;
};
