import {photoBindingHash,photoCompleteness,SOURCE_PHOTO_LIMIT} from '../lib/sourcePhotoInventory';
import {prepareSourcePhotoImport} from '../lib/sourcePhotoImport';
import {sourceLeadMedia} from '../lib/sourceLeadMedia';
const now=Date.now(),id=(n:number)=>`11111111-1111-4111-8111-${String(n).padStart(12,'0')}`;
const base={archiveItemId:'FB138730922963023-3595555557280525-01',title:'來源線索：蘇俄在中國摘要問答',canonicalUrl:'https://www.facebook.com/groups/138730922963023/posts/3595555557280525',archiveVersion:7,checkedAt:new Date(now).toISOString(),evidence:{}};
const ids=['1587500906507918','1587500909841251','1587500913174584'];
const inventory=(photos=ids)=>({archiveItemId:base.archiveItemId,sourceUrl:base.canonicalUrl,checkedAt:new Date(now).toISOString(),reviewRef:'review:exact-first-three-20261003',sourceRevision:'post-photo-inventory-20261003',coverage:'FULL_POST' as const,photos:[...photos.map(sourcePhotoId=>({sourcePhotoId,classification:'SAME_ITEM' as const,archiveItemId:base.archiveItemId})),{sourcePhotoId:'advertisement',classification:'ADVERTISEMENT' as const},{sourcePhotoId:'different-product',classification:'OTHER_ITEM' as const,archiveItemId:'another-item'}]});
// Synthetic storage receipts only; source IDs are the reviewed real grouping, never production writes.
const receipts=(photos=ids):any[]=>photos.map((sourcePhotoId,i)=>({state:'UPLOADED_AND_VERIFIED',archiveItemId:base.archiveItemId,sourcePostUrl:base.canonicalUrl,sourcePhotoId,mediaId:id(i+1),photoId:String(100+i),mappingEvidenceRef:'review:synthetic-item-mapping',rightsBasis:'HANK_USER_DIRECTED',rightsEvidenceRef:'consent:synthetic-approved-display',uploadReceiptRef:'source:synthetic-upload-receipt',verifiedAt:new Date(now).toISOString(),flickrOriginal:{source:`https://live.staticflickr.com/1/${100+i}_abc_b.jpg`},thumbnailSource:`https://live.staticflickr.com/1/${100+i}_abc_s.jpg`}));
const build=()=>prepareSourcePhotoImport(base,inventory(),receipts(),{version:8,sha256:'a'.repeat(64)},now);
describe('complete source-item photo import',()=>{
 test('three same-object angles in source order, excludes advertisements and other goods, keeps ID',()=>{const row=build();expect(row.archiveItemId).toBe(base.archiveItemId);expect(row.evidence.media.map((m:any)=>m.sourcePhotoId)).toEqual(ids);expect(photoCompleteness(row,sourceLeadMedia(row,now),now)).toMatchObject({status:'IMPORTED_COMPLETE',sourceCount:3,importedCount:3});});
 test('ten angles are supported without changing the separate native-listing cap',()=>{const photos=Array.from({length:10},(_,i)=>'photo'+i);const row=prepareSourcePhotoImport(base,inventory(photos),receipts(photos),{version:8,sha256:'a'.repeat(64)},now);expect(sourceLeadMedia(row,now)).toHaveLength(10);});
 test('YODA physical ten and dedicated specification six stay distinct, unrelated advert excluded',()=>{const all=Array.from({length:16},(_,i)=>'yoda'+i),inv:any=inventory(all);for(let i=10;i<16;i++)inv.photos[i].classification='ITEM_SPECIFICATION';const row=prepareSourcePhotoImport(base,inv,receipts(all),{version:8,sha256:'a'.repeat(64)},now);expect(photoCompleteness(row,sourceLeadMedia(row,now),now)).toMatchObject({status:'IMPORTED_COMPLETE',physicalSourceCount:10,sourceCount:16,importedCount:16});});
 test('over-limit is rejected rather than truncated',()=>{const photos=Array.from({length:SOURCE_PHOTO_LIMIT+1},(_,i)=>'photo'+i);expect(()=>prepareSourcePhotoImport(base,inventory(photos),receipts(photos),{version:8,sha256:'a'.repeat(64)},now)).toThrow('SOURCE_PHOTO_LIMIT_EXCEEDED');});
 test.each(['duplicate-source','duplicate-media','advertisement','wrong-item','not-verified','broken-storage','missing-rights','missing-photo'])('rejects %s before producing a payload',kind=>{const r=receipts();if(kind==='duplicate-source')r[1].sourcePhotoId=r[0].sourcePhotoId;if(kind==='duplicate-media')r[1].mediaId=r[0].mediaId;if(kind==='advertisement')r[1].sourcePhotoId='advertisement';if(kind==='wrong-item')r[1].archiveItemId='different-item';if(kind==='not-verified')r[1].state='UPLOADED';if(kind==='broken-storage')r[1].flickrOriginal.source='https://invalid.example/image.jpg';if(kind==='missing-rights')delete r[1].rightsEvidenceRef;if(kind==='missing-photo')r.pop();expect(()=>prepareSourcePhotoImport(base,inventory(),r,{version:8,sha256:'a'.repeat(64)},now)).toThrow();});
 test('unknown grouping and partial source inspection cannot certify completeness',()=>{const v=inventory();(v.photos[0] as any)={sourcePhotoId:ids[0],classification:'UNKNOWN'};expect(()=>prepareSourcePhotoImport(base,v,receipts(),{version:8,sha256:'a'.repeat(64)},now)).toThrow('FULL_ITEM_ASSIGNMENT_REQUIRED');expect(()=>prepareSourcePhotoImport(base,{...inventory(),coverage:'PARTIAL'},receipts(),{version:8,sha256:'a'.repeat(64)},now)).toThrow('FULL_ITEM_ASSIGNMENT_REQUIRED');});
 test('missing, replaced, reordered, or regrouped media invalidates prior confirmation',()=>{for(const change of ['remove','replace','reorder','regroup']){const row=build();if(change==='remove')row.evidence.media.pop();if(change==='replace')row.evidence.media[0].imageUrl='https://live.staticflickr.com/1/100_changed_b.jpg';if(change==='reorder')row.evidence.media.reverse();if(change==='regroup')row.evidence.photoInventory.photos[0].classification='ADVERTISEMENT';expect(photoCompleteness(row,sourceLeadMedia(row,now),now).status).not.toBe('IMPORTED_COMPLETE');}});
 test('current media validity matters even when inventory hash still matches',()=>{const row=build();row.evidence.media[1].checkedAt=new Date(now-49*3600000).toISOString();row.evidence.photoInventory.bindingHash=photoBindingHash(row.evidence.photoInventory,row.evidence.media);expect(photoCompleteness(row,sourceLeadMedia(row,now),now)).toMatchObject({status:'INCOMPLETE',importedCount:2});});
 test('legacy one-photo media is unverified, not automatically incomplete',()=>{const row=build();delete row.evidence.photoInventory;expect(photoCompleteness(row,sourceLeadMedia(row,now),now)).toMatchObject({status:'UNVERIFIED',sourceCount:null,importedCount:3});});
 test('a reviewed genuine single-photo item is complete',()=>{const row=prepareSourcePhotoImport(base,inventory(ids.slice(0,1)),receipts(ids.slice(0,1)),{version:8,sha256:'a'.repeat(64)},now);expect(photoCompleteness(row,sourceLeadMedia(row,now),now).status).toBe('IMPORTED_COMPLETE');});
 test.each([
  ['3595555557280525','1587500906507918','1587500909841251','1587500913174584'],
  ['3594378424064905','1586582789933063','1586582799933062','1586582796599729'],
  ['3592975287538552','1585482106709798','1585482113376464','1585482116709797']
 ])('reviewed three-book grouping fixture %s preserves all three, storage stays synthetic', (post,a,b,c)=>{
  const product={...base,archiveItemId:'FB138730922963023-'+post+'-01',canonicalUrl:'https://www.facebook.com/groups/138730922963023/posts/'+post};
  const inv:any=inventory([a,b,c]);inv.archiveItemId=product.archiveItemId;inv.sourceUrl=product.canonicalUrl;inv.photos=inv.photos.map((p:any)=>({...p,...(p.classification==='SAME_ITEM'?{archiveItemId:product.archiveItemId}:{})}));
  const uploaded=receipts([a,b,c]).map(r=>({...r,archiveItemId:product.archiveItemId,sourcePostUrl:product.canonicalUrl}));const row=prepareSourcePhotoImport(product,inv,uploaded,{version:8,sha256:'a'.repeat(64)},now);expect(row.evidence.media.map((m:any)=>m.sourcePhotoId)).toEqual([a,b,c]);
 });

 test('packaging-only complete image set is not physical-product photo evidence',()=>{const inv:any=inventory(ids.slice(0,1));inv.photos[0].classification='ITEM_PACKAGING';const row=prepareSourcePhotoImport(base,inv,receipts(ids.slice(0,1)),{version:8,sha256:'a'.repeat(64)},now);expect(photoCompleteness(row,sourceLeadMedia(row,now),now)).toMatchObject({status:'IMPORTED_COMPLETE',sourceCount:1,physicalSourceCount:0});});
 test.each(['ITEM_IDENTITY','CAPACITY','UNRESOLVED_MEDIA'])('unresolved %s blocks certification without merging or borrowing a photo',kind=>{expect(()=>prepareSourcePhotoImport(base,{...inventory(),ambiguities:[{kind:kind as any,evidenceRef:'review:synthetic-capacity-conflict'}]},receipts(),{version:8,sha256:'a'.repeat(64)},now)).toThrow('FULL_ITEM_ASSIGNMENT_REQUIRED');});
 test('a toothbrush image cannot replace an independently absent brush-head image',()=>{const inv:any=inventory(ids.slice(0,1));inv.photos[0].classification='OTHER_ITEM';inv.photos[0].archiveItemId='toothbrush-not-head';expect(()=>prepareSourcePhotoImport(base,inv,[],{version:8,sha256:'a'.repeat(64)},now)).toThrow('NO_CONFIRMED_ITEM_PHOTOS');});

});
