import {parseLead,leadDTO,leadCurrent} from '../lib/sourceLeadRules';
import {countyIllustration,COUNTY_ILLUSTRATION_SOURCE} from '../lib/sourceCountyIllustration';
const now=new Date('2026-10-03T01:40:00Z');
const make=()=>{const county='桃園市',url='https://www.facebook.com/groups/123456789/posts/987654321';const p=countyIllustration(county)!;return {archiveItemId:'SYNTHETIC-COUNTY',libraryFileId:'libfile_'+'a'.repeat(32),archiveVersion:1,archiveSha256:'a'.repeat(64),title:'合成候選玩具',summary:'來源線索，庫存與交易待確認。',canonicalUrl:url,county,district:'桃園區',publicPlaceName:county+'概略示意位置',publicAddress:county+'（概略位置，非取貨點）',latitude:p.latitude,longitude:p.longitude,postedEarliestAt:'2026-10-01T00:00:00Z',postedLatestAt:'2026-10-01T23:59:59Z',checkedAt:'2026-10-03T01:30:00Z',evidence:{sourceUrl:url,sourcePublic:true,publicSourceRef:'review:synthetic-public',dateRef:'review:synthetic-date',locationRef:'review:synthetic-county',coordinateRef:'source:post-dataset-25489',locationSourceUrl:url,coordinateSourceUrl:COUNTY_ILLUSTRATION_SOURCE,publicPlace:false,locationType:'COUNTY_ILLUSTRATION',sourceMeetingPointConfirmed:false,independentlyReviewed:true,selfWrittenSummary:true,noCopiedTextOrImages:true,noPrivateData:true,reviewRef:'review:synthetic-approved',countyIllustration:{county,sourceUrl:url,sourceCountyRef:'review:synthetic-original-county',representativeKey:p.key,approvalRef:'consent:synthetic-county-only'}}};};
describe('county illustration never becomes a verified pickup or qualified listing',()=>{
 test('accepts bound county representative and exposes explicit safe label',()=>{const b=make(),row={...parseLead(b,now),id:'11111111-1111-4111-8111-111111111111',status:'PUBLISHED'} as any;expect(leadCurrent(row,now)).toBe(true);const dto=leadDTO(row);expect(dto.locationPrecision).toBe('COUNTY_ILLUSTRATION');expect(dto.stockStatus).toBe('UNKNOWN');expect(dto.qualifiedSupply).toBe(false);expect(dto.checkoutEnabled).toBe(false);expect(dto.notice).toContain('非取貨點');expect(dto).not.toHaveProperty('evidence');});
 test('rejects invented coordinates, wrong county/district, false meeting claims and private addresses',()=>{for(const patch of [{latitude:25.1},{county:'高雄市',district:'桃園區'},{district:'板橋區'},{publicAddress:'桃園市桃園區合成住家123號'},{evidence:{...make().evidence,publicPlace:true}},{evidence:{...make().evidence,sourceMeetingPointConfirmed:true}},{evidence:{...make().evidence,coordinateSourceUrl:'https://example.invalid/guess'}},{evidence:{...make().evidence,countyIllustration:{...make().evidence.countyIllustration,sourceUrl:'https://example.invalid/other'}}}])expect(()=>parseLead({...make(),...patch},now)).toThrow();});
 test('keeps original two-calendar-month, stale/source and privacy gates',()=>{for(const patch of [{postedEarliestAt:'2026-07-01T00:00:00Z'},{checkedAt:'2026-09-30T01:00:00Z'},{summary:'seller@example.com'},{evidence:{...make().evidence,sourcePublic:false}},{evidence:{...make().evidence,noPrivateData:false}}])expect(()=>parseLead({...make(),...patch},now)).toThrow();});
 test('cannot relabel an unverified point as a concrete public meeting point',()=>{expect(()=>parseLead({...make(),evidence:{...make().evidence,locationType:'PUBLIC_MEETING_POINT',countyIllustration:undefined}},now)).toThrow();});
});
