import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/marketplaceApi';
import { isUuid } from '../lib/listingBatch';
export type ConsignmentResult={kind:'ARCHIVED_AGENT_PROXY_INQUIRY';id:string;productId:string;archiveItemId:string;title:string;answer:string;state:string;canonicalUrl:string;events:{messageId:string;conversationId:string;sequence:number;action:string;text:string|null;at:string}[];meetup:{status:'UNKNOWN';reason:string}};
export function parseConsignmentResults(data:any):{items:ConsignmentResult[];truncated:boolean}{
 if(!data||data.scope!=='OWN_ARCHIVED_AGENT_PROXY_INQUIRIES'||!Array.isArray(data.items)||data.items.length>25||typeof data.truncated!=='boolean'||data.items.some((r:any)=>r.kind!=='ARCHIVED_AGENT_PROXY_INQUIRY'||!isUuid(r.id)||!isUuid(r.productId)||typeof r.title!=='string'||typeof r.archiveItemId!=='string'||typeof r.answer!=='string'||r.meetup?.status!=='UNKNOWN'||typeof r.meetup.reason!=='string'||!Array.isArray(r.events)||r.events.length>201||r.events.some((e:any)=>!isUuid(e.messageId)||e.conversationId!==r.id||!Number.isSafeInteger(e.sequence)||!['ASK','CONSENT','CANCEL','SELLER_REPLY'].includes(e.action)||!(e.text===null||typeof e.text==='string')||!Number.isFinite(Date.parse(e.at)))))throw Error('Invalid consignment response');return data;
}
export default function ChatQuery({token}:{token:string}) {
 const [query,setQuery]=useState(''),[items,setItems]=useState<ConsignmentResult[]>([]),[busy,setBusy]=useState(false),[issue,setIssue]=useState(''),[done,setDone]=useState(false),[truncated,setTruncated]=useState(false);
 const generation=useRef(0),controller=useRef<AbortController|null>(null),gate=useRef(false);
 useEffect(()=>()=>{generation.current++;controller.current?.abort();},[token]);
 async function submit(event:React.FormEvent){event.preventDefault();if(gate.current)return;gate.current=true;const n=++generation.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setIssue('');setItems([]);setDone(false);
  try {const data=parseConsignmentResults(await api<unknown>(token,'/chat/query',{method:'POST',body:JSON.stringify({query}),signal:AbortSignal.any([abort.signal,AbortSignal.timeout(30000)])}));if(n!==generation.current||abort.signal.aborted)return;setItems(data.items);setTruncated(data.truncated);setDone(true);
  }catch{if(n===generation.current)setIssue('代售查詢未完成，請重試；不能當作沒有紀錄。');}
  finally{if(n===generation.current){gate.current=false;setBusy(false);}}
 }
 return <section aria-labelledby="chat-query-heading" className="space-y-3 rounded-xl border bg-white p-4"><h2 id="chat-query-heading" className="font-semibold">查詢代售詢問與面交</h2><p className="text-sm">例如「二手書在哪裡面交？」或「商品 ID：…」。僅查詢已歸檔且有 Agent 代理詢問同意的來源商品；自刊商品排除。不發訊、不將聊天傳給外部模型。</p><form onSubmit={submit} className="flex flex-wrap gap-2"><label htmlFor="chat-query" className="sr-only">代售查詢問題</label><input id="chat-query" value={query} onChange={e=>setQuery(e.target.value)} maxLength={500} required className="min-h-11 min-w-0 flex-1 rounded border p-2"/><button disabled={busy} type="submit" className="min-h-11 rounded border px-4">{busy?'查詢中…':'查詢代售紀錄'}</button></form>{issue&&<p role="alert">{issue}</p>}{done&&!items.length&&<p role="status">沒有找到你有權讀取的合格代售詢問。可改用來源商品 ID 查詢；自刊商品不在範圍內。</p>}{truncated&&<p role="status">結果超過安全查詢範圍，尚未完整；請用名稱或商品 ID 縮小範圍。</p>}{items.length>1&&<p>多個結果分別列出，請核對商品 ID，不合併同名商品的約定。</p>}{items.map(r=><article key={r.id} data-consignment-product={r.productId} className="space-y-2 border-t pt-3"><h3>{r.title}</h3><p className="break-all">商品 ID：{r.productId} · 歸檔：{r.archiveItemId}</p><p>{r.answer}</p><p>面交：未知。{r.meetup.reason}</p><Link className="underline" to={'/chat?source='+r.productId}>原詢問：{r.id}</Link><details><summary>原訊息引用</summary>{r.events.map(m=><blockquote key={m.messageId} className="my-2 break-words border-l pl-2"><p>{m.text??({'CONSENT':'同意代理詢問','CANCEL':'取消代理詢問'} as any)[m.action]??m.action}</p><small className="break-all">詢問 {m.conversationId} · 訊息 {m.messageId} · {m.action} · {m.at}</small></blockquote>)}</details></article>)}</section>;
}
