import { Link } from 'react-router-dom';
import { ListingPhoto } from './ListingPhoto';
import { useSourceInquiry } from '../lib/useSourceInquiry';
import { sourceContactText as text } from '../lib/sourceContactCopy';
import { sourceLeadPrice } from '../lib/sourceLeadPrice';
export type SourceProductContext = { id: string; title: string; canonicalUrl: string; county?: string; district?: string; locationPrecision?: 'COUNTY_ILLUSTRATION'; contactRouting?: { status: 'VERIFIED' | 'UNAVAILABLE' | 'UNVERIFIED'; reason: string; checkedAt: string | null }; publicFacts?: { priceText: string }; media?: { id: string; imageUrl: string; thumbnailUrl: string; alt: string }[] };
const buttonClass = 'min-h-12 rounded-xl px-3 py-2 disabled:opacity-50';
export default function SourceContactChat({ source: selected, onBack }: { source: SourceProductContext; onBack: () => void }) {
 const { token, room, recovery, ready, error, notice, question, setQuestion, busy, waiting, action } = useSourceInquiry(selected.id);
 const pending = recovery.cancel ?? recovery.inquiry, locked = busy || waiting > 0 || !ready || !!pending;
 const roomNotice = !room ? text('empty') : ['DELIVERY_REQUIRES_REVIEW', 'CANCEL_REQUESTED'].includes(room.state) ? text('review') : room.state === 'CANCELLED' ? text('cancelled') : !room.available ? text('unavailable') : room.state === 'WAITING_ROUTE' ? text('waiting') + (selected.contactRouting?.reason || text('route')) + ' ' + text('notSent') : room.state === 'DELIVERED' && room.delivered ? text('deliveredNotice') : text('compose');
 return <section role="dialog" aria-modal="true" aria-label={text('title')} className="flex min-h-[620px] flex-col overflow-hidden rounded-2xl border bg-stone-50">
  <header className="flex items-center justify-between border-b bg-white p-4"><button className={buttonClass} onClick={onBack}>{text('back')}</button><h3 className="font-semibold">{text('title')}</h3><button className={buttonClass} disabled={busy || waiting > 0} onClick={() => action('READ')}>{text('update')}</button></header>
  <div className="flex gap-3 border-b bg-white p-4"><ListingPhoto src={selected.media?.[0]?.thumbnailUrl} alt={selected.title}/><div><p className="font-semibold">{selected.title}</p><p className="font-semibold text-green-800">{sourceLeadPrice(selected.publicFacts?.priceText)}</p><p className="text-xs text-stone-500">{text('item')}{selected.id} · {text('external')}</p><a className="inline-flex min-h-12 items-center" href={selected.canonicalUrl} target="_blank" rel="noreferrer">{text('original')}</a><p className="text-xs text-stone-600">{selected.contactRouting?.reason || text('route')}</p></div></div>
  <div className="flex-1 space-y-3 overflow-auto p-4"><p className="max-w-xl rounded-2xl bg-white p-4">{text('intro')}</p>{selected.locationPrecision==='COUNTY_ILLUSTRATION'&&<p className="max-w-xl rounded-2xl bg-white p-4">{text('approximateLocation')}</p>}<p className="max-w-xl rounded-2xl bg-white p-4">{roomNotice}</p>{room && <><p className="text-xs text-stone-500">{text('receipt')}{room.id} · {room.state} · {room.state === 'DELIVERED' && room.delivered ? text('delivered') : room.delivered ? text('evidence') : text('notSent')}</p>{room.events.map(e => <p key={e.requestId} className={e.action === 'SELLER_REPLY' ? 'max-w-xl rounded-2xl bg-white p-4' : 'ml-auto max-w-xl rounded-2xl bg-green-800 p-4 text-white'}>{e.action === 'SELLER_REPLY' ? text('seller') : ''}{e.text ?? (e.action === 'CONSENT' ? text('consentEvent') : text('cancelEvent'))}<small className="mt-1 block break-all opacity-70">{e.requestId}{e.reservationId?' · '+e.reservationId:''}</small></p>)}</>}
   {pending && <div className="rounded-xl border border-amber-300 bg-amber-50 p-4" role="status"><p>{text(pending.operation.version === 0 ? 'legacy' : 'pending')}</p>{recovery.inquiry?.operation.version === 1 && recovery.inquiry.operation.payload.text && <><p className="mt-2 font-semibold">{text('savedQuestion')}</p><p className="whitespace-pre-wrap">{recovery.inquiry.operation.payload.text}</p></>}</div>}
  </div>
  <footer className="space-y-2 border-t bg-white p-4">{error && <p role="alert" className="text-red-700">{error}</p>}{notice && <p role="status">{notice}</p>}{waiting > 0 && <p role="status">{text('wait', { seconds: waiting })}</p>}
   {!token ? <Link className="inline-flex min-h-12 items-center" to="/login">{text('login')}</Link> : <><button className={buttonClass} disabled={busy || waiting > 0} onClick={() => action('READ')}>{text(ready ? 'read' : 'restore')}</button>
    {pending?.operation.version === 1 && <button className={buttonClass + ' border border-amber-600'} disabled={busy || waiting > 0 || !ready} onClick={() => action('RETRY')}>{text('retry')}</button>}
    {(!room || room.available && ['INQUIRY','DELIVERED'].includes(room.state)) && <><button className={buttonClass} disabled={locked} onClick={() => setQuestion(text('purchaseDraft'))}>{text('purchase')}</button><textarea className="w-full rounded-xl border p-3" aria-label={text('question')} maxLength={1500} value={question} onChange={e => setQuestion(e.target.value)} disabled={locked}/><p className="text-xs text-stone-500">{text('consent')}</p><button className={buttonClass + ' bg-green-800 px-5 text-white'} disabled={locked || !question.trim()} onClick={() => action('ASK')}>{text('send')}</button></>}
    {room?.available && room.state === 'INQUIRY' && room.events.some(e => e.action === 'ASK') && <button className={buttonClass} disabled={locked} onClick={() => action('CONSENT')}>{text('consentButton')}</button>}
    {room && ['INQUIRY', 'WAITING_ROUTE', 'TRANSFER_RESERVED'].includes(room.state) && <button className={buttonClass} disabled={busy || waiting > 0 || !ready} onClick={() => action('CANCEL')}>{text('cancel')}</button>}
   </>}
  </footer>
 </section>;
}
