'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
require('ts-node').register({transpileOnly:true,compilerOptions:{module:'CommonJS',moduleResolution:'node',target:'ES2022'}});
const {parseLead}=require('../src/lib/sourceLeadRules.ts');
const {adminHeaderAdmission}=require('../src/lib/adminAdmission.ts');
const {marketplaceAdmin}=require('../src/middleware/marketplaceAdmin.ts');
const {prepare,runJob,hash}=require('./source-sync-once-core.cjs');
const NOW=new Date('2026-10-07T15:00:00Z');
function fixture(count=1){
 const rows=Array.from({length:count},(_,i)=>({archiveItemId:'SYNTHETIC-ONLY-'+i,libraryFileId:'libfile_'+'a'.repeat(32),archiveVersion:1,archiveSha256:'',title:'合成測試用品'+i,summary:'只供離線測試，非真實商品。',canonicalUrl:'https://example.com/synthetic/'+i,county:'臺北市',district:'中正區',publicPlaceName:'合成公共測試點',publicAddress:'臺北市中正區合成測試路123號',latitude:25,longitude:121.5,postedEarliestAt:'2026-10-06T01:00:00Z',postedLatestAt:'2026-10-06T02:00:00Z',checkedAt:'2026-10-07T01:00:00Z',evidence:{sourceUrl:'https://example.com/synthetic/'+i,sourcePublic:true,publicSourceRef:'source:synthetic-public-'+i,dateRef:'review:synthetic-date-'+i,locationRef:'review:synthetic-place-'+i,coordinateRef:'source:synthetic-coordinate-'+i,locationSourceUrl:'https://example.com/synthetic-place',coordinateSourceUrl:'https://example.com/synthetic-coordinate',publicPlace:true,locationType:'PUBLIC_MEETING_POINT',sourceMeetingPointConfirmed:true,independentlyReviewed:true,selfWrittenSummary:true,noCopiedTextOrImages:true,noPrivateData:true,reviewRef:'review:synthetic-review-'+i}}));
 const archiveBytes=Buffer.from(JSON.stringify({items:rows.map(r=>({id:r.archiveItemId,stock_status:'unknown',qualified:false,current_source_check:{status:'read_original_post',checked_at_utc:r.checkedAt,source_url:r.canonicalUrl}}))}));
 for(const r of rows)r.archiveSha256=hash(archiveBytes);
 const payloadBytes=Buffer.from(JSON.stringify({items:rows,dryRun:true}));
 const policy={jobId:'synthetic-job',allowWrite:true,notBefore:'2026-10-07T00:00:00Z',expiresAt:'2026-10-08T00:00:00Z',archiveSha256:hash(archiveBytes),payloadSha256:hash(payloadBytes),libraryFileId:rows[0].libraryFileId,archiveVersion:1,items:rows.map(r=>({archiveItemId:r.archiveItemId,canonicalUrl:r.canonicalUrl,checkedAt:r.checkedAt,itemSha256:hash(Buffer.from(JSON.stringify(r)))}))};
 return {archiveBytes,payloadBytes,policy,parseLead,now:()=>NOW,rows};
}
function context(f,handler){let stored,calls=[];return {...f,journal:{begin(s){if(stored)throw Error('already');stored=structuredClone(s);},save(s){stored=structuredClone(s);}},transport:async body=>{calls.push(body);return handler?handler(body,calls):{validatedCount:body.items.length,persistedCount:body.dryRun?0:body.items.length,qualifiedSupplyCount:0,...(!body.dryRun?{ids:body.items.map(()=>crypto.randomUUID())}:{})};},getStored:()=>stored,getCalls:()=>calls};}
test('formal parser accepts synthetic bound payload, batch max20 and all dry precede writes',async()=>{const c=context(fixture(41));const r=await runJob(c);assert.equal(r.state,'APPLIED_REQUIRES_READBACK');assert.deepEqual(c.getCalls().map(x=>[x.dryRun,x.items.length]),[[true,20],[true,20],[true,1],[false,20],[false,20],[false,1]]);assert.equal(r.qualifiedSupplyAdded,0);});
test('unapproved job makes no requests',async()=>{const f=fixture();f.policy.allowWrite=false;const c=context(f);assert.equal((await runJob(c)).errorCode,'JOB_NOT_APPROVED');assert.equal(c.getCalls().length,0);});
test('substituted archive fails hash',async()=>{const f=fixture();f.archiveBytes=Buffer.from('{}');const c=context(f);assert.equal((await runJob(c)).errorCode,'HASH_MISMATCH');assert.equal(c.getCalls().length,0);});
test('substituted payload fails hash',async()=>{const f=fixture();f.payloadBytes=Buffer.from('{}');assert.equal((await runJob(context(f))).errorCode,'HASH_MISMATCH');});
test('changing allowed IDs cannot admit arbitrary source',async()=>{const f=fixture();f.policy.items[0].archiveItemId='OTHER';assert.equal((await runJob(context(f))).errorCode,'ITEM_BINDING_MISMATCH');});
test('fake refreshed checkedAt mismatches observed archive',async()=>{const f=fixture();const a=JSON.parse(f.archiveBytes);a.items[0].current_source_check.checked_at_utc='2026-10-07T14:00:00Z';f.archiveBytes=Buffer.from(JSON.stringify(a));f.policy.archiveSha256=hash(f.archiveBytes);assert.equal((await runJob(context(f))).errorCode,'SOURCE_OBSERVATION_REQUIRED');});
test('duplicated IDs refused',async()=>{const f=fixture(2);f.policy.items[1]=f.policy.items[0];assert.equal((await runJob(context(f))).errorCode,'DUPLICATE_ID');});
test('expired job and source rejected',async()=>{const f=fixture();f.now=()=>new Date('2026-10-09T00:00:00Z');assert.equal((await runJob(context(f))).errorCode,'JOB_EXPIRED');const g=fixture();g.now=()=>new Date('2026-10-09T02:00:00Z');g.policy.expiresAt='2026-10-10T00:00:00Z';assert.equal((await runJob(context(g))).errorCode,'IMPORT_RULE_REJECTED');});
test('dry failure stops all writes and sanitizes secret',async()=>{const c=context(fixture(),()=>{throw Error('SYNTHETIC_SECRET_NEVER_LOG');});const r=await runJob(c);assert.equal(r.errorCode,'DRY_RUN_FAILED');assert.equal(c.getCalls().length,1);assert.ok(!JSON.stringify([r,c.getStored()]).includes('SYNTHETIC_SECRET'));});
test('timeout after write remains unknown; no automatic replay or overwritten journal',async()=>{const c=context(fixture(),b=>{if(!b.dryRun)throw Error('timeout');return {validatedCount:1,persistedCount:0,qualifiedSupplyCount:0};});assert.equal((await runJob(c)).errorCode,'WRITE_RESULT_UNKNOWN');const old=structuredClone(c.getStored());assert.equal(old.batches[0].state,'UNKNOWN_NO_RETRY');assert.equal((await runJob(c)).errorCode,'JOURNAL_UNAVAILABLE_OR_JOB_ALREADY_STARTED');assert.deepEqual(c.getStored(),old);assert.equal(c.getCalls().length,2);});
test('partial failure retains earlier batch receipts',async()=>{const c=context(fixture(21),(b)=>{if(!b.dryRun&&b.items.length===1)throw Error('lost');return {validatedCount:b.items.length,persistedCount:b.dryRun?0:b.items.length,qualifiedSupplyCount:0,...(!b.dryRun?{ids:b.items.map(()=>crypto.randomUUID())}:{})};});await runJob(c);assert.equal(c.getStored().batches[0].state,'ACKNOWLEDGED_REQUIRES_READBACK');assert.equal(c.getStored().batches[0].ids.length,20);assert.equal(c.getStored().batches[1].state,'UNKNOWN_NO_RETRY');});
test('incomplete or promoted supply ACK stays unknown',async()=>{const c=context(fixture(),b=>({validatedCount:1,persistedCount:b.dryRun?0:1,qualifiedSupplyCount:b.dryRun?0:1,ids:[crypto.randomUUID()]}));assert.equal((await runJob(c)).errorCode,'WRITE_ACK_INVALID');assert.equal(c.getStored().batches[0].state,'UNKNOWN_NO_RETRY');});
test('existing adminAdmission rejects absent and wrong substitute credentials',async()=>{const expected='SYNTHETIC_TEST_ONLY',f=fixture();let supplied='WRONG_TEST_VALUE';const c=context(f,b=>{if(adminHeaderAdmission(expected,supplied)!=='AUTHORIZED')throw Error('401');return {validatedCount:b.items.length,persistedCount:b.dryRun?0:b.items.length,qualifiedSupplyCount:0,ids:[crypto.randomUUID()]};});assert.equal((await runJob(c)).errorCode,'DRY_RUN_FAILED');assert.equal(adminHeaderAdmission(expected,undefined),'DENIED');assert.equal(adminHeaderAdmission(expected,expected),'AUTHORIZED');});
test('all successful reruns are fenced',async()=>{const c=context(fixture());await runJob(c);const saved=structuredClone(c.getStored());assert.equal((await runJob(c)).errorCode,'JOURNAL_UNAVAILABLE_OR_JOB_ALREADY_STARTED');assert.deepEqual(c.getStored(),saved);assert.equal(c.getCalls().length,2);});
test('actual admin middleware requires header and refuses URL credentials',()=>{
 const guard=marketplaceAdmin(()=> 'SYNTHETIC_TEST_ONLY');
 function attempt(headers,query={}){let admitted=false,status;const res={status(n){status=n;return this;},json(){return this;}};guard({headers,query},res,()=>{admitted=true;});return {admitted,status};}
 assert.deepEqual(attempt({'x-admin-key':'SYNTHETIC_TEST_ONLY'}),{admitted:true,status:undefined});
 assert.equal(attempt({authorization:'Bearer SYNTHETIC_TEST_ONLY'}).status,401);
 assert.equal(attempt({'x-admin-key':'WRONG'}).status,401);
 assert.equal(attempt({'x-admin-key':'SYNTHETIC_TEST_ONLY'},{key:'SYNTHETIC_TEST_ONLY'}).status,400);
});
test('journal failure stops before any network or write',async()=>{const c=context(fixture());c.journal.begin=()=>{throw Error('disk full');};assert.equal((await runJob(c)).errorCode,'JOURNAL_UNAVAILABLE_OR_JOB_ALREADY_STARTED');assert.equal(c.getCalls().length,0);});
test('job expiry during dry-run prevents apply',async()=>{const c=context(fixture());let times=0;c.now=()=>times++===0?NOW:new Date('2026-10-09T01:00:00Z');assert.equal((await runJob(c)).errorCode,'JOB_EXPIRED');assert.equal(c.getCalls().length,1);assert.equal(c.getCalls()[0].dryRun,true);});
test('CLI empty approval registry and inherited names fail closed before input or credential reads',()=>{const {spawnSync}=require('node:child_process');for(const job of ['unapproved-job','__proto__','constructor','toString']){const p=spawnSync(process.execPath,[require('node:path').join(__dirname,'source-sync-once.cjs'),job,'nonexistent-archive','nonexistent-payload'],{encoding:'utf8',env:{}});assert.equal(p.status,1);assert.deepEqual(JSON.parse(p.stdout),{state:'STOPPED',errorCode:'SYNC_SETUP_FAILED'});assert.equal(p.stderr,'');}});
test('real private filesystem journal persists partial result and fences process recreation',async()=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{createJournal}=require('./source-sync-journal.cjs');
 const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'wishlist-synthetic-journal-')));fs.chmodSync(dir,0o700);
 try{const c=context(fixture());c.journal=createJournal(dir,c.policy.jobId);const result=await runJob(c);assert.equal(result.state,'APPLIED_REQUIRES_READBACK');const file=path.join(dir,c.policy.jobId+'.json'),before=fs.readFileSync(file);assert.equal(fs.statSync(file).mode&0o777,0o600);c.journal=createJournal(dir,c.policy.jobId);assert.equal((await runJob(c)).errorCode,'JOURNAL_UNAVAILABLE_OR_JOB_ALREADY_STARTED');assert.deepEqual(fs.readFileSync(file),before);assert.equal(c.getCalls().length,2);}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('journal refuses public permissions, symlink directories and stale next files',()=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{createJournal}=require('./source-sync-journal.cjs');
 const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'wishlist-synthetic-journal-')));
 try{fs.chmodSync(dir,0o755);assert.throws(()=>createJournal(dir,'test-job'));fs.chmodSync(dir,0o700);const link=dir+'-link';fs.symlinkSync(dir,link);try{assert.throws(()=>createJournal(link,'test-job'));}finally{fs.unlinkSync(link);}const j=createJournal(dir,'test-job');j.begin({state:'APPLY_STARTED'});fs.writeFileSync(path.join(dir,'test-job.json.next'),'retained-crash-marker',{mode:0o600});assert.throws(()=>j.save({state:'DONE'}));assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'test-job.json'))).state,'APPLY_STARTED');assert.equal(fs.readFileSync(path.join(dir,'test-job.json.next'),'utf8'),'retained-crash-marker');}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
